### ISSUE TITLE
Handle Errors Seamlessly

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#110]
When the cluster reconfigures, like a leader moving to a different broker, the protocol implementation will raise an error. We need to be certain that both the cluster model and the active consumer/producer are updated.

  - [ ] Make sure relevant errors are caught
  - [ ] Update cluster model to reflect changes
  - [ ] Reconfigure active consumer or producer

**Comment by emmett9001** [comment]
What are some cases that we'll need to handle here? I imagine these changes will look a bit like [this](https://github.com/Parsely/pykafka/blob/dd93ef3e5650c7236ae86a46c7708d53defd4a2b/kafka/pykafka/partition.py#L75). If partitions are always updating their own leaders, what else is there to do here? What are specific error cases that need to be caught?

**Comment by kbourgoin** [comment]
My plan was to go through the error list [here](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ErrorCodes) and handle the exception they'd throw in the broker.

The workflow I have in my head is:

  1. Try operation
  2. Catch exception we know how to handle
  3. Call `cluster.update()`
  4. Try again

This works great in a single-threaded environment. What's going to be hard is reasoning through where the locks need to be and what can go wrong in the worst cases.  I'm hoping a single cluster-wide lock to pause the whole thing while updating works, but I don't know for sure.  This hasn't gotten beyond the "vague idea" state for me.

**Comment by emmett9001** [comment]
Related to https://github.com/Parsely/pykafka/issues/126
