### ISSUE TITLE
Finish Combined C/Python model

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#111]
We've started an interface that both the Python and librdkafka code will implement.  This needs to be finished and documented.  Finishing it will be ongoing work as we do the implementations, since things will certainly change.

  - [x] Docstrings for everything in [base.py](https://github.com/Parsely/pykafka/blob/master/kafka/base.py)
  - [ ] Finalize model

**Comment by emmett9001** [comment]
The model as it exists now currently supports the Balanced and Simple consumers. There may still be other changes depending on how much the rdkafka side of the project needs to change base.py.

**Comment by kbourgoin** [comment]
I think this is ready to close. We're in really good shape here.
