### ISSUE TITLE
Increase Test Coverage

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#112]
Some unit tests for the protocol implementation and model were working a year ago when I started the 0.8.x upgrade.  They've since broken as files have gotten moved and interfaces changed slightly.  This needs to be fixed.

**Comment by emmett9001** [comment]
The [protocol unit tests](https://github.com/Parsely/pykafka/blob/master/tests/kafka/pykafka/test_protocol.py) are working now. I've also added tests for the [BalancedConsumer](https://github.com/Parsely/pykafka/blob/master/tests/kafka/test_balancedconsumer.py) and pykafka's [SimpleConsumer](https://github.com/Parsely/pykafka/blob/master/tests/kafka/pykafka/test_simpleconsumer.py)

**Comment by kbourgoin** [comment]
Updated title to reflect that we have *some* tests, but need a boatload more before we can call this done/ready.

**Comment by emmett9001** [comment]
We've got some integration tests working now for the main components, so we can move this to the next milestone for now.

**Comment by kbourgoin** [comment]
Let's just kill it. We've hit 80%, which I set as passing in coveralls.  We'll just need to make sure that new additions have tests so that the suite grows with the project.
