### ISSUE TITLE
SimpleConsumer Implementation

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#115]
Implement a python version of the SimpleConsumer. Work in progress in [this pull request](https://github.com/Parsely/pykafka/pull/137).

  - [x] Rename `Consumer` to `BaseSimpleConsumer` in `base.py`
  - [x] Finish implementation that's been started in `pykafka/consumer.py`
  - [x] Unit test `SimpleConsumer`

**Comment by yungchin** [comment]
- [ ] update rdkafka.SimpleConsumer to match interface

**Comment by emmett9001** [comment]
Not sure what `abstrct.py` refers to from the first checklist item. I see there's already a `SimpleConsumer` in `pykafpa/consumer.py`. Is that the one this ticket is about?

**Comment by yungchin** [comment]
Yes, that should be the one this is about - I believe it's still WIP. And abstract.py has been renamed base.py - it's meant to serve as the "interface definition" shared between kafka.pykafka and kafka.rdkafka.

**Comment by emmett9001** [comment]
Some things I notice reading the [kafka-python implementation](https://github.com/mumrah/kafka-python/blob/master/kafka/consumer/simple.py):

* The kafka-python `SimpleConsumer` actually subclasses its `Consumer` class, allowing it to use `commit` and other functions from that class. The stub in our `SimpleConsumer` does not currently subclass the existing `Consumer` (in `kafka/pykafka/consumer.py`) - should it?
* More generally, what is the status of `kafka/pykafka/cosumer.py`? It appears to be defunct, or at least out of date - should I be adding new functionality to it, porting what's there to some other location, or ignoring it completely? The `SimpleConsumer` implementation in kafka-python uses the Offset Commit/Fetch API, but only by way of its extension of the base `Consumer` class and its `commit` function.

**Comment by emmett9001** [comment]
Answers to the above from conversations with @kbourgoin 

The kafka-python `SimpleConsumer` does do roughly the same thing that we need ours to, but we don't need to stick to any design decisions in that library such as subclass/superclass relationships. We can think of our `SimpleConsumer` as roughly the combination of kafka-python [Consumer](https://github.com/mumrah/kafka-python/blob/master/kafka/consumer/base.py#L30) and [SimpleConsumer](https://github.com/mumrah/kafka-python/blob/master/kafka/consumer/simple.py#L68).

`kafka/pykafka/consumer.py` is dead and should be deleted. All offset committing and fetching in our new implementation should indeed use the Offset Commit/Fetch API.

**Comment by emmett9001** [comment]
I merged the `SimpleConsumer` pull request, so @yungchin should be good to start writing the rdkafka version to match it.

**Comment by emmett9001** [comment]
I wrote some meaningful unit tests for the `OwnedPartition`. Looking over `SimpleConsumer`, it seems that returns will diminish from writing unit tests for that class. It does almost no bookkeeping of its own (pushing that off onto `OwnedPartition`) and would really benefit from some integration tests.

**Comment by emmett9001** [comment]
This branch is merged, so for now I'm moving on to the `BalancedConsumer` implementation.

**Comment by kbourgoin** [comment]
Moved the librdkafka task to another ticket and closing this one out.
