### ISSUE TITLE
BalancedConsumer Implementation

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#116]
Implement a `BalancedConsumer` that manages one or more `SimpleConsumer`s and balances their use of partitions. The balancing algorithm has been implemented correctly in the old code, so that can be used again, or as a reference, for the new implementation.

We should only need one implementation of this for both the python and librdkafka sides of the driver.  If we use `SimpleConsumer`s to control which partitions we read from, it should be possible to use the same code for both paths.

**Comment by kbourgoin** [comment]
The code for the previous implementation can be found [here](https://github.com/Parsely/pykafka/blob/b97401ce98cfbe2bccbf1dac95e65fea25f1a6b5/samsa/consumer/consumer.py#L214).

It may also be helpful to look at the description of the algorithm itself, which can be found [here](http://kafka.apache.org/documentation.html).  Search the page for "Consumer rebalancing algorithm".

**Comment by emmett9001** [comment]
@kbourgoin It's not completely clear to me what you mean by "use SimpleConsumers to control which partitions we read from". Currently I'm imagining that I'll implement a function similar to the old `decide_partitions` in the new `BalancedConsumer` and use its output as the `partitions` kwarg of `SimpleConsumer`. Does this generally match what you had in mind?

**Comment by kbourgoin** [comment]
Yeah, precisely that.

**Comment by emmett9001** [comment]
Today I started the new BalancedConsumer implementation, largely based on the old samsa.consumer.consumer.Consumer. I've gotten it to the point where consumption is being correctly balanced between one to three consumers of a five-partition cluster (these are just the tests I've been doing).

**Comment by emmett9001** [comment]
`BalancedConsumer` is working well. I've added support for a bunch of different configuration options from the kafka documentation and tested the consumer with up to 15 partitions shared between up to 8 consumer instances. It all works well.

**Comment by emmett9001** [comment]
Time to start testing the BalancedConsumer. The branch is merged, so we'll soon being testing it in an 0.8.2.1 cluster.
