### ISSUE TITLE
Set up ReadTheDocs

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#117]
Make sure it's generating some sensible for old versions and under the new pykafka name.

  - [x] Convert README.md to README.rst because it's also introduction.rst in the docs.
  - [x] Double-check old versions of the docs are accessible.
  - [x] Verify pykafka.readthedocs.org works.
  - [x] Clean up docstrings for all modules
  - [x] Write page on common usage patterns (quickstart)
  - [x] Update readme

**Comment by emmett9001** [comment]
http://pykafka.readthedocs.org/en/latest/
