### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#120]
Possibly not going into 0.8.2-01, but we should be sure to not forget about this.

**Comment by emmett9001** [comment]
Work in progress https://github.com/Parsely/pykafka/pull/144

**Comment by mcandre** [comment]
+1

**Comment by emmett9001** [comment]
A lot has happened since work on this started, and the current most promising pull request is [here](https://github.com/Parsely/pykafka/pull/231) thanks to @sontek. Figuring out a testing workflow around this will be my first priority once #177 is merged.

**Comment by emmett9001** [comment]
@sontek's branch is looking pretty good now - as far as I'm concerned it's ready for merging. We'll need to add a bit of documentation about the preferred way to run tests under three interpreters.

**Comment by rduplain** [comment]
#231

**Comment by emmett9001** [comment]
#246 merged! :tada: :tada: :tada: :tada: :partly_sunny: :tada:

**Comment by mcandre** [comment]
:+1:
