### ISSUE TITLE
Kafka Metrics Reporting

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#121]
The Scala drivers has this built in, and it's something that could be very useful. To start, a graphite metrics reporter would be very handy, but it should be easily extensible to other systems.

**Comment by gg7** [comment]
+1

**Comment by emmett9001** [comment]
If I understand the feature request correctly, this would constitute a new API entirely separate from the existing producer/consumer interface. This new API might be exposed similarly to the `cli` module. I can't conceptualize this in a way that makes sense if metrics reporting is included in the main produce/consume loop.

I imagine the only metrics that would make sense to report from the client library are lag values for active consumer groups. Are there other metrics we'd want to support? If not, I really don't know what this feature actually looks like given that [`fetch_consumer_lag`](https://github.com/Parsely/pykafka/blob/5b860fdfa53422adc4ff089e97afec8cdf898d1f/pykafka/cli/kafka_tools.py#L44) already exists.
