### ISSUE TITLE
Change kafka to pykafka

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#123]
`kafka` is already taken by `python-kafka` so no need to step on their namespace.

**Comment by emmett9001** [comment]
By this do you mean changing `pykafka/kafka` to `pykafka/pykafka`? If so, I'll just grab it.

**Comment by amontalenti** [comment]
Yes, pretty much, @emmett9001. We need the actual root Python package/module name to be `pykafka`.
