### ISSUE TITLE
Python AsyncProducer Implementation

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#124]
Moving this implementation to 0.8.2-02 because we at least have a sync producer implementation in Python.

**Comment by emmett9001** [comment]
Is there a good reference point for the design of an async producer? Maybe another project that implements something similar or a kafka project design document. Given that, I can probably put one together.

**Comment by kbourgoin** [comment]
That's the best idea I have.  The need for it was taken from the fact that there is a Scala one, so I've got no better source

**Comment by yungchin** [comment]
The librdkafka docs may be of interest too: https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#producer-api

The approach there is that the underlying producer is always async; implementing a sync producer on top of it basically means producing through the async producer, and then waiting for the message delivery report(s) before returning:
https://github.com/edenhill/librdkafka/wiki/Sync-producer
(we did exactly that on the cffi branch: https://github.com/Parsely/pykafka/blob/feature/archived_rdkafka_cffi/pykafka/rdkafka/producer.py#L71 )

**Comment by emmett9001** [comment]
Started work on this [here](https://github.com/Parsely/pykafka/tree/feature/async-producer). It's still very prototypal, but I figured out some basic things. It's nowhere near ready for review.

**Comment by emmett9001** [comment]
Pull requested [here](https://github.com/Parsely/pykafka/pull/177). It's ready for initial review from @kbourgoin and/or @yungchin.

**Comment by emmett9001** [comment]
Ready for final review and merge

**Comment by emmett9001** [comment]
Merged!
