### ISSUE TITLE
pykafka.Cluster.update() needs to be thread-safe

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#126]
It's not right now, but there's no telling where/when this is going to be called. We'll have to figure out what the implications of a reconfiguration are and how locking should occur.

**Comment by emmett9001** [comment]
Related to https://github.com/Parsely/pykafka/issues/110

**Comment by kbourgoin** [comment]
Going to mark this resolved.  This was opened because thread-safety for samsa was a challenge, but looking the code most of those issues aren't present here. Those were mostly around using `.itervalues()` and things like that, which we just don't do on objects that change during an update.

Having the broker be thread-safe and the cluster update in-place really should be sufficient to call this thread-safe.

I'm sure at some point testing will prove me wrong, of course. ;)
