### ISSUE TITLE
Ensure auto-creating topics works

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#128]
Both the producer and consumer should be able to handle topics that don't exist yet.

- [ ] python implementation
- [x] librdkafka implementation

**Comment by yungchin** [comment]
Ack. On the rdkafka side, I'm planning to add some magic to rdkafka.cluster.topics for this.

**Comment by kbourgoin** [comment]
What are you thinking there? I haven't done any work on the python side yet, so I'm not entirely sure where it would live. I was thinking to create essentially a VirtualTopic class which would handle things until it was replaced by a real `Topic` at some point.  Not really sure that works, though.

**Comment by yungchin** [comment]
I'm not entirely sure yet, but I think it would work ok if cluster.topics
gets a __missing__ method that just creates a new Topic (so the first
access would be a little slow perhaps)?

**Comment by kbourgoin** [comment]
Yeah, I think that's how it'll have to be done.  I need to verify that this even works in Kafka since auto-creating topics was broken on 0.8.0.  I'm assuming it's been fixed since then.

**Comment by yungchin** [comment]
Yep, I've seen it work fine both on kafka 0.8.1 and 0.8.2 - one way to trigger creation is to do a metadata request on that specific topic name. That might be a nice call to stick in a __missing__() method.
