### ISSUE TITLE
Implement Partition.latest/earliest_offset

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#130]
For this we'll have to hook up librdkafka's statistics-callback (and decide which rdkafka-handle to derive the information from, ideally not wasting too many resources on it).

**Comment by emmett9001** [comment]
For reference, here's the [pykafka implementation](https://github.com/Parsely/pykafka/blob/master/kafka/pykafka/partition.py#L73-L79)

**Comment by yungchin** [comment]
Closing this, because in the new approach we'd just handle this through the python implementation.
