### ISSUE TITLE
Docker-based environment for integration testing

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#132]
I suppose there's not much to unittest on the rdkafka side of things, because all the functionality is really in the underlying libs, but it would be really helpful to have integration tests so bumping versions can be done safely. 

There's a start for this in the dockerise branch, but there's a lot more plumbing to do to tie it into nose etc.

**Comment by kbourgoin** [comment]
I'm going to close this in favor of our current integration test setup.

**Comment by yungchin** [comment]
Thanks, was just about to come here to do the same! Your testinstances setup works great here, and it's indeed much easier to avoid a 'dirty' cluster causing odd interactions between test runs.
