### ISSUE TITLE
SimpleConsumer for librdkafka

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#146]
Status: there's a working `RdkSimpleConsumer` which derives from `pykafka.SimpleConsumer` without changing the interface (see [here][0]). My `%timeit` results are somewhat noisy, but I generally see 4-7 microsecs per `consume` call vs 25-50 microsecs for the pure-python consumer (where me == @yungchin, as I've just edited this summary...).

[0]: https://github.com/Parsely/pykafka/blob/e475d9703f7903e1e9272503583f2ec45f8f21ce/pykafka/rdkafka/simple_consumer.py#L5

Still to do:
- [ ] passing `SimpleConsumer.__init__` config settings into the underlying rdkafka consumer
- [ ] wrap error conditions in the C module in meaningful exceptions (I've marked these `TODO` in the code)
- [ ] figure out if the python side needs more exceptions out of the rdkafka consumer: most cluster reconfiguration error responses and the like are absorbed as a matter of course, so I'm wondering if `KafkaClient.cluster` and co will need more explicit updates to stay informed?
- [ ] integration testing (there's a separate issue for this)
- [ ] hook up logging (also has a separate issue)
- [ ] take a shot at redefining `_rd_kafka.Message` to expose the payload through the buffer API rather than doing a string copy

**Comment by kbourgoin** [comment]
This sounds like it may be as simple as making the interfaces line up, btw.

**Comment by yungchin** [comment]
This is now underway in renewed form at https://github.com/Parsely/pykafka/tree/feature/rdkafka_extension - I'll update the description above to track what still needs doing.

**Comment by yungchin** [comment]
Tracking this in #176 from now.
