### ISSUE TITLE
SimpleConsumer: default `consumer_group=None` breaks offset manager

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#150]
If no `consumer_group` name is passed-in when initing a `pykafka.SimpleConsumer`, I get a `TypeError: object of type 'NoneType' has no len()` out of `cluster.get_offset_manager()`. I'm not immediately clear what the preferred solution is here - I suppose you always want _some_ default to store offsets under, or should an unspecified group imply disabling offset storage?

**Comment by emmett9001** [comment]
A `None` group is supposed to disable offset storage in the `SimpleConsumer`. I'll find this and just pass if it's not present.

**Comment by emmett9001** [comment]
Added a fix in master https://github.com/Parsely/pykafka/commit/edc5e8b143f9e86361debdace60624d408e5750c

**Comment by yungchin** [comment]
Works great - thanks!
