### ISSUE TITLE
Don't log error numbers

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#160]
Messages like this aren't super useful: `Error committing offsets for topic pixel_logs (error codes: [7])`.  Instead, we should wrap those with the name when possible.

**Comment by emmett9001** [comment]
Fixed here https://github.com/Parsely/pykafka/commit/8b38e194f275abd86276ef6d0bd97344bd5044b9

**Comment by kbourgoin** [comment]
Wow. That was fast.  :clap:
