### ISSUE TITLE
Add manual committing to BalancedConsumer

### ISSUE THREAD

**Issue by Kaydannik** [Parsely/pykafka#161]
Hello.
Sorry, may be its not a very smart question. 
But how to commit offset when i am using balanced consumer ? 

Main thing - calculate stream and store results in external DB. For prevent counters overlaps - i need to commit offset at exact position.
Thanks for advice

**Comment by kbourgoin** [comment]
Hi there,

We don't currently support that, but plan on doing so before our official release.

**Comment by emmett9001** [comment]
You can actually do this with

    balancedconsumer._consumer.commit_offsets()

but this is undocumented. I've added a wrapper [here](https://github.com/Parsely/pykafka/commit/492caa9ba953b01b4ec42cf52b5219279e7c46b3) that allows users to manually commit offsets like this:

    con = BalancedConsumer()
    con.commit_offsets()
