### ISSUE TITLE
Add Periodic Re-checks to BalancedConsumer

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#163]
I don't trust Zookeeper.  Very rarely, it fails to send events when topics/brokers/etc change.  We should add a periodic re-check to make sure what the consumer is consuming is what zookeeper thinks it's consuming.

**Comment by emmett9001** [comment]
The most important thing to check here is whether the zookeeper nodes created by [this call](https://github.com/Parsely/pykafka/blob/35ad8c77c4ec75ac9eec5824b2368f0439273fb8/pykafka/balancedconsumer.py#L432-L436) correspond to the internally-held [list of partitions](https://github.com/Parsely/pykafka/blob/35ad8c77c4ec75ac9eec5824b2368f0439273fb8/pykafka/balancedconsumer.py#L437). This can run on another background thread that only wakes up once every two or three autocommit cycles.

**Comment by emmett9001** [comment]
I think this works, let me know what you think. https://github.com/Parsely/pykafka/pull/171/files
