### ISSUE TITLE
Snappy Compression is (probaby) broken

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#165]
[This commit](https://github.com/Parsely/pykafka/commit/92f7460784cd38e38a793db3188ece41bc8f085e) stopped us from stripping snappy headers, but that only works part of the time.  [This](https://github.com/mumrah/kafka-python/pull/127/files) Pull Request has us thinking that our snappy implementation is deficient.  So, this needs more investigation and testing before we can really consider it "done".

**Comment by emmett9001** [comment]
I'll try [this commit](https://github.com/Parsely/pykafka/commit/6af28fca01d3716ead983f9efa41e6db983073f7) against some topic or another.

**Comment by emmett9001** [comment]
Tested against Parsely's internal topic, seems to be working fine.
