### ISSUE TITLE
reset_offset_on_start edge case

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#167]
The situation:

* Run a `BalancedConsumer` with `reset_offset_on_start=True` and `auto_commit_enable=True`.
* Observe that it starts at the latest available offset.
* Before the first autocommit, start another `BalancedConsumer` with the same settings.
* Observe that the first consumer consumes the entire history of the topic.

This is an error. It happens because `_reset_offsets` is not called on rebalances. Since the rebalance happens before an autocommit has occurred, the initial `fetch_offsets` call after the rebalance finds nothing and defaults to `0`. `_reset_offsets` is not called on rebalances since it can result in dropped messages: any messages produced during the rebalance will be skipped when the newly created internal consumer goes straight to `OFFSET_LATEST`.

How should this be handled? The current workaround is to set `auto_commit_interval` to a short enough timespan that this situation is very unlikely to happen, but it feels like we should have a smarter way of dealing with this.

Input from @kbourgoin welcome.

**Comment by emmett9001** [comment]
This can be avoided by committing offsets immediately before a rebalance starts - we should look into that.

**Comment by kbourgoin** [comment]
It's how samsa did it, and I think maybe it should be configurable, but for now having it commit before the rebalance should be sufficient to handle the corner case.
