### ISSUE TITLE
blocking consume on empty topic => 100% cpu utilization

### ISSUE THREAD

**Issue by ltucker** [Parsely/pykafka#172]
First, glad to see this coming along. A meaningful python client with a balanced consumer is a very welcome sight!

One issue I've noticed is that the "blocking" consume() is a very busy loop currently (simple or a balanced-with-simple-inside) eg, the following causes 100% cpu utilization on the current trunk for me:

```
import pykafka

if __name__ == '__main__':
    client = pykafka.KafkaClient()
    topic = client.topics['some.empty-topic']
    consumer = topic.get_simple_consumer()
    for message in consumer:
        # never really even gets here...
        if message is not None:
            print message.offset, message.value
```

It would be interesting to see a select-like-behavior across the partitions with a timeout though I'm sure that's not exactly trivial. The block=False also appears has a very high rate of returning None even if one or more partitions have messages waiting so it is not easy to use non-busily either currently...

**Comment by emmett9001** [comment]
Hi @ltucker, thanks for filing this. I'll be taking a look at it today. I'm wondering if you can elaborate on what you mean by "select-like-behavior".

**Comment by ltucker** [comment]
Hey @emmett9001, mainly my expectation would just be a very quiet cpu when blocking and perhaps to be able to have a specifiable timeout for how long to block (even in the balanced case)

In referring to select-like-behavior, I mean the select/poll/epoll/kqueue family of calls that wait (quietly) for read/write readiness from a set of file descriptors and wake when such a condition arises or a timeout has expired.

I know that's not what's directly under the hood here (visiting and testing a lot of Queues and so forth) -- I can imagine perhaps some sleeping/signaling through threading.Event or Condition, but again probably not totally trivial in the way it's designed.

**Comment by emmett9001** [comment]
I see, thanks for the detail. If I understand your comment about a blocking timeout, that actually already exists [here](https://github.com/Parsely/pykafka/blob/master/pykafka/simpleconsumer.py#L293). It may be slightly confusing that the timeout isn't a kwarg on `consume()`, but you can set it when you create the consumer:
```python
consumer = topic.get_simple_consumer(consumer_timeout_ms=1 * 1000)
```
This tells all subsequent calls to `consume()` with `block=True` (the default) to stop blocking after 1000 milliseconds. Maybe you can try this out and see if you can get some more acceptable behavior as a workaround.

**Comment by ltucker** [comment]
@emmett9001 oh yeah I see that (for simpleconsumer only though), but the main issue for me the cpu.  With or without that set, it's in a busy loop when blocking and running at 100% cpu.

**Comment by ltucker** [comment]
I tossed a branch up with a potential solution... Works-For-Me (TM), feel free to use / rework or ignore :)

**Comment by emmett9001** [comment]
Thanks for this - I'll check it out today and see what feedback I can give. @kbourgoin may also give it a look at some point.

**Comment by emmett9001** [comment]
Tested and merged the branch. Give master a try now.

**Comment by ltucker** [comment]
Looks good to me now, feel free to close.

One other thing here that occurred to me, since that included a backport from python3.4 that Semaphore block should probably display the python copyright notice and/or license.  I can also throw that code up as a separate 'semaphore-backport' package on pypi if that's preferable for isolation.

**Comment by emmett9001** [comment]
I've added the copyright notice to `Semaphore`. Thanks for pointing that out.
