### ISSUE TITLE
PyKafka installation

### ISSUE THREAD

**Issue by elachman** [Parsely/pykafka#174]
I am looking to test out pykafka however I could not figure out how to install it and get started. It seems the last release and pip version was in march 2014 under Samsa and it looks like there have been a significant amount of changes since then. So what is the best option to get started with this?

**Comment by emmett9001** [comment]
Currently the best way to install pykafka is to clone this repository and run
```
python setup.py install
```
 We're currently testing the newest version in production at Parse.ly, and will be releasing it on PyPI once the bugs have been sufficiently ironed out.
