### ISSUE TITLE
topic is not created when TopicDict is empty

### ISSUE THREAD

**Issue by Wombasta** [Parsely/pykafka#175]
The new topic is not auto-created with error when no topics exist on kafka brokers (the TopicDict is empty {} ) 
```  
  File "/usr/local/lib/python2.7/dist-packages/pykafka/cluster.py", line 45, in __missing__
    if self._create_topic(key):
  File "/usr/local/lib/python2.7/dist-packages/pykafka/cluster.py", line 63, in _create_topic
    self._cluster.brokers[self._cluster.brokers.keys()[0]].request_metadata(topics=[topic_name])
IndexError: list index out of range
```
As soon as the random topic was created on broker manually, the new topic can be easily auto-created as designed.

**Comment by kbourgoin** [comment]
The index error is actually from the broker list being empty, not the topic dict. It's part of a [known issue](https://issues.apache.org/jira/browse/KAFKA-2154) with Kafka. I put a warning [here](https://github.com/Parsely/pykafka/blob/35ad8c77c4ec75ac9eec5824b2368f0439273fb8/pykafka/cluster.py#L263-L268) about it, but I'll update the text to include that topic auto-creation won't work.
