### ISSUE TITLE
Consider addind default values to variables documentation

### ISSUE THREAD

**Issue by eltermann** [Parsely/pykafka#178]
I needed to open the source code to learn that producer's `max_retries` defaults to 3. It would be great if this was explicit on variable description.

**Comment by emmett9001** [comment]
Default argument information is contained in the __init__ function specification for each class. For `Producer`, it's [here](http://pykafka.readthedocs.org/en/latest/api/producer.html#pykafka.producer.Producer). We could maybe also put it in the docstring, but I'm not keen on duplicating that information.

**Comment by eltermann** [comment]
Oh, that's enough then.
Just noticed that "Init signature" is available at ipython information, via:

```
In [1]: import pykafka
In [2]: pykafka.Producer?
```

Thank you.
