### ISSUE TITLE
Support binary message

### ISSUE THREAD

**Issue by amiorin** [Parsely/pykafka#179]
Reading the source code and the manual (http://pykafka.readthedocs.org/en/latest/api/producer.html#pykafka.producer.Producer.produce), it looks there is no support for binary messages.
Only string messages are supported.
Why is that?

**Comment by kbourgoin** [comment]
Huh, that's actually a holdover from samsa which I never questioned. We only use Kafka for string data, so it never even occurred to me.  We'll add that into the next release, to accept any byte data instead of just strings.

**Comment by yungchin** [comment]
As this is all python2 for now, `str` are just `bytes`, not unicode.
So you should be able to send anything that can be serialised to
`bytes`.

Thanks

**Comment by amiorin** [comment]
thx. I'll try with thrift.

**Comment by yungchin** [comment]
I've just pushed a test that produces and consumes a binary string, so this should hopefully work for you as is.

**Comment by amiorin** [comment]
thx, I'll check it out
