### ISSUE TITLE
Cannot consume from topic ("Partition 0 above max queued count (queue has 16586)")

### ISSUE THREAD

**Issue by htch** [Parsely/pykafka#185]
I have been using pykafka for a short while and enjoyed it so far. But at one point my code became unable to read from one of the topics, no matter the consumer group or offset (-1, 0 or 1068127). This is the debug output that I get:

    INFO:pykafka.cluster:Discovered 1 brokers
    DEBUG:pykafka.cluster:Discovered broker id 0: pavels-mbp.it.local:9092
    INFO:pykafka.cluster:Discovered 33 topics
    INFO:pykafka.topic:Adding 1 partitions
    DEBUG:pykafka.topic:Adding partition test1/0
    DEBUG:pykafka.cluster:Discovered topic <pykafka.topic.Topic at 0x10305fbd0 (name=test1)>
    INFO:pykafka.topic:Adding 1 partitions
    DEBUG:pykafka.topic:Adding partition pks/0
    DEBUG:pykafka.cluster:Discovered topic <pykafka.topic.Topic at 0x10305fc90 (name=pks)>
    INFO:pykafka.topic:Adding 1 partitions
    DEBUG:pykafka.topic:Adding partition AppLaunchedEvent/0
    DEBUG:pykafka.cluster:Discovered topic <pykafka.topic.Topic at 0x10305fd10    (name=AppLaunchedEvent)>
    INFO:pykafka.topic:Adding 1 partitions
    DEBUG:pykafka.topic:Adding partition global/0
    DEBUG:pykafka.cluster:Discovered topic <pykafka.topic.Topic at 0x10305fd50 (name=global)>
    INFO:pykafka.topic:Adding 1 partitions
    DEBUG:pykafka.topic:Adding partition InviteSentEvent/0
    DEBUG:pykafka.cluster:Discovered topic <pykafka.topic.Topic at 0x10305fe10 (name=InviteSentEvent)>
    INFO:pykafka.topic:Adding 1 partitions
    DEBUG:pykafka.topic:Adding partition general/0
    DEBUG:pykafka.cluster:Discovered topic <pykafka.topic.Topic at 0x10305fe50 (name=general)>
    ...
    INFO:pykafka.topic:Adding 1 partitions
    DEBUG:pykafka.topic:Adding partition test11/0
    DEBUG:pykafka.cluster:Discovered topic <pykafka.topic.Topic at 0x10306ea10 (name=test11)>
    INFO:pykafka.cluster:Attempting to discover offset manager for consumer group 'default'
    INFO:pykafka.cluster:Found coordinator broker with id 0
    DEBUG:pykafka.simpleconsumer:Fetching offsets for 1 partitions from broker id 0
    DEBUG:pykafka.simpleconsumer:Set offset for partition 0 to -1
    INFO:pykafka.simpleconsumer:Starting 1 fetcher threads
    DEBUG:pykafka.simpleconsumer:Fetching offsets for 1 partitions from broker id 0
    DEBUG:pykafka.simpleconsumer:Set offset for partition 0 to -1
    INFO:pykafka.simpleconsumer:Starting 1 fetcher threads
    DEBUG:pykafka.simpleconsumer:Fetching offsets for 1 partitions from broker id 0
    DEBUG:pykafka.simpleconsumer:Set offset for partition 0 to -1
    INFO:pykafka.cluster:Discovered 1 brokers
    DEBUG:pykafka.cluster:Discovered broker id 0: pavels-mbp.it.local:9092
    DEBUG:pykafka.simpleconsumer:Fetched 16586 messages for partition 0
    DEBUG:pykafka.simpleconsumer:Partition 0 queue holds 16586 messages
    DEBUG:pykafka.simpleconsumer:Partition 0 above max queued count (queue has 16586)
    DEBUG:pykafka.simpleconsumer:Partition 0 above max queued count (queue has 16586)
    DEBUG:pykafka.simpleconsumer:Partition 0 above max queued count (queue has 16586)
    DEBUG:pykafka.simpleconsumer:Partition 0 above max queued count (queue has 16586)
    DEBUG:pykafka.simpleconsumer:Partition 0 above max queued count (queue has 16586)
    DEBUG:pykafka.simpleconsumer:Partition 0 above max queued count (queue has 16586)
    ...

The log message is being left [here](https://github.com/Parsely/pykafka/blob/0431280d6e2a68736e04fd91614f2dc028f087a6/pykafka/simpleconsumer.py#L496), so apparently pykafka refuses to make fetch requests should `queued_max_messages` be above certain message count. As described in the docs, `queued_max_messages` is a "Maximum number of messages buffered for consumption". So far I couldn't make any sense of this piece of knowledge.

I'm not at all sure if it is a programming problem, a configuration problem or a genuine problem with pykafka, perhaps a documentation problem more likely than anything else.

**Comment by emmett9001** [comment]
Hi @htch, thanks for posting this. Do you mind including a bit of code that shows the context in which you're starting your consumer? I'm a bit surprised to see multiple instances of
```
INFO:pykafka.simpleconsumer:Starting 1 fetcher threads
```
and it's hard to say why it's happening without seeing how you're setting things up. Thanks!

`queued_max_messages`, by the way, is the maximum size of the internal per-partition queue into which the consumer places messages it fetches before they're removed by a call to `consume`. This is also a possible issue: are you calling `consume` or `__iter__` on your consumer anywhere? If not, these messages would just sit in the consumer's queue indefinitely.

**Comment by htch** [comment]
Hi @emmett9001 and thanks for quick reply.

This is the code, which is a bit verbose. Indeed there is more than one consumer, in fact two of them, simulateneously consuming from different topics and one producer as well.

// pk_owner.py

    import logging
    import time
    from datetime import datetime

    from resources import make_kafka_client, make_zk_client

    logger = logging.getLogger(__name__)

    kafka_client = make_kafka_client()
    zk_client = make_zk_client()

    class SessionState(object):
        def __init__(self):
            self.memo_table = None
            self.lock = zk_client.Lock("/pk_lock", "act")
            self.topic = kafka_client.topics["pks"]
            self.consumer = self.topic.get_simple_consumer(
                consumer_group="default",
                auto_commit_enable=False
            )
            # demands setting topic.log.retention.hours to forever ("-1" ?)
            self.consumer.start()
            time.sleep(0.1)         # waiting as consumer starts off
            self.initial_consumer_offset = 0
            for _, partition in self.consumer.fetch_offsets():
                # assumes there's only one partition
                if not partition.offset == -1:
                    self.initial_consumer_offset = partition.offset
            if not self.initial_consumer_offset == 0:
                logger.debug("starting with non-zero offset of %i", self.initial_consumer_offset)
            self.producer = kafka_client.topics["pks"].get_producer()


    session_state = SessionState()

    def get_pk(pk):
        def load():
            offset = [offsets.offset[0] for offsets in session_state.topic.latest_available_offsets().values()][0]
            logger.debug("preparing to fetch %i records", offset)
            for i, message in enumerate(session_state.consumer):
                session_state.memo_table[message.value] = message.offset - session_state.initial_consumer_offset
                if (i + 1) % 10000 == 0:
                    logger.debug("%i records already fetched", message.offset)
                if message.offset + 1 >= offset:
                    break

        if session_state.memo_table is None:
            session_state.memo_table = {}
            logger.debug("requesting lock | 1")
            with session_state.lock:
                logger.debug("entering lock | 1")
                load()
                logger.debug("leaving lock | 1")

        if pk in session_state.memo_table:
            return session_state.memo_table[pk]

        logger.debug("requesting lock | 2")
        with session_state.lock:
            logger.debug("entering lock | 2")
            # making sure pk is still unknown to all other workers
            load()

            if pk in session_state.memo_table:
                return session_state.memo_table[pk]
            
            # adding pk to the feed
            session_state.producer.produce([pk])

            time.sleep(0.1)     # waiting enough for our change to propagate
            
            # getting the id for pk
            load()

            if pk in session_state.memo_table:
                return session_state.memo_table[pk]
            
            logger.debug("leaving lock | 2")

        raise RuntimeError("leaving without a pk")

// index_active.py

    # ...

    from workers.pk_owner import get_pk
    from workers.type1.common import keep_state, setup_consumer

    redis_client = make_imports_redis_client()

    if __name__ == "__main__":
        logger.debug("running kafka consumer")

        consume = setup_consumer('general', "active_users")

        logger.debug("setting up zk")

        with keep_state("active_users") as keeper:

            logger.debug("starting iteration")

            for body, offset in consume():
                logger.debug("next event at offset %i", offset)

                user_id = get_pk(body["user_id"])

                logger.debug("event for user <%s, %i>", body["user_id"], user_id)
                
                # ...

// common.py

    from datetime import datetime
    from contextlib import contextmanager
    import time

    import bson

    from resources import make_zk_client, make_kafka_client

    kafka_client = make_kafka_client()
    zk_client = make_zk_client()

    @contextmanager
    def keep_state(lane):
        # ...

    # ...

    def setup_consumer(topic, consumer_group):
        topic = kafka_client.topics[topic]
        consumer = topic.get_simple_consumer(consumer_group=consumer_group)

        def consume_wrapper():
            while True:
                for message in consumer:
                    if message is not None:
                        body = bson.BSON(message.value).decode()
                        yield body, message.offset
                        consumer.commit_offsets()
                time.sleep(0.1)

        return consume_wrapper

**Comment by htch** [comment]
It turns out the read problem is caused by something else entirely, so far I don't see any other problems connected with `Partition 0 above max queued count`, thanks and sorry for taking your time.
