### ISSUE TITLE
What is a best practice of using balanced consumer ?

### ISSUE THREAD

**Issue by Kaydannik** [Parsely/pykafka#186]
Hello
I have a topic with 360-400 mio messages per day (~4000 msg/s) on Kafka 0.8.2 with 40 paritions.
So i am running 40 processes on 2 servers (20 per each)
Simple code is something like this:
pykafka v 1.0.3
```python
client = KafkaClient(hosts="server)
topic = client.topics['requests']
consumer = topic.get_balanced_consumer(consumer_group='Testing',auto_commit_enable=True,zookeeper_connect='amsmgmt002:2181,nas5:2181,amsdblx006:2181')
while True:
    message=consumer.consume()
    process_message(message.value)
```

As i noticed - i all the time have two problems:
duplicates of messages (same message receiving different processes in different time) - 3-5%
Lost messages (messages that will never be received by worker) also 3-5%

Can you please give best practice of using get_balanced_consumer ?
Is it normally handle situation with workers restart ? 
Is is ok to distribute workers across a few servers ? 
Should i run rebalance somehow by my self ? 

Thanks for your helping

**Comment by emmett9001** [comment]
Hi @Kaydannik, thanks for checking this in. The way you're setting up your use of `BalancedConsumer` in the sample code you provided is very similar to what we use in production at Parsely. When a `BalancedConsumer` dies, assuming it was properly connected to ZooKeeper, it notifies ZooKeeper that it's not around anymore. ZooKeeper reacts by notifying all other `BalancedConsumers` that it's time to rebalance. This answers two of your questions - you don't need to do anything special to handle consumer restarts, and you don't need to (and generally should not) directly call `rebalance`. Finally, distributing consumers across a few different machines is totally fine. You probably want all consumers to use the same `consumer_group` name, depending on your use case.

As for the duplicated and dropped messages: we may need more context to help diagnose those issues. At Parsely, we currently run 190 separate consumer processes consuming the same stream across multiple consumer groups, and we haven't seen dropped or duplicated messages being an issue. It's something we could stand to examine more closely, though. If you can provide any further context on how you're setting up your consumer workers, it might be helpful to figure this out.

**Comment by kbourgoin** [comment]
Closing as inactive. If we get more info on duplicated or dropped messages, we can re-open.
