### ISSUE TITLE
Unused init args

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#188]
I'm working on mapping to librdkafka config settings again, and noticed some metadata-related settings that didn't end up getting used. Just wondering if these are still reserved for future use, or if I should perhaps make a pullreq to drop them?

* in producer: `topic_refresh_interval_ms` [link](https://github.com/Parsely/pykafka/blob/0431280d6e2a68736e04fd91614f2dc028f087a6/pykafka/producer.py#L47)
* in both consumers: `refresh_leader_backoff_ms` [link](https://github.com/Parsely/pykafka/blob/0431280d6e2a68736e04fd91614f2dc028f087a6/pykafka/simpleconsumer.py#L59) [link](https://github.com/Parsely/pykafka/blob/0431280d6e2a68736e04fd91614f2dc028f087a6/pykafka/balancedconsumer.py#L61)

In the previous take on this, I used those settings to map to librdkafka metadata settings (see [here](https://github.com/Parsely/pykafka/blob/feature/archived_rdkafka_cffi/pykafka/rdkafka/config.py#L56-58)) but I think it makes more sense to just use librdkafka defaults for those - pykafka doesn't really call `cluster.update` on a timer anywhere, in the way of librdkafka's `topic.metadata.refresh.*` settings.

**Comment by emmett9001** [comment]
You're fine to remove these kwargs. They were supposed to be used but weren't, and I think we just forgot to take them out. They're things that we may add in a future version, but for now there's no reason to have them hanging around unused.
