### ISSUE TITLE
Is it a bug that consumer_timeout_ms doesn't work for BalancedConsumer?

### ISSUE THREAD

**Issue by fortime** [Parsely/pykafka#190]
I have set `consumer_timeout_ms` when I am getting a `BalancedConsumer` object.
```python
consumer = topic.get_balanced_consumer(
        'testgroup',
        consumer_timeout_ms=1000)
message = consumer.consume(block=True) # it blocks forever if there is no message
```

After some debugs, I found that `consumer_timeout_ms` works in the internal consumer. But 
it cann't exit the loop in the function `consume` of `BalancedConsumer`.
```python
def consume(self, block=True):
    """Get one message from the consumer

    :param block: Whether to block while waiting for a message
    :type block: bool
    """
    message = None
    while message is None:
        try:
            message = self._consumer.consume(block=block) 
        except ConsumerStoppedException:
            continue
        if not block:
            return message
    return message
```
After timeout, the internal consumer returns None, and the loop continues.

**Comment by emmett9001** [comment]
Hi @fortime, at first glance this does look like a bug that was introduced when we changed the polling logic in the `SimpleConsumer`. I'll investigate.

**Comment by emmett9001** [comment]
Thanks for finding this, @fortime. It's an oversight that we didn't catch this in the initial release, so it's good to have this fixed now. Current master (as of [this commit](https://github.com/Parsely/pykafka/commit/1834dc15675473834cad6e6b6d1a126fe5f70d6c)) fixes the issue. We'll also be putting out a bugfix release on PyPI before too long.

**Comment by fortime** [comment]
@emmett9001 So great! Thanks for your work. This project helps me a lot!
