### ISSUE TITLE
base.py doesn't agree with Topic

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#191]
`earliest_offset` still exists in `BaseTopic` even this this was renamed to `earliest_available_offset`.   The same goes for `latest_offset`.

We might also want to check on the rdkafka implementation, because `base.py` might not even be necessary anymore.

**Comment by yungchin** [comment]
That's right - currently nothing in the rdkafka branch requires `base` - we inherit from `SimpleConsumer` instead.

I've not really thought about how/what we'll do for inheriting from `Producer` yet. But actually, for me, `base` wouldn't really be missed either way - now that it's not an `abc` anymore, it doesn't enforce anything much (as this issue shows, too).

**Comment by emmett9001** [comment]
I'm in favor of deleting `base.py` altogether if we can get away with it, which it appears we can. I'll do the honors  if I don't hear any disagreement on this ticket in the next few days.

**Comment by emmett9001** [comment]
Removed base.py [here](https://github.com/Parsely/pykafka/commit/57cff746ce38f4d10d1f35591f4214a5084962e7).
