### ISSUE TITLE
CLI Consumer/Producer 

### ISSUE THREAD

**Issue by wrobstory** [Parsely/pykafka#197]
I would love to have a CLI Consumer/Producer interface that somewhat resembles [kafkacat](https://github.com/edenhill/kafkacat) for Consuming/Producing messages. 

Use case: I find myself constantly wanting to smoke-test a few messages through a topic, but needing to do so on a remote server. I don't have apt-get, don't want to fuss with building kafkacat manually, but do have Python available, so a simple CLI that can read from newline-delimited JSON, individual JSON blobs, or even a string argument would be awesome. 

If no one is in the middle of working on this, I would be happy to tinker on it this week and submit a PR for comments.

**Comment by emmett9001** [comment]
Hi @wrobstory, thanks for stepping up! We've got a budding `cli` directory [here](https://github.com/Parsely/pykafka/tree/master/pykafka/cli) - most of it currently deals with offset management. I think it would be really cool to have CLI interfaces to the consumer and producer. If you're up for it, we'd love a pull request!

**Comment by wrobstory** [comment]
Didn't get any time to work on this, so going to close the issue for now. Keep up the great work on the lib!
