### ISSUE TITLE
equivalent from-beginning

### ISSUE THREAD

**Issue by mbaudisch** [Parsely/pykafka#198]
I am sure this is a simple question but I have spent more time on it than my newbie status can stand. I am using the pykafka simpleconsumer and I want it to start picking up messages from the beginning as you would if you used "kafka-console-consumer.sh --zookeeper <etc>:2181 --topic test --from-beginning"  As it is, it starts consuming from the moment it connects to the kafka server and so loses earlier messages. How can I tell it to start at the beginning of the messages?

**Comment by emmett9001** [comment]
Hi @mbaudisch, thanks for checking this in. You can force the `SimpleConsumer` to begin consuming from the earliest available offset by using these settings:
```python
from pykafka.common import OffsetType
consumer = topic.get_simple_consumer(consumer_group="testgroup",
                                                                   auto_offset_reset=OffsetType.EARLIEST,
                                                                   reset_offset_on_start=True)
```
However, I'm a bit surprised that you're seeing the behavior you report. Under normal circumstances, a `SimpleConusmer` without a `consumer_group` should always start from the beginning of the topic, so it's unclear why you're getting different behavior. If you can provide the code you're using to set up your consumer, it could help get to the bottom of the issue.

Thanks!

**Comment by mbaudisch** [comment]
Thanks for the response! I will include the code in a little bit as I 
have a meeting starting very shortly!
Michael

**Comment by mbaudisch** [comment]
Hi Emmet,
Sorry it's taken me this long to respond. I am working through other 
parts of the code in a cyclical manner and I am back to this point 
again. Your suggesions did the trick!
Thanks a million
Michael

**Comment by mbaudisch** [comment]
One last question, I want to use the pykafka producer to send a message 
and then turn itself off untilnother message is ready. The simple 
consumer  has a timeout that works fine but there doesn't seem to be one 
for the producer. I will probably put it into some sort of timed loop 
but is there something that a normal person would use in this situation?
Thanks again
Michael

**Comment by emmett9001** [comment]
@mbaudisch The producer is pretty minimal by design, and it doesn't have a built-in way to specify the time between message sends. To implement this, you could put the `produce()` calls in a loop that amounts to something like this:

```python
while True:
    producer.produce(['test message'])
    time.sleep(timeout)
```

Thanks, and remember you can get any additional help you need with pykafka usage from the pykafka mailing list:
pykafka-user%40googlegroups.com

**Comment by mbaudisch** [comment]
Again, Thanks
I ended up putting it in a thread that I could terminate after a period 
of time.
I tried to join the pykafk-user group but google can't find it when I 
look. Also, when I mailed to that address, I received an error saying I 
probably wasn't on the mailing list, and hence could not mail to it,..  
strange,..

**Comment by emmett9001** [comment]
I just set the mailing list to be public. You can try posting to it again if you like. Thanks for pointing that out!

**Comment by mbaudisch** [comment]
Thanks Emmett, I think I just joined. I will post a similar message from 
the email account that seemingly sent the "like to join list" request as 
this is my home account and the other is my work account.
