### ISSUE TITLE
error reporting from reset_offsets

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#201]
[Here](https://github.com/Parsely/pykafka/pull/194#discussion_r33518462), we don't raise an exception if all attempts at `reset_offsets` fail. Thus, the only way for the client to know that it failed is to check the offsets stored in the consumer. We can't simply raise an exception, since in cases where `reset_offsets` is called in response to another error, we'd like it to be able to silently fail.

**Comment by emmett9001** [comment]
@yungchin [this](https://github.com/Parsely/pykafka/pull/203) is an exception-free way of ensuring that the client doesn't need to worry about whether their supplied offsets were saved to the consumer's internal counters. It's not super dangerous to just merge into master, but it's also not a very high priority. Let me know if it looks sane when you get a chance.

**Comment by yungchin** [comment]
@emmett9001 the approach definitely looks sane to me, yet I suspect for my uses I'd still rather see it raise an exception. Even in the case where `reset_offsets` is called in response to another error, usually that would be an `OffsetOutOfRangeError` - so there, if `reset_offsets` fails, that would mean 1) the offset I provided is invalid and 2) we haven't managed to set it to either earliest or latest offsets, so at that point we'd be at some entirely unexpected offset - better to fail loudly, I'd think.

**Comment by emmett9001** [comment]
I've updated `SimpleConsumer` to just raise an exception if there are any errors hanging around after the maximum retries have been hit.
