### ISSUE TITLE
pip install pykafka erro

### ISSUE THREAD

**Issue by knightseal** [Parsely/pykafka#202]
![image](https://cloud.githubusercontent.com/assets/2109057/8669020/6d8fa8b0-2a43-11e5-80ff-01ee6a391aa1.png)

**Comment by emmett9001** [comment]
Hi @knightseal, I see you're using python 2.6 to install pykafka. Pykafka is only compatible with python 2.7 at this time - we don't support 2.6.

**Comment by knightseal** [comment]
ok,thx
