### ISSUE TITLE
BalancedConsumer incorrectly handles loss of its ephemeral zookeeper nodes

### ISSUE THREAD

**Issue by fortime** [Parsely/pykafka#204]
Once the connection from one consumer to zookeeper losts, the consumer_id on zookeeper will be deleted. After reconnecting to zookeeper, rebalancing of this consumer will fail. The following line at func `_decide_partitions`:
```python
participants.index(self._consumer_id)`
```
will raise an exception.
Finally, all threads calling `_rebalance` will exit. But the worker thread still fetch messages from broker.

I think that it should check if the consumer is still on zookeeper when `_consumers_changed` is called. If not, calling `_add_self` registers this consumer again. In the meantime, if register failed, we should exit all other threads. BTW, can you provide a function to check if the consumer is running?

**Comment by fortime** [comment]
I think if the internal consumer of BalancedConsumer should stop if the connection to zookeeper lost. Other consumers may consume its partitions when it tries to reconnect zookeeper.

**Comment by emmett9001** [comment]
Hi again, @fortime! I've dug a bit into this issue and what you're saying makes sense. I'm still not totally clear on when exactly this situation arises - under what circumstances is the connection to zookeeper lost? Can you provide some example code that shows a case where the zookeeper connection can die in this way? I haven't been able to trigger the error you mention at `participants.index()`.

**Comment by emmett9001** [comment]
I've started some fixes on [this branch](https://github.com/Parsely/pykafka/tree/bugfix/zookeeper_failure), but I haven't yet fully thought through the consequences of the change, or if it's actually solving the right thing.

**Comment by fortime** [comment]
I think that it should take care if all watcher is alive. A simple solution is to stop the consumer and let the user restart a new one once a watcher is not alive.

**Comment by fortime** [comment]
Hi @emmett9001 , I have created a PR: #205 . A simple way to handle any failure which happens in worker thread.

**Comment by yungchin** [comment]
Here's an updated summary, also taking into account some details implied in pullreq #215:

After a zookeeper reconnect, `BalancedConsumer` should handle the potential loss of its ephemeral nodes. That means that

  1. it cannot assume that `self._consumer_id` is still a listed participant on zookeeper (and we might be able to salvage some logic from #206 to fix that)
  2. it must also consider the case where `self._partitions` is no longer in sync with what's advertised on zookeeper (the fixes that were part of #215 suggest that we can assume they're either all in sync or that all of them are missing on zookeeper - and this is probably correct), whereas `BalancedConsumer._rebalance()` on current master always assumes `self._partitions` is the one source of truth

I've updated the title of this issue to cover both these aspects.

**Comment by emmett9001** [comment]
This issue is tied to PR #308
