### ISSUE TITLE
Kafka balanced consumer reads each character as separate message

### ISSUE THREAD

**Issue by ziky90** [Parsely/pykafka#207]
With respect to the #196 I have updated kafka to version 0.8.2.

Now it seems that I am experiencing  another problem. My pykafka consumer reads the data from kafka character by character (every character as separate message) instead as a one message.
In order to be able to read the whole message I need to wrap it to double quotes eg. `{"body":{"content":"this is a simple text","id":"www.text.com"}}`

For sending the data to kafka I use just command `kafka-console-producer.sh --broker-list localhost:9092 --topic test`

I would like to ask if someone has already experienced this problem? If so, then what I am possibly doing wrong?

**EDIT:**
Now I have realised that this error only happens when I am trying to send jsons. Sending normal text messages eg. `hello world` works well.

And I have also experienced the same problem when I am using the `simple_consumer` instead of the `balanced_consumer`

**Comment by emmett9001** [comment]
Hi @ziky90. I've tested this with a consumer script that looks like this:

```python
client = KafkaClient(hosts="127.0.0.1:9092")
    topic = client.topics['testtopic']
    consumer = topic.get_simple_consumer()
    while True:
        message = consumer.consume()
        if message:
            print message.value
```
I produce messages to kafka using this command:
```
/opt/kafka-0.8.2.1/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic testtopic
```
At the producer's command line, I can enter this sequence:
```
{"field": "my content"}<ENTER>
```
and I see it consumed by my consumer script as a single message.

Does your test case differ in some way? I imagine the problem you're seeing is an issue with how you're producing the messages, not with the pykafka consumer.

**Comment by ziky90** [comment]
Hi @emmett9001 

Yes this is exactly the way I am testing it. Except instead of `/opt/kafka-0.8.2.1/bin/kafka-console-producer.sh` I am using `/usr/local/bin/kafka-console-producer.sh`.

Inspecting the folder `/usr/local/bin` I can see kafka version 0.8.2.1

**Comment by ziky90** [comment]
Found an internal application bug. I'm sorry for bothering by this.
