### ISSUE TITLE
Stopping BalancedConsumer ends in infinite loop

### ISSUE THREAD

**Issue by tiriplicamihai** [Parsely/pykafka#210]
I noticed today a problem with BalancedConsumer. The steps to reproduce this behavior are:

1. Call consume method (blocking or nonblocking)
2. On another thread get the instance and call `stop` method (For my scenario it was in a signal handler)
3. The consume will never end

I think this happens because of this code:
https://github.com/Parsely/pykafka/blob/1.0.3/pykafka/simpleconsumer.py#L297-L310

`SimpleConsumer` always raises `ConsumerStoppedException` and `BalancedConsumer` always ignores it (`continue` skips the blocking part).

Is this the expected behavior? If not, maybe before calling `continue`, self._running should be check. If you thing it's ok I'd be happy to create a PR for this fix (or think about another one).

Thank you!

**Comment by emmett9001** [comment]
Thanks @tiriplicamihai. My original intent with the `continue` statement was to allow `consume()` to continue without returning during a call to `_rebalance()`. That can stay, but I agree that a check on `self._running` before the `continue` in `BalancedConsumer` should fix this issue. If you're willing to open a pull request for this, please do!

**Comment by tiriplicamihai** [comment]
@emmett9001 Thank you for your response! I will open a PR tomorrow.
