### ISSUE TITLE
Proposal for changes in manual offset management

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#216]
While working on #213 I ran into a confusing quirk, where `held_offsets` may return an offset of -1 (ie we're at the start of the partition), which seems fine until you do the following: 1) store the offsets from `held_offsets` in your application's external offset store, 2) feed them back from there into `reset_offsets`. The problem is that Kafka defines -1 to mean LATEST (it would not have been a problem if LATEST was -2 instead, and EARLIEST was -1). So you may get:

```
In [18]: cons = top.get_simple_consumer(reset_offset_on_start=True, auto_offset_
reset=pykafka.common.OffsetType.EARLIEST)                                       

In [19]: held = cons.held_offsets

In [20]: held
Out[20]: {0: -1, 1: -1, 2: -1}

In [21]: cons.reset_offsets([(cons.partitions[pid], offset) for pid, offset in h
eld.items()])

In [22]: cons.held_offsets
Out[22]: {0: -1, 1: 99, 2: -1}
```

We can avoid the magic numbers altogether by doing something like

 * creating a property `next_offsets` which would just return `held_offsets` + 1, so to speak
 * (plus slap a deprecation warning on `held_offsets`)
 * creating a kwarg `next_offsets` for `reset_offsets()`, which accepts the same as its `partition_offsets` kwarg but expects all values + 1
 * (plus slap a deprecation warning on the `partition_offsets` kwarg)

If that makes sense, I'm happy to write the pullreq.

**Comment by kbourgoin** [comment]
I'm generally +1 to the idea, but need to think on it a bit more. I can see the issue with the current setup, but I'm confused why in the example provided only partition `1` has its offset changed whereas the other two are unchanged.

**Comment by yungchin** [comment]
Ah, yes sorry that's a bit confusing: only that partition held any messages. I quickly created the test-topic using the KafkaInstance producer, which dumps all its messages on a single partition if you only call `produce_messages` once.

**Comment by yungchin** [comment]
If we're headed for a major version bump soon, would that be a good time to move on this one? Would save us all the deprecation warnings :)

**Comment by yungchin** [comment]
(Just ran into an issue with this again.)

As an alternative fix, that wouldn't change as much of the interface, how about if we only change the implementation of `held_offsets` so that it returns `-2` (ie `OffsetType.EARLIEST) when it holds `-1` internally? So

```python
    @property
    def held_offsets(self):
        """Return a map from partition id to held offset for each partition"""
        return {p.partition.id: (OffsetType.EARLIEST if p.last_offset_consumed == -1 
                                 else p.last_offset_consumed)
                for p in itervalues(self._partitions_by_id)}
```

If that makes sense, I'd propose this for 2.0.0.

**Comment by emmett9001** [comment]
I'm kind of surprised it's taken me this long to get to this, but things fall through the cracks I guess. This is a weird side effect of making `held_offsets` public, and after thinking about it I believe the small proposed change to `held_offsets`' implementation is the best way to handle this. It does make sense that calling `reset_offsets` using `held_offsets` as input should be an idempotent operation, and I don't see any harm in fudging the values a bit to that end. I'll open a PR.
