### ISSUE TITLE
make 'tabulate' an optional dep?

### ISSUE THREAD

**Issue by benauthor** [Parsely/pykafka#220]
Dependency 'tabulate' is only used for the cli utility; what do you think about changing that from an `install_requires` to an `extras_require`? One less dependency for most users?

**Comment by emmett9001** [comment]
Fixed https://github.com/Parsely/pykafka/commit/55d556546ca5827075298207eb14331dea2ec34f

**Comment by emmett9001** [comment]
We'd like all of the provided functionality to work with a simple `pip install pykafka`, including the CLI. Making it optional means that a lot of folks will be confused when they can't use the CLI tools after installing pykafka..

**Comment by benauthor** [comment]
fair enough
