### ISSUE TITLE
Consumer hanging after a broker gets down

### ISSUE THREAD

**Issue by AgustinCB** [Parsely/pykafka#223]
Trying the library, I set the following situation:

Five brokers in the kafka cluster, one producer and two consumers over one topic. 

If I stop one of the brokers, the producer get some warning messages and after some seconds, restarts its normal behavior with no problem. The consumer, on the other side, fails with a Socket Disconnect exception on a different thread, leaving the process alive, but not doing anything.

Using what I saw on the producer code, I modified the consumer to use a similar approach:

https://github.com/appsoma/pykafka/pull/2

However, I'm not sure if there were a reason to the behavior of the consumer, if my code breaks something else or if it doesn't fit the code philosophy that you're following.

Excuse my poor English, please.

**Comment by fortime** [comment]
I have encoutered this problem too. I think it is a bug of broker connection. When a Socket Disconnect exception happens, it will disconnect the broker connection, and it will never re-connect. I think it should check the connection to broker is still alive. If not, re-connect it.

**Comment by emmett9001** [comment]
Current master now immediately raises an exception if a broker goes down, which at least allows the client code to catch the exception and reinstantiate the consumer. A more complete fix will involve smartly retrying fetch requests after updating broker metadata. This effort will be tracked in this ticket.
