### ISSUE TITLE
SocketDisconnectedError on commit_offsets()

### ISSUE THREAD

**Issue by youngpm** [Parsely/pykafka#224]
Related to #209, the code snippet below gives me a `SocketDisconnectedError` using pykafka 1.1.0 (the version in pypi) and Kafka 0.8.2.0 (I just spun up Kafka locally as described in their quickstart).

I start the consumer, put a message on the queue, and wait 30 minutes before committing the offset.

```python
#!/usr/bin/env python
import time

from pykafka import KafkaClient
from pykafka.common import OffsetType

if __name__ == "__main__":

    time_to_sleep = 0.5*60*60

    # Get a consumer.
    client = KafkaClient(hosts='localhost:9092')
    input_topic = client.topics['test']
    consumer = input_topic.get_simple_consumer(consumer_group='testgroup',
                                               auto_offset_reset=OffsetType.EARLIEST,
                                               auto_commit_enable=False)

    # List messages on topic.
    for message in consumer:
        print('{} {}'.format(message.value, message.offset))
        time.sleep(time_to_sleep)
        print('committing...')
        consumer.commit_offsets()
        print('committed!')
```

The traceback looks like:

```
In [2]: run consumer_bug.py
message16 15
committing...
---------------------------------------------------------------------------
SocketDisconnectedError                   Traceback (most recent call last)
/mnt/panasas/pyoung/pykafka_bug/consumer_bug.py in <module>()
     22         time.sleep(time_to_sleep)
     23         print('committing...')
---> 24         consumer.commit_offsets()
     25         print('committed!')
     26

/mnt/panasas/pyoung/pykafka_bug/venv/lib/python2.7/site-packages/pykafka/simpleconsumer.pyc in commit_offsets(self)
    347
    348             response = self._offset_manager.commit_consumer_group_offsets(
--> 349                 self._consumer_group, 1, 'pykafka', reqs)
    350             parts_by_error = handle_partition_responses(
    351                 self._default_error_handlers,

/mnt/panasas/pyoung/pykafka_bug/venv/lib/python2.7/site-packages/pykafka/broker.pyc in commit_consumer_group_offsets(self, consumer_group, consumer_group_generation_id, consumer_id, preqs)
    306                                   consumer_id,
    307                                   partition_requests=preqs)
--> 308         return self._offsets_channel_req_handler.request(req).get(OffsetCommitResponse)
    309
    310     def fetch_consumer_group_offsets(self, consumer_group, preqs):
/mnt/panasas/pyoung/pykafka_bug/venv/lib/python2.7/site-packages/pykafka/handlers.pyc in get(self, response_cls, timeout)
     53         self._ready.wait(timeout)
     54         if self.error:
---> 55             raise self.error
     56         if response_cls:
     57             return response_cls(self.response)
```

Any ideas on what is going on and possible work arounds?  Thanks!

**Comment by emmett9001** [comment]
It looks like the connection on the offsets channel is timing out. You should be able to set [`_offsets_channel_socket_timeout_ms`](https://github.com/Parsely/pykafka/blob/master/pykafka/client.py#L42) to a number greater than 30 minutes to solve this error.

**Comment by youngpm** [comment]
I'll give it a shot.  

I reran it with a sleep of 60 seconds (without changing the socket timeout defaults in the client) and it works, surprised that it did given what the defaults are set to! Are the timeouts fuzzy? It even worked with a sleep of 10 minutes without messing with the defaults...

**Comment by emmett9001** [comment]
That's definitely strange. It seems pretty clear that this is the result of an idle offsets channel socket, but I'm not sure how [this](https://github.com/Parsely/pykafka/blob/master/pykafka/connection.py#L79) could really go wrong.

**Comment by youngpm** [comment]
I ran a few more tests, 30 minutes sometimes works, and sometimes gives me the disconnect.  I wonder if the tcp socket that is handling offset management needs a heartbeat to keep active (I guess auto commit offsets would take care of this, running the same test with it on right now)?

**Comment by youngpm** [comment]
@emmett9001 I ran the same test with `auto_commit_enable=True` and huge sleep intervals between receiving messages and calling `commit_offsets`, no problems.  I guess that's no surprise.

**Comment by emmett9001** [comment]
Yeah, that's what I'd expect. I'm not surprised that the socket dies after a period of inactivity, but I'm confused that the timeout does seem to be fuzzy.

**Comment by emmett9001** [comment]
@youngpm Some of the code potentially affecting this issue has changed significantly since we last connected about it. I wonder if you can re-run your test case on current master and see how it affects the results you're seeing. Thanks!

**Comment by youngpm** [comment]
I'll get on it!

**Comment by youngpm** [comment]
Didn't see it crop up agian, so I think its probably good!
