### ISSUE TITLE
Error importing KafkaClient

### ISSUE THREAD

**Issue by dmuralik** [Parsely/pykafka#228]
I believe I have followed the instructions clearly while installing pykafka on my mac but when I run my code it throws an error when trying to import KafkaClient: ImportError: No module named 'broker'

I am using condas for my env and I did not run into any errors while installing.

Am I missing something?

**Comment by dmuralik** [comment]
Looks like the issue was that I had python3 running and nowhere obvious in the pykafka doc does it say anything about the compatible versions. I tried it on 2.7.9 and this error seems to have gone away.

**Comment by emmett9001** [comment]
Added a note about python version [here](https://github.com/Parsely/pykafka/commit/e477f345fa3699082c5ca5f2ebb2c0facf69fc27)

**Comment by dmuralik** [comment]
Sweet, thanks!
