### ISSUE TITLE
Return futures from Producer.produce()

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#238]
As per earlier discussion [here][0], I'm spinning this out into a separate issue. 
[0]: https://github.com/Parsely/pykafka/pull/234#discussion_r37731037

The proposal here would be that both `Producer.produce` and `RdKafkaProducer.produce` would return a future, enabling users to check the delivery status of produced messages to the kafka cluster.

I originally drafted a rough idea that used a `pykafka.handlers.ResponseFuture`, but I would now really propose that we return a (backported) `concurrent.futures.Future` instead. The former has never really been part of our public interface, and it wouldn't make sense to start leaking it now, if there's a more standard and more featureful alternative available.

The returned future would evaluate to `None` if delivery was successful (or optionally, it could report back both the partition_id and offset of the produced message, but I think we should save that for another day). If delivery wasn't successful, the future would re-raise the exception that occurred on the worker thread -- be it `InvalidMessageSize` or `RequestTimedOut` or any other that currently only appear in logging output.

@emmett9001 you're much more familiar with `Producer` internals, but I've been working on this anyway on the rdkafka side, so would also be happy to pick this up if you like.

**Comment by ltucker** [comment]
That might also allow you to replace this busy-waiting-with-sleeps that synchronous produce uses with a more fine grained concurrent.futures.wait(...)

https://github.com/Parsely/pykafka/blob/master/pykafka/producer.py#L352

**Comment by emmett9001** [comment]
Related to #240
