### ISSUE TITLE
Synchronous batch produce() no longer possible in 2.0?

### ISSUE THREAD

**Issue by ltucker** [Parsely/pykafka#240]
This doesn't apply to a released version, just the current trunk that is slated for 2.0.  

As far as I can tell, there is currently not a reasonable way to express a synchronous batch produce(...) at the discretion of the application in the Producer interface.

Whenever sync=True, you get one-by-one synchronous publishing.  It waits with arbitrary sleeps up to 300ms for empty queues after every single message ( produce(...) only accepts one message at a time. )

If sync=False, well then ... it's not synchronous and you aren't guaranteed that a flush has taken place no matter how you adjust batching parameters / timing parameters.

There is no public method to produce a batch of messages and wait for them to all be flushed.
There is no public method to force a synchronous flush of all pending messages.

This might be planned already, not sure.  Seems like this might also be helped by https://github.com/Parsely/pykafka/issues/238

**Comment by yungchin** [comment]
Yes that's right - there was a discussion about this on #177 (and I've no idea how to reconstruct it, with all of github's magic about commits superseding older comments etc etc - maybe we ought to feed all github updates into the mailing list so we can at least read them back there) and in the end this got dropped, basically because it was unclear how to tell, in case of errors, which messages in the batch had been successfully enqueued and which ones hadn't been.

I see what you mean about how it fits in with #238. With that in place, you could probably make a synchronous `produce_batch()` which would just be a bunch of async `produce()` calls, plus a bulk `wait` for all of the futures.

**Comment by ltucker** [comment]
yes, exactly -- ah, yes, sorry I missed the other discussion -- feel free to close or merge into others as you see fit.

**Comment by yungchin** [comment]
Well maybe it's good to have this here as an independent issue. I reckon there's room for discussion to reintroduce it as a method `Producer.produce_batch()` or a name like that.

The thing is, I've never had a real use for batch-produce calls myself, which makes it harder to come up with the right semantics, but I guess you'll have some use and ideas for this?

**Comment by ltucker** [comment]
Looks like would need some funkier signature to incorporate the key based partitioning parameter in any case (tuples of (key, message) or something)  For our cases, it would probably be sufficient / more flexible to have those futures in hand, but I'll think about it and see if I can propose something generally nice.

In some cases, for example, we don't want to commit the offset of a block of consumed messages until we can guarantee the results of processing the messages have been published (to some other topic(s)).

Today we use synchronous publication for that guarantee (with batching necessary for performance).

**Comment by yungchin** [comment]
Right right - thanks for describing the use case, that makes a lot of sense. Yeah, so actually, having the futures would really work well there - you could even be sending your results off to multiple different topics, and still tie all the futures together in one `wait()`.

Ok, let's leave this here, see if we can get #238 going quickly, and then revisit if we still need this?

**Comment by ltucker** [comment]
Sounds good thanks!

**Comment by emmett9001** [comment]
@ltucker I just merged in the futures branch to the producer. Does the current interface on master satisfy your use case?

**Comment by emmett9001** [comment]
We've decided to remove the futures interface for the time being, since it uses far more resources than is appropriate. @yungchin is working on a better implementation.

**Comment by emmett9001** [comment]
@ltucker If you'd like, please test out #344 and let us know how it satisfies this use case. It's just about ready to go into master.
