### ISSUE TITLE
Provide a lag monitor program.

### ISSUE THREAD

**Issue by rduplain** [Parsely/pykafka#244]
[I'm only reporting this based on a conversation that I was in. Others on the team may have more. We discussed adding a tool to pykafka which would monitor the offsets that consumers are currently consuming.]

**Comment by ottomata** [comment]
I assume yall already know https://github.com/linkedin/Burrow ?

**Comment by emmett9001** [comment]
I haven't used [this](https://github.com/Parsely/pykafka/blob/master/pykafka/cli/kafka_tools.py#L114) in a while, but it's around and relatively up-to-date. It seems to fit the bill?

**Comment by emmett9001** [comment]
This exists in kafka-tools
