### ISSUE TITLE
BalancedConsumerIntegrationTests unpredictably hanging

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#260]
I've been running into this on various branches, even with code changes that didn't touch the code path this test tests, and it would always disappear when restarting the tests. We originally assumed this was a test cluster quirk, somehow triggered by our deleting all topics between different TestCases. But we've since addressed most of its quirks (using UUIDs for topic names etc etc), and yet this thing keeps popping up - probably deserves its own issue number by now.

Here it is as it manifested itself today, on travis-ci:
```
tests/pykafka/test_balancedconsumer.py::BalancedConsumerIntegrationTests::test_consume_latest 

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

**Comment by emmett9001** [comment]
Possibly related to #189

**Comment by emmett9001** [comment]
I've seen this test hanging before, but I can't reliably replicate it with

    tox -- -s tests/pykafka/test_balancedconsumer.py::BalancedConsumerIntegrationTests::test_consume_latest
