### ISSUE TITLE
Occasional test suite failure in test_partition: test_can_get_latest_offset

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#263]
We occasionally get a failure here: https://github.com/Parsely/pykafka/blob/298ddc198b0d015621ae6f8e133dc7158f70fdfe/tests/pykafka/test_partition.py#L32

I suspect this simply happens in the (rare) event that the producer's random partitioner has managed to leave a given partition out n times, so that it is still empty when this test runs - that is, it's probably just a problem with how the test is defined. Filing this just in case I'm missing something, and because I don't immediately see how to improve the test.

**Comment by emmett9001** [comment]
I believe I've verified this hypothesis by changing the implementation of `random_partitioner` to `return partitions[0]` and observing the error. I've also made a simple fix [here](https://github.com/Parsely/pykafka/pull/267) that simplifies the test a bit.
