### ISSUE TITLE
SimpleConsumer.stop() ought to commit offsets if appropriate

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#270]
I'm spinning this out of #206 which we won't be merging.

Currently, if we call `stop()` on a consumer, the auto-commit thread will abort, possibly without committing the latest partition offsets. Instead, `stop()` should make sure the latest offsets are committed, provided that 1) `self.auto_commit_enable == True` and 2) we didn't call `stop()` as part of some exception handling (this second rule is up for discussion, I suppose).

We might be able to cherry-pick some commits out of #206 towards this.

**Comment by emmett9001** [comment]
Thanks @yungchin, this is really helpful. There are a lot of worthwhile ideas in those PRs, but they're basically unmergeable without splitting them out like this.

**Comment by emmett9001** [comment]
There's a good chance this will be fixed as part of #235, since the thread create/destroy logic is probably going to change significantly to enable this and other enhancements.

**Comment by yungchin** [comment]
Re point 2) - I'm no longer really sure why that rule would be needed at all. Even if this was part of some error on the worker thread, the offsets you'd commit would still be the latest that the user did actually consume.
