### ISSUE TITLE
Should BalancedConsumer.consume() block/fail during rebalancing?

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#274]
This was raised by @fortime in comments on #215: "The consumer will consume message during the time of rebalancing. It is an expected behavior, but it may cause messages in 30 seconds consumed by multiple consumers."

**Comment by emmett9001** [comment]
Folding this into #273 since they're really about the same thing: when the zookeeper partition registry is changing or inaccessible, what should the consumer do about it?
