### ISSUE TITLE
BalancedConsumer.stop() should remove its ephemeral nodes if it doesn't own the zookeeper handle

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#276]
This was reported by @fortime in a comment on #227.

**Comment by yungchin** [comment]
Oops, this is a special sort of duplicate of #272.

**Comment by yungchin** [comment]
As noted by @xqliang in https://github.com/Parsely/pykafka/commit/770c4fc114dcb4ba0752240c81a56ae717ae50ab#commitcomment-13739557 this is still outstanding.

**Comment by emmett9001** [comment]
To clarify - the consumer should *only* remove its ephemeral nodes rather than stop the zookeeper instance if it does not own the zookeeper instance. This should happen only during `stop()`.
