### ISSUE TITLE
Potential for out-of-range error to overwrite a user's reset_offsets instruction?

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#287]
( @emmett9001 I got thinking about this while reviewing #265, but since I shouldn't be heaping multiple issues into the same thread as I've done in the past, here's a fresh ticket :))

I believe that in the usage model that @zsimpson describes in #253 -- where you'd start a new consumer, then immediately call `reset_offsets()` on it -- there's a special case where you might end up with the default `auto_offset_reset` value, rather than whatever you just passed to `reset_offsets()`. Here's the sequence of events (or the theory, anyway):

  * user starts a new consumer
  * in `start()`, `fetch_offsets()` runs, which happens to obtain a bunch of stale offsets (this is the special case -- maybe it's because the topic's just been compacted; whatever)
  * the fetch-worker starts, enters `fetch()`, grabs a bunch of fetch locks
  * user calls `reset_offsets()`
  * `reset_offsets()` blocks trying to get a lock that the fetch-worker holds
  * the fetch-worker gets a response with `OffsetOutOfRangeError` on all partitions (not necessarily all, but that's the easiest case to reason about)
  * the fetch-worker then [releases locks on those partitions][0]
  * this means the user's `reset_offsets()` call can now grab those locks, and do its work
  * the fetch-worker waits for that to finish, then [continues with its own resets][1]
  * end result: the user-provided offsets got clobbered

I suspect it's really hard to get a test case written that demonstrates this reliably, but if we're happy to merge a fix without that test case, I'd think not releasing the locks before resetting, and instead using an `RLock` should do the trick. Happy to take a shot at that.

[0]: https://github.com/Parsely/pykafka/blob/770c4fc114dcb4ba0752240c81a56ae717ae50ab/pykafka/simpleconsumer.py#L619-L624
[1]: https://github.com/Parsely/pykafka/blob/770c4fc114dcb4ba0752240c81a56ae717ae50ab/pykafka/simpleconsumer.py#L627-L630

**Comment by yungchin** [comment]
On reconsidering this, I don't think it's likely to be a common scenario. I do believe fixing it would be worthwhile, because it would also simplify that code a little bit, but I'll drop it to the very bottom of the list on waffle.io

**Comment by emmett9001** [comment]
I agree this isn't high-priority, since the preferred way to reset offsets after starting a consumer is to simply set `reset_offsets_on_start=True` in the consumer constructor.
