### ISSUE TITLE
Notification / callback on rebalance?

### ISSUE THREAD

**Issue by ryan-stateless** [Parsely/pykafka#288]
I have N consumers of M partitions in a Kafka topic. Kafka messages are updates to an in-memory data structure that is initialized from (and periodically written back out to) a 3rd party DB.

I'm trying to figure out a robust solution to the following problem:
Consumer  'A' owns some subset of the partitions. Consumer 'B' comes online, initializes, and takes ownership of one (or more) partitions from 'A' and begins processing messages. Consumer 'B' then goes down and the Consumer 'A' resumes consuming the messages.

From consumer A's perspective, there was a gap in updates for a while, but eventually they resumed. In reality, A has failed to apply a subset of the updates to it's data structure because they were being handled by 'B'

If there were a mechanism to notify Consumer 'A' that it had lost ownership of the partition, it could do the appropriate flushing/retiring of data and likewise resume cleanly when it regained ownership.

Does such a mechanism exist? Is there any reason that such a mechanism wouldn't work cleanly in practice? It seems like I could pass a function pointer to the BalancedConsumer at init() and call that function at the end of _rebalance(). Thoughts? Pitfalls? Worthwhile PR?

**Comment by emmett9001** [comment]
At first blush, a callback after `_rebalance` sounds like it wouldn't be too problematic to implement. As long as we kept it very generic and didn't try to give the callback too much information about any state, I think it would be fine. Sounds like a worthwhile pull request.

I'm wondering about your use case. Does each consumer have its own separate in-memory data structure it's responsible for modifying, or are all of the consumers pushing updates to a single structure? If you want all updates to go to the same structure, it seems like you could use a single consumer or a group of balanced consumers without any issue. If you're modifying multiple structures (one per consumer), I think separate consumer groups would be more suited to your use case.

It's extremely likely I'm misunderstanding something about your use case - please enlighten me!

**Comment by ryan-stateless** [comment]
In my use case, you might as well think of the topic as "user activity updates". The number of users is much greater than the number of partitions. User updates are hashed into partitions by unique user id. Each consumer in the group is responsible for aggregating user updates into an up-to-date user data structure per user. The data structure is large and the update heuristic moderately complex, precluding a database read before each update or an atomic in-database stored procedure style update.

Because of the hashed partitions, any given consumer knows that it is the sole updater for any given user whose messages it consumes. The consumer just needs a mechanism to know when to flush/finalize data for a given user if a rebalance occurs and it is no longer the consumer of the partition containing a given user. So... a rebalance callback seems like the natural way to support the use case - though if you'd come at it from a different angle, I would be interested to hear your thoughts.

**Comment by emmett9001** [comment]
I see, that makes sense. Our use case at Parsely doesn't involve hashing messages to particular partitions, so we haven't fully explored that space yet. I think a rebalance callback is a good way to address this - feel free to open a pull request.

**Comment by yungchin** [comment]
Just a quick note: it looks like the JVM consumer is going to gain something similar, it might be interesting to consider their design for this http://people.apache.org/~nehanarkhede/kafka-0.9-consumer-javadoc/doc/

**Comment by emmett9001** [comment]
@ryan-stateless Take a look at #324 if you get a chance, and let us know if it handles your use case satisfactorily.

**Comment by ryan-stateless** [comment]
The first commit - https://github.com/Parsely/pykafka/commit/8bb4f3dbe8381d83d5fc36474f3334e50c0e9503 - is almost line for line identical to what I had written up in my development environment and suits my needs perfectly.

My first pass returned the new partition ids in the callback, but subsequently I decided to just inspect consumer.partitions to determine the new set of held partitions. However in the paradigm of giving the callback both the before and after partition dicts, this probably makes good sense.

Looks great!
