### ISSUE TITLE
minimum consumer lag is 1, not 0

### ISSUE THREAD

**Issue by dribler** [Parsely/pykafka#289]
I noticed that, even if consumer consumed all messages, lag value is 1. I expected that after consuming ALL message, lag value should be 0.

I thought this is Kafka issue, but i've made experiment and below what i got.

So i have 3 brokers and small topic:

```
Topic:test     PartitionCount:6        ReplicationFactor:3     Configs:
        Topic: test    Partition: 0    Leader: 0       Replicas: 0,2,1 Isr: 0,2,1
        Topic: test    Partition: 1    Leader: 1       Replicas: 1,0,2 Isr: 1,0,2
        Topic: test    Partition: 2    Leader: 2       Replicas: 2,1,0 Isr: 2,1,0
        Topic: test    Partition: 3    Leader: 0       Replicas: 0,1,2 Isr: 0,1,2
        Topic: test    Partition: 4    Leader: 1       Replicas: 1,2,0 Isr: 1,2,0
        Topic: test    Partition: 5    Leader: 2       Replicas: 2,0,1 Isr: 2,0,1
```

I produced 4 messages and consumed with kafka-console-consumer:

/opt/kafka/bin/kafka-consumer-offset-checker.sh --topic test --group test --zookeeper localhost:2181
```
Group           Topic                          Pid Offset          logSize         Lag             Owner
test            test                          0   0               0               0               none
test            test                          1   0               0               0               none
test            test                          2   4               4               0               none
test            test                          3   0               0               0               none
test            test                          4   0               0               0               none
test            test                          5   0               0               0               none
```

Lag is 0. I expected that.

And now 4 messages consumed with pykafka 2.0.0

 /opt/kafka/bin/kafka-consumer-offset-checker.sh --topic test --group test2 --zookeeper localhost:2181
```
Group           Topic                          Pid Offset          logSize         Lag             Owner
test           test3                          0   -1              0               unknown         none
test           test3                          1   -1              0               unknown         none
test           test3                          2   3               4               1               none
test           test3                          3   -1              0               unknown         none
test           test3                          4   -1              0               unknown         none
test           test3                          5   -1              0               unknown         none
```
Lag is 1. I had same on pykafka 1.1.0

We have this at production and i able to reproduce it locally everytime. Is it pykafka issue? Maybe i do something wrong?
This actually is not a big problem - there are no missed messages, this just confused a bit.

**Comment by emmett9001** [comment]
Hi @dribler, thanks for checking this in. It would be helpful to see the code you're using to test, since my guess is that the consumer is not committing the offset of the last message it consumes. Are you using the `auto_commit_enable` or `auto_commit_interval_ms` kwargs on the consumer instance? It's also possible that this is a one-off error on the consumer's offset counting, but it's difficult to rule out either without seeing the code you're using to test.

**Comment by dribler** [comment]
@emmett9001 thanks for looking into this. 
Here is my test code:

```
from pykafka import KafkaClient

client = KafkaClient(hosts="localhost:9092,localhost:9093,localhost:9094")
consumer = client.topics['test'].get_simple_consumer(consumer_group='test')
while True:
    message = consumer.consume()
    print(message.value)
    consumer.commit_offsets()
```

To test i'm using kafka-console-producer. Like this:
/opt/kafka/bin/kafka-console-producer.sh --topic test --broker-list localhost:9092,localhost:9093,localhost:9094

All messages are printed. If i restart script i don't get already consumed messages. So it behaves like it committed all offsets.

**Comment by benauthor** [comment]
I've also observed this off-by-one error. It causes a problem in practice in which `kafka-tools reset_offsets my.topic my.group latest` to set invalid offsets, so consumer group resets itself with configured auto-reset (which is back to beginning by default -- opposite of desired effect)

More details:

Empty topic of four partitions
```
$ kafka-tools print_offsets pykafka.empty earliest
 Partition    Offset
-----------  --------
     0          0
     1          0
     2          0
     3          0

$ kafka-tools print_consumer_lag pykafka.empty foo
 Partition    Lag    Latest Offset    Current Offset
-----------  -----  ---------------  ----------------
     0         1           0                -1
     1         1           0                -1
     2         1           0                -1
     3         1           0                -1

 Total lag: 4 messages.
```

Produce ten messages and consumed them all
```
> [m.offset for m in messages]
Out[49]: [0, 0, 0, 0, 1, 1, 1, 2, 2, 3]

$ kafka-tools print_consumer_lag pykafka.offbyone foo
 Partition    Lag    Latest Offset    Current Offset
-----------  -----  ---------------  ----------------
     0         1           4                3
     1         1           2                1
     2         1           3                2
     3         1           1                0

 Total lag: 4 messages.

```

Pykafka is reporting from the offset api as delivered:
```
In [55]: top.fetch_offset_limits(-1)
Out[55]:
{0: OffsetPartitionResponse(offset=[4], err=0),
 1: OffsetPartitionResponse(offset=[2], err=0),
 2: OffsetPartitionResponse(offset=[3], err=0),
 3: OffsetPartitionResponse(offset=[1], err=0)}

In [56]: top.fetch_offset_limits(-2)
Out[56]:
{0: OffsetPartitionResponse(offset=[0], err=0),
 1: OffsetPartitionResponse(offset=[0], err=0),
 2: OffsetPartitionResponse(offset=[0], err=0),
 3: OffsetPartitionResponse(offset=[0], err=0)}
```

Is this a case of interpreting indices reported as "next available offset" as if they meant "last consumed offset"?
