### ISSUE TITLE
Wrong name for partition_key attribute in documentation

### ISSUE THREAD

**Issue by marianov** [Parsely/pykafka#290]
The documentation only makes reference of an optional "key" attribute in messages, but I think the attribute is called partition_key
The following code prints message keys correctly (while msg.key give an `AttributeError` all the times)

```
while True:
    msg = balanced_consumer.consume()
    try :
       print msg.partition_key
       print msg.value
    except AttributeError:
       print msg.value
```

Maybe it should be explained in pykafka/pykafka/protocol.py https://github.com/Parsely/pykafka/blob/c2e9c5e9ba5fce10405dfb3c5d62636b1d7415c6/pykafka/protocol.py#L139

Thanks

**Comment by emmett9001** [comment]
Thanks for checking this in, @marianov. Are you referring to the `Key` attribute in the [protocol documentation](https://github.com/Parsely/pykafka/blob/c2e9c5e9ba5fce10405dfb3c5d62636b1d7415c6/pykafka/protocol.py#L132)? The docs for `Message.__init__` do specify `partition_key` - maybe I'll just add a note that indicates that `partition_key` in `__init__` corresponds to `Key` in the protocol documentation.

**Comment by marianov** [comment]
I mean that both in the code and the consumer documentation, there is no
reference on how to handle messages that you receive that have a
partition_key (referred as keyed messages elsewhere on kafka projects). The
docs for Message.__init__ specify `Key`, but the name of the attribute you
need to access is `partition_key`

**Comment by emmett9001** [comment]
@marianov I've cleaned up the `Message` documentation on a [branch](http://pykafka.readthedocs.org/en/docs-protocol_literal/api/protocol.html#pykafka.protocol.Message) to make it clearer that it contains the `partition_key` attribute.
