### ISSUE TITLE
Cluster does not reconnect to disconnected brokers

### ISSUE THREAD

**Issue by cscheffler** [Parsely/pykafka#295]
Behaviour: a KafkaClient cluster does not reconnect to disconnected brokers that have become available again.

Test environment: a 3 broker Kafka cluster with a replication factor of 2 on the test topic.

To reproduce:
* Connect a producer to the cluster and produce messages continuously.
* The producer connects to 2 out of 3 brokers in the cluster, since the replication factor is 2. For this example, let's say we are connected to brokers 1 and 2, but not to broker 3.
* Stop broker 1.
* The producer notices the disconnect and updates the leader from 1 to 2 or 3 on some of its partitions.
* Everything keeps running smoothly.
* Start broker 1 again.
* Everything keeps running smoothly.
* Stop broker 2.
* The producer notices the disconnect and updates the leader from 2 to 1 or 3 on some of its partitions.
* The producer never tried to reconnect to broker 1, so sending messages fails.
* After 3 retries, the producer dies with an exception.

Error output:
```
2015-10-09 15:29:33,445 ERROR Exception encountered in worker thread:
  File "/workspace/pykafka/pykafka/producer.py", line 403, in queue_reader
    self.producer._send_request(batch, self)
  File "/workspace/pykafka/pykafka/producer.py", line 351, in _send_request
    "retries.", self._max_retries)

2015-10-09 15:29:33,448 INFO Blocking until all messages are sent
Traceback (most recent call last):
  File "produce-pykafka.py", line 46, in <module>
    break
  File "/workspace/pykafka/pykafka/producer.py", line 169, in __exit__
    self.stop()
  File "/workspace/pykafka/pykafka/producer.py", line 219, in stop
    self._wait_all()
  File "/workspace/pykafka/pykafka/producer.py", line 363, in _wait_all
    self._raise_worker_exceptions()
  File "/workspace/pykafka/pykafka/producer.py", line 154, in _raise_worker_exceptions
    raise ex
pykafka.exceptions.ProduceFailureError: ('Message failed to send after %d retries.', 3)
```

Proposed fix: Try to reconnect to all available brokers on a call to cluster.update(). Some connections might fail, but just leave those disconnected until the next call to update().

**Comment by cscheffler** [comment]
This pull request attempts to solve the problem: https://github.com/Parsely/pykafka/pull/296

Tested on my local cluster.

**Comment by emmett9001** [comment]
Excellent, I'll take a look at this on Monday.

On Friday, October 9, 2015, Andrew Montalenti <notifications@github.com>
wrote:

> Assigned #295 <https://github.com/Parsely/pykafka/issues/295> to
> @emmett9001 <https://github.com/emmett9001>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Parsely/pykafka/issues/295#event-431587293>.
>


-- 
Emmett Butler | Software Engineer
<http://www.parsely.com/?utm_source=Signature&utm_medium=emmett&utm_campaign=Signature>

**Comment by emmett9001** [comment]
Nice! I was running into this issue during my testing of #254, but actually had chalked up the error to some other cause, since I wasn't able to replicate it quite reliably enough. I'll test out the solution, but at first glance it looks good.
