### ISSUE TITLE
get_simple_consumer() TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by asifhj** [Parsely/pykafka#299]
Getting break on last message read from queue.

2015-10-13 11:20:54,438.438.999891281:pykafka.simpleconsumer:8868:DEBUG:1916:Partition 25 queue holds 5 messages
Traceback (most recent call last):
  File "C:/Users/asifj/PycharmProjects/Python_SOAP_OSSJ_SAP_Fusion_Kafka_Spark_HBase/KafkaConsumerDEV.py", line 28, in <module>
    for message in consumer:
  File "C:\Python27\lib\site-packages\pykafka\simpleconsumer.py", line 288, in __iter__
    message = self.consume(block=True)
  File "C:\Python27\lib\site-packages\pykafka\simpleconsumer.py", line 311, in consume
    while not message:
  File "C:\Python27\lib\site-packages\pykafka\protocol.py", line 169, in __len__
    size = 4 + 1 + 1 + 4 + 4 + len(self.value)
TypeError: object of type 'NoneType' has no len()
0 ?????

**Comment by emmett9001** [comment]
Hi @asifhj, thanks for reporting this. Are you able to post a code snippet that shows how you're triggering this error? Also, what version of pykafka are you running?

**Comment by asifhj** [comment]
Here is the code snippet

client = KafkaClient(hosts="xxx.22.147.232:9092,xxx.22.147.242:9092,xxx.22.147.243:9092")
print client.topics
topic = client.topics['SAPEvent']
consumer = topic.get_simple_consumer()
for message in consumer:
    if message is not None:
        print "Offset: "+str(message.offset)+"\tMessage: "+str(message.value)

**Comment by asifhj** [comment]
Yes this fix resolves it.

**Comment by emmett9001** [comment]
How about the code that uses the producer? Is it possible that you're putting a `None` into a message without realizing it?

**Comment by asifhj** [comment]
Producer is not able to send "None", I am reading from already queued messages.

**Comment by emmett9001** [comment]
Can you create a test case that reliably reproduces this issue? It's unclear how the consumer is getting into a state where this error becomes possible.

**Comment by yungchin** [comment]
I can't immediately see what the struct helpers return when a message is received with a null payload, but I suspect this is what would cause `None` to appear in `Message.value`. Our producer cannot produce such messages yet, so this would have to mean @asifhj used some other client to produce these messages?

(As per kafka docs, null payloads are special and different from empty strings, and they serve as "delete markers" during log compaction.)

**Comment by asifhj** [comment]
I agree your producer cannot produce `None` I tried it. In my case producer is different and consumer is from pykafka. But I still think it must handle `None` messages, I assume compaction process periodic not real time and we cannot wait for compaction process to delete null payloads.

**Comment by yungchin** [comment]
@asifhj no, totally agree - I wasn't suggesting it should not be fixed, but I wanted to check with you that this could indeed be to do with null payloads. Thanks for starting work on a fix already.
