### ISSUE TITLE
use_greenlets not Implemented?

### ISSUE THREAD

**Issue by blooshirt** [Parsely/pykafka#301]
Setting `use_greenlets` to `True` in the `KafkaClient` constructor results in an error. It sets the `KafkaClient._handler` to `None`, which is eventually called for a `Queue()` [here](https://github.com/Parsely/pykafka/blob/master/pykafka/handlers.py#L102), resulting in an error. The docs state regarding `use_greenlets`, `"If True, use gevent instead of threading"`. What is the intention for this feature? Is it something that is yet to be implemented, or something that has been deprecated? Either way, it might be useful to update the docs to reflect the current state.

**Comment by yungchin** [comment]
I believe this was carried over from the earlier samsa code base, and @kbourgoin has plans to reimplement it - he'll have a more complete answer for you.

**Comment by emmett9001** [comment]
`use_greenlets` is currently one of the lower-priority features on our future roadmap. Its presence is a holdover from a previous idea that hasn't yet been implemented. I'll update the docs.

**Comment by emmett9001** [comment]
I've [removed](https://github.com/Parsely/pykafka/commit/64df140a062ec0bb921eabf56180090d9b4a0b67) this option for now. I'll keep this issue open as a reminder to implement this at some point.

**Comment by emmett9001** [comment]
#365 is related to this

**Comment by emmett9001** [comment]
#368 is likely to be put into a release later this week, after which pykafka will support gevent for pure-python producers and consumers on cpython 2 and 3.
