### ISSUE TITLE
PyKafka NoMessagesConsumed Errors

### ISSUE THREAD

**Issue by jasonrhaas** [Parsely/pykafka#312]
PyKafka throws an error occasionally when trying to iterate through messages in a Kafka queue.  I imagine the issue is some consumer or zookeeper timeout issue, since I know that I am not consuming faster than my Kafka queue is being produced to.  I made a simple script to manually iterate through messages and after a while it throws this error:

```
Traceback (most recent call last):
  File "pykafka_test.py", line 50, in <module>
    k.consume()
  File "pykafka_test.py", line 37, in consume
    print self.balanced_consumer.consume().value
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 575, in consume
    message = self._consumer.consume(block=block)
  File "/usr/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 345, in consume
    self._raise_worker_exceptions()
  File "/usr/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 199, in _raise_worker_exceptions
    raise ex
pykafka.exceptions.NoMessagesConsumedError
```

I imagine its seeing some *null* value or something and just raising that exception.  Is this the desired behavior?  Should it return `None` instead?  In a gist that @amontalenti wrote, he had a code block that did this:

```
        msg = self.consumer.consume()
        if not msg:
            # nothing here
            return
```

This would work if `self.consumer.consume()` was returning `None`, but instead it raises an error.  You can catch this error with `except: NoMessagesConsumed` but I think this error message may be misleading and something else is going on.

Here's a simple script I'm using to test this:

https://gist.github.com/jasonrhaas/2281296a538908cfa85b

**Comment by amontalenti** [comment]
Thanks for reporting this Jason. We discussed this a little today and one of either @kbourgoin or @emmett9001 will look at this soon!

**Comment by yungchin** [comment]
Thanks very much for this. This exception was introduced with ac5fda0d, and indicates that a truncated message was received from kafka. We can probably change how we handle the error (as you've found, it currently aborts the fetcher thread).

I'm hoping @emmett9001 (who wrote the commit I referenced) may be able provide some extra context: would this error be recoverable if we re-fetch from the same offset? That is, is it just a truncated network transmission, or is there really only a partial message stored in kafka?

**Comment by jasonrhaas** [comment]
```
if len(buff) - offset < size:
    break
```

```
if len(messages) == 0 and attempted:
    raise NoMessagesConsumedError()
```
Trying to understand what this error actually means... so it looks like it gets raised if the `size` isn't what PyKafka expects?  What determines that size field and why is that important?  Is there some setting that maybe needs to be adjusted?

**Comment by yungchin** [comment]
The `size` is the `MessageSize` field here: https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets - so the incoming protocol message declares that it contains a message of that size, but then the whole thing turns out to be shorter than that. What I'm not yet clear about is if this happens when a transmission was cut short (so a retry would work), or if it's worse than that, and it means kafka holds a corrupted message set.

**Comment by emmett9001** [comment]
After taking a look, I can see adding retry logic either [here](https://github.com/Parsely/pykafka/blob/c72eea47a4592bec59e3d09becd100d7f75a538f/pykafka/simpleconsumer.py#L643) or [in the broker call](https://github.com/Parsely/pykafka/blob/c72eea47a4592bec59e3d09becd100d7f75a538f/pykafka/broker.py#L244) (probably the latter, come to think of it). I've never known Kafka to return a corrupted message size - I've only ever come across this error in cases where the wire message was truncated. That's not to say it's impossible, but raising an exception here may be a bit much. I think we can warn and retry a few times.

**Comment by emmett9001** [comment]
Today I stumbled on a bit of the [protocol documentation](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchAPI) that claims
```
As an optimization the server is allowed to return a partial message at
the end of the message set. Clients should handle this case.
```
I believe this means we can effectively `pass` instead of raising the `NoMessagesConsumed` error here.

**Comment by amontalenti** [comment]
Good catch, @emmett9001!

**Comment by jasonrhaas** [comment]
```
except NoMessagesConsumed:
    pass
```

Is this an effective workaround until the update gets merged in?  I realize `except: pass` is normally poor form.

**Comment by emmett9001** [comment]
@jasonrhaas I'm actually wondering the same thing. Since you're currently the one among us most able to replicate this error, please give that change a try. If it solves your problem, I'll be convinced that ignoring partial messages is a reasonable fix to close this issue, and I'll be able to make a pull request based on that idea.

**Comment by emmett9001** [comment]
@jasonrhaas On second thought, give [this pull request](https://github.com/Parsely/pykafka/pull/323/files) a try. I'm not sure what you're attempting will actually work, given that the consumer's fetcher thread may already have aborted by the time you're able to catch the exception.

**Comment by amontalenti** [comment]
@jasonrhaas We discussed this on our checkpoint call today, and we realized we'd like you to test this option for the balanced consumer:

https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L56

Also take a look at the `message.max.bytes` in the broker configuration:

https://kafka.apache.org/08/configuration.html

"The maximum size of a message that the server can receive. It is important that this property be in sync with the maximum fetch size your consumers use or else an unruly producer will be able to publish messages too large for consumers to consume."

**Comment by jasonrhaas** [comment]
@amontalenti @emmett9001 setting the `fetch_message_max_bytes` to match my `fetch.message.max.bytes` in my `consumer.properties` file for Kafka did the trick. :+1:

**Comment by emmett9001** [comment]
@jasonrhaas Excellent!
