### ISSUE TITLE
Make SimpleConsumer commit_offsets handle cluster updates too

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#325]
This is a relatively minor issue if running a pure `SimpleConsumer`, because the fetch workers will almost always resolve a `SocketDisconnectedError` before the auto-commit worker gets there. With an `RdKafkaSimpleConsumer` however, we don't run those fetch workers, so the auto-commit worker will have to fend for itself.

**Comment by emmett9001** [comment]
Related to #327
