### ISSUE TITLE
Cannot remove _zk_state_listener when creating BalancedConsumer failed

### ISSUE THREAD

**Issue by xqliang** [Parsely/pykafka#328]
When an exception raised from [here](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L438), the `_zk_state_listener` is [added](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L239), but the `_running` flag is not set yet. So calling `stop()` is [ignored](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L251), the `_zk_state_listener` and `_zookeeper` connection [which is owned by us](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L235) are still there.

We can set `_running` to `True` before `_add_self`, but we will encounter [NoNodeError](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L268) when stop it.

Another problem, when init `BalancedConsumer` with `auto_start=True`(the default setting), and an exception raised from [here](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L438), we cannot get the  instance reference, so there is no way to do cleanups.

**Comment by yungchin** [comment]
Thanks very much for this. I think we could solve this by 1) calling `stop()` if exceptions occur during `start()` (and maybe also adding a `__del__()` that runs `stop()`) and 2) instead of preventing `stop()` when not running, making `stop()` idempotent. Does that sound right?

If I may ask a favour: you seem to be able to trigger that exception out of `_add_self()` a lot - any chance you could turn that into a test case for `test_balancedconsumer.py`? Thanks!

**Comment by xqliang** [comment]
@yungchin OK, I'm going to try it sometime.

**Comment by emmett9001** [comment]
I don't think calling `stop()` in response to exceptions in `start()` entirely makes sense - isn't that the very thing that's causing the `NoNodeError`? `stop()` needs to be changed to not assume that everything in `start()` ran cleanly - possibly wrapping all of the zookeeper operations in `stop()` in a `try` that simply warns and passes on exception is good enough.

**Comment by emmett9001** [comment]
This issue can be reproduced with test code like this
```python
_zookeeper = KazooClient('127.0.0.1:2181', timeout=6)
    _zookeeper.start()
    consumer = topic.get_balanced_consumer("foo",
                                        auto_offset_reset=OffsetType.EARLIEST,
                                        reset_offset_on_start=True,
                                        auto_start=False,
                                        zookeeper=_zookeeper)
    try:
        consumer.start()
    except:
        consumer.stop()
```
and by adding a `True or` in the check in `_add_self()`.
