### ISSUE TITLE
Producer finaliser may fail to flush queue, hitting ReferenceError

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#352]
I just ran into a bug on the rdkafka branch, where queue-flushing fails due to the use of weakref (as @emmett9001 had warned about). We don't have test coverage for it, and I only noticed it by coincidence, spotting an unimportant-looking debugging log message.

In theory at least, the same bug should exist in `pykafka.Producer`, as of merging #329. This is not a regression, because before #329 we would never run the finaliser, so we would also never wait to flush the queue at program exit, but it needs fixing of course.

The `SimpleConsumer` and `BalancedConsumer` (which were also patched in #329) do not suffer from this problem: the only state they carry that needs flushing are the offsets, and we explicitly commit offsets on the thread that calls `stop()`, so we really don't care for weakref exceptions on the worker threads.

**Comment by yungchin** [comment]
@rogaha I'm tagging you here just to notify that there's probably still an issue with producer queue flushing.

**Comment by yungchin** [comment]
After adding a `del prod` to `test_async_produce()` (for reasons unrelated to this issue), here's a test run that hangs: https://travis-ci.org/Parsely/pykafka/jobs/90941409 (presumably in `prod._wait_all()` although we can't see that). We need a more explicit test case for this of course, but I think it confirms the suspicion that there's still a bug here.

**Comment by rogaha** [comment]
Thanks for spotting this @yungchin! Do you have an idea of how to approach it? We ended up using the upstream version ``2.0.3`` to avoid maintaining a fork and adding this right after the ``Producer`` instantiation: ``atexit.register(lambda p: p.stop() if p._running else None, producer)``.

**Comment by yungchin** [comment]
@rogaha if you're using `atexit`, you won't be affected by this particular problem, because when the atexit handlers run the producer object is still reachable and so there are no invalidated weakrefs yet. That is, if you call `stop()` via `atexit` it will successfully see the queue to flush through.

About your code snippet: `p._running` is not really part of the public interface, so it might at some point break for you. Are there issues if you just call `p.stop()`? It should be safe to call that unqualified, otherwise I'd say we have a bug in `stop()`. Thanks!

**Comment by yungchin** [comment]
See also #422 which confirms this isn't just theoretical.

**Comment by matthewatabet** [comment]
Do we know when this might be resolved?

PyKafka is working out really well for my use case, but I am seeing clutter in many of our logs from this which is confusing to other engineers. I've need to reassure folks a few times that we're not losing data. I suppose applying the workaround is the next step, but I thought I'd check first if there was an eta. Thanks a bunch!

**Comment by emmett9001** [comment]
I'm not 100% sure, but I think this issue is solved or at least partially addressed by #463.

**Comment by emmett9001** [comment]
I don't think this is the same as #463, but it's related. Looking at this in light of recent changes, I almost think it's ok to ask users to manually call `stop()` at program exit or to use the context manager. I'm not actually sure there's a fix necessary here. Thoughts?

**Comment by yungchin** [comment]
I think asking that users call `stop()` is OK as a workaround for now, but it does feel unpythonic that failing to call `stop()` would put you at risk of losing messages. I'd like to fix it, just haven't gotten to it so far, sorry.

**Comment by emmett9001** [comment]
@yungchin any thoughts on whether this is still an issue after the most recent round of fixes? It's still not clear to me from this thread how to actually replicate the issue.

**Comment by jayadevanm** [comment]
I was also running into this error. I am reading data from a file and publishing the lines to kafka after some manipulation. I was getting the error
`ReferenceError: weakly-referenced object no longer exists`

The messages were not getting published. So I ended the program like this - 
```
        producer.produce(str.encode(newrow))
producer.stop()
```
Now the messages are getting published but the script execution ends like this.
```

Exception in thread 1: pykafka.RequestHandler.worker for localhost:9092 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib64/python2.7/threading.py", line 763, in run
  File "/home/jay/sw/venv/lib/python2.7/site-packages/pykafka/handlers.py", line 191, in worker
  File "/usr/lib64/python2.7/Queue.py", line 174, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```
What am I doing wrong?

**Comment by emmett9001** [comment]
@jayadevanm What version of pykafka are you using? It doesn't look like you're doing anything wrong - that's just a nuisance error that I thought had been silenced in a recent update.

**Comment by jayadevanm** [comment]
pykafka - 2.3.0. But my kafka version is 0.9.0.0. I think that is the reason. On another machine where I have 0.8.2.2, I don't see this error.

**Comment by emmett9001** [comment]
Oh, that's quite interesting. This error in particular would not cause the tests to fail, so it's possible that it's going unhandled at the moment.

**Comment by yungchin** [comment]
@emmett9001 this is only an issue if you 1) call `produce()` and then 2) immediately get to the end of the program, so that the interpreter starts cleaning up.

In that case, `Producer.__del__()` may run before the queues are empty, and that will call `stop()`, which will wait for `queue_reader` to flush, but this will fail: at the point where `__del__` runs the weakref is no longer dereferenceable.

Getting rid of the weakref would require quite a reshuffle of `Producer` I'm afraid: the problem is that `queue_reader` calls `_send_request()`. I think it would not be illogical if that were a method of `OwnedBroker` instead, but it is a bit of a job to separate it from `Producer`.

**Comment by emmett9001** [comment]
The more I think about this issue the more I'm inclined to `wontfix` it. If i understand correctly, it only happens on interpreter shutdown. The producer already implements an api that ensures that this doesn't happen (the context manager form), so I'm not really sure we need to worry too much about the fact that there's an api that doesn't provide the same guarantees. Maybe I'm just being crazy, though.

**Comment by jayadevanm** [comment]
Does this mean if I add a line that makes my script sleep for, say, 5 seconds just before producer.stop(), it should make these messages go away?

**Comment by emmett9001** [comment]
I believe the sleep would have to be at least as many seconds as the `linger_ms` kwarg indicates. It's preferable to use the context manager, though, since it calls `stop()` automatically.
```python
with topic.get_producer() as prod:
    prod.produce("hi")
```

**Comment by rogaha** [comment]
@emmett9001 unfortunately that approach doesn't seem to be efficient as you need to instantiate a new `producer` for each `batch` of events you want to send (more context about it here: https://github.com/Parsely/pykafka/pull/311#issuecomment-154572215)

**Comment by emmett9001** [comment]
@rogaha After looking at this in more detail, I believe implementing the correct solution is more work than this fix is worth, since there's an existing workaround.

Would you mind sharing how you're currently working around this issue in your production system? Thanks for all of the information!
