### ISSUE TITLE
Raising configuration errors straight from `__init__()`

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#371]
Currently, some config parameters are only used in worker threads, and the result is that exceptions due to invalid parameters do not emerge when calling `__init__()` but only later, when the worker threads fail, and the exception is subsequently re-raised through `consume()` or `produce()`. I think the challenge here is to find a solution that provides a nicer user experience, and that also keeps validating code and worker thread code coherent.

(This was reported by @rduplain last week, but didn't get a ticket assigned yet.)

**Comment by emmett9001** [comment]
This is old, but I still think it's a good idea.
