### ISSUE TITLE
[pykafak/test/utils.py] KafkaInstance doesn't support the current Producer implementation

### ISSUE THREAD

**Issue by rogaha** [Parsely/pykafka#375]
<pre>
In [1]: from pykafka.producer import Producer
In [2]: from pykafka.test.utils import get_cluster, stop_cluster
In [3]: cluster = get_cluster()
In [4]: cluster.create_topic('test', 2, 3)
In [5]: client = KafkaClient(cluster.brokers)
In [6]: from pykafka.client import KafkaClient
In [7]: client = KafkaClient(cluster.brokers)
In [8]: producer = Producer(cluster, client.topics['test'])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-41cb2de6f39c> in <module>()
----> 1 producer = Producer(cluster, client.topics['test'])

/Users/rogaha/.virtualenvs/hydra/lib/python2.7/site-packages/pykafka/producer.pyc in __init__(self, cluster, topic, partitioner, compression, max_retries, retry_backoff_ms, required_acks, ack_timeout_ms, max_queued_messages, min_queued_messages, linger_ms, block_on_queue_full, sync)
    138         self._owned_brokers = None
    139         self._running = False
--> 140         self._update_lock = self._cluster.handler.Lock()
    141         self.start()
    142

AttributeError: 'KafkaInstance' object has no attribute 'handler'
</pre>

**Comment by emmett9001** [comment]
Looks like the `get_cluster` function is confusingly named. It doesn't return a `Cluster` instance, rather a `KafkaConnection` or `KafkaInstance`. These test utilities are not meant to be part of the public API, but we could certainly change the names.

The proper way to do what it looks like you're trying to do is
```python
client = KafkaClient(brokers)
producer = client.topics['test'].get_producer()
```

**Comment by rogaha** [comment]
Got it! It's working now, thanks for clarifying @emmett9001!
