### ISSUE TITLE
Write-up on using librdkafka + pykafka, and benchmarking C vs Python

### ISSUE THREAD

**Issue by amontalenti** [Parsely/pykafka#378]
- can make it part of our ReadTheDocs
- publicize on Parse.ly blog
- include in an ANN of pykafka preliminary 0.9 support + C protocol support to kafka-users group

**Comment by emmett9001** [comment]
In-porgress draft of a post for the Parse.ly blog: https://gist.github.com/yungchin/0b107fd9f4e532de2da5

**Comment by emmett9001** [comment]
What's the status of this effort @yungchin? Should this issue be reassigned or closed?

**Comment by yungchin** [comment]
@emmett9001 publication of that post is still pending, as far as I know. I don't think I've anything to add to it, but as for the benchmarks, it might be nice to have a discussion about them in some more detail than the blog post allowed, either under this ticket or on the mailing list, if you prefer?

**Comment by emmett9001** [comment]
Closing this since it seems to have stalled and I think @amontalenti has it in his backlog.
