### ISSUE TITLE
rdkafka memory issue

### ISSUE THREAD

**Issue by jofusa** [Parsely/pykafka#379]
First wonderful project, i've watching from the sidelines and really excited about pushing for first class python tools in the kafka ecosystem. 

I have started testing the new rdkafka support in 2.1.0 and i do see a throughput improvement (yeah!), but there appears to be a memory leak. My attempts to implement memory profiling have come up with very little because the tooling around C extensions is limited and my knowledge is even less. 

I'm going to dig deeper next week but wanted to put a note here to see if anyone else run into this. 

I am deploying these workers as docker containers, so i am not ruling out some issue with my container setup, but below is a chart of memory.rss for the same container. The flat lines are configured `use_rdkafka=False`, the ominous slanted line only difference is `use_rdkafka=True`. These are configured from envvars so the underlying images are the same.

<img width="603" alt="screen shot 2015-12-05 at 12 02 20 pm" src="https://cloud.githubusercontent.com/assets/800669/11609593/2f9a0642-9b48-11e5-8f86-ea8b3ea0b8af.png">

Sorry for the vagueness of this, i work on getting some better threads to pull on next week.

My setup:
pykafka 2.1.0
rdkafka 0.8.6

**Comment by yungchin** [comment]
@jofusa thanks for reporting this! Are you seeing this with a producer or consumer? And can you give me an idea of what kind of message volume you're moving over the time of that plot? (I made some last-minute updates to how producer delivery-reporting works just before we released 2.1.0, and so I wonder if your graph is showing that that somehow leaks `protocol.Message` references...)

Thanks!

**Comment by jofusa** [comment]
This worker is using both a consumer and a producer. I can tun off the producer to help isolate the issue.

The message rates aren't crazy ~500/s per a worker.

Also here is the obligatory crash:

<img width="602" alt="screen shot 2015-12-05 at 1 37 15 pm" src="https://cloud.githubusercontent.com/assets/800669/11610099/b8bf1676-9b55-11e5-96e9-6d987187dc85.png">

**Comment by jofusa** [comment]
Removing the producer did not stop the issue. Still creeping memory like before

**Comment by yungchin** [comment]
Thanks @jofusa I think I found the problem: pretty ugly double-definition that slipped in last month! It should be fixed by #381. As you said, the tooling is a bit lacking - I'm not sure how to write a straightforward test case that would detect this, eg I can't get `gc.collect()` to warn me about this one.

**Comment by jofusa** [comment]
Thanks for fixing! thats a nasty one. who said C extensions were hard...

I tried this with no luck. https://pythonhosted.org/Pympler/muppy.html

At some point, aggregate cpu hours are what is needed. Which means RCs and a willing community.

**Comment by dan-blanchard** [comment]
@emmett9001, this would be the reason for the crazy memory usage earlier.

**Comment by emmett9001** [comment]
That'll do it. I'll be making a new release before EOD tomorrow.
