### ISSUE TITLE
Possible performance issues with BalancedConsumer

### ISSUE THREAD

**Issue by waypointsoftware** [Parsely/pykafka#380]
I've currently got a scenario where I am sending 50-150 messages to kafka while I have a consumer script running and I'm printing out the current time whenever a message is read. My consumer code looks something like this:

```python
timeout=10000
consumer = get_balanced_consumer(queue=queue,
                                        consumer_group=group,
                                        auto_commit_enable=True,
                                        zookeeper_connect=Service('zookeeper').hosts,
                                        consumer_timeout_ms=timeout,
                                        use_rdkafka=False)
for message in consumer:
    if message:
        print("offset-{0} - {1}".format(message.offset, datetime.datetime.utcnow()))
        #consume(message)
```

*NOTE: I have simplified the code as much as possible to eliminate all other factors

I am seeing a lot of long delays randomly happening between messages and I'm wondering what might be going on, here is the output:

...20 some odd messages
offset-3086 - 2015-12-06 04:48:05.691443
offset-3087 - 2015-12-06 04:48:05.720971
offset-3088 - 2015-12-06 04:48:05.751728
offset-3089 - 2015-12-06 04:48:07.801828
offset-3090 - 2015-12-06 04:48:07.832760
...20 more messages

...another run
offset-3210 - 2015-12-06 04:48:50.601347
offset-3211 - 2015-12-06 04:48:50.628328
offset-3212 - 2015-12-06 04:48:50.655916
offset-3213 - 2015-12-06 04:48:52.800826
offset-3214 - 2015-12-06 04:48:52.831820
offset-3215 - 2015-12-06 04:48:52.861711

This happens with just about every batch of messages I send. 

Also, one interesting thing to point out is this 2 second delay in reading messages happens exactly every 5 seconds.

Any help appreciated

**Comment by yungchin** [comment]
@waypointsoftware thanks for reporting this. I can't reproduce this just now, but it may well be my test setup is missing some ingredient that causes it. Could you mix in some debug logging, to get an idea what `BalancedConsumer` is up to in those 2-second gaps? (I often just throw in a `import logging ; logging.basicConfig(level=logging.DEBUG)` but beware that may produce a barrage of log lines).

**Comment by waypointsoftware** [comment]
Here is the log output, again you can see the gaps in time. It appears as though every time it has to go back and read more messages is when it pauses...at least according to this output

offset-5819 - 2015-12-06 15:35:20.558765
offset-5820 - 2015-12-06 15:35:20.558889
offset-5821 - 2015-12-06 15:35:20.558984
offset-5822 - 2015-12-06 15:35:20.559074
DEBUG:pykafka.simpleconsumer:Fetched 5 messages for partition 0
2015-12-06 15:35:21,546 - pykafka.simpleconsumer - DEBUG - Fetched 5 messages for partition 0
DEBUG:pykafka.simpleconsumer:Partition 0 queue holds 5 messages
2015-12-06 15:35:21,547 - pykafka.simpleconsumer - DEBUG - Partition 0 queue holds 5 messages
DEBUG:pykafka.simpleconsumer:Fetched 5 messages for partition 0
2015-12-06 15:35:21,550 - pykafka.simpleconsumer - DEBUG - Fetched 5 messages for partition 0
DEBUG:pykafka.simpleconsumer:Partition 0 queue holds 10 messages
2015-12-06 15:35:21,551 - pykafka.simpleconsumer - DEBUG - Partition 0 queue holds 10 messages
offset-5823 - 2015-12-06 15:35:21.575030
offset-5824 - 2015-12-06 15:35:21.575212
offset-5825 - 2015-12-06 15:35:21.575342
offset-5826 - 2015-12-06 15:35:21.575469
offset-5827 - 2015-12-06 15:35:21.575631
offset-5828 - 2015-12-06 15:35:21.575764
offset-5829 - 2015-12-06 15:35:21.575891
offset-5830 - 2015-12-06 15:35:21.576015
offset-5831 - 2015-12-06 15:35:21.576141
offset-5832 - 2015-12-06 15:35:21.576283
DEBUG:pykafka.simpleconsumer:Fetched 5 messages for partition 0
2015-12-06 15:35:22,121 - pykafka.simpleconsumer - DEBUG - Fetched 5 messages for partition 0
DEBUG:pykafka.simpleconsumer:Partition 0 queue holds 5 messages
2015-12-06 15:35:22,121 - pykafka.simpleconsumer - DEBUG - Partition 0 queue holds 5 messages
DEBUG:pykafka.simpleconsumer:Fetched 4 messages for partition 0
2015-12-06 15:35:22,124 - pykafka.simpleconsumer - DEBUG - Fetched 4 messages for partition 0
DEBUG:pykafka.simpleconsumer:Partition 0 queue holds 9 messages
2015-12-06 15:35:22,125 - pykafka.simpleconsumer - DEBUG - Partition 0 queue holds 9 messages
offset-5833 - 2015-12-06 15:35:22.141267
offset-5834 - 2015-12-06 15:35:22.141396
offset-5835 - 2015-12-06 15:35:22.141472
offset-5836 - 2015-12-06 15:35:22.141546
offset-5837 - 2015-12-06 15:35:22.141656
offset-5838 - 2015-12-06 15:35:22.141730
offset-5839 - 2015-12-06 15:35:22.141803
offset-5840 - 2015-12-06 15:35:22.141876
offset-5841 - 2015-12-06 15:35:22.141947
DEBUG:pykafka.simpleconsumer:Fetched 1 messages for partition 0
2015-12-06 15:35:24,475 - pykafka.simpleconsumer - DEBUG - Fetched 1 messages for partition 0
DEBUG:pykafka.simpleconsumer:Partition 0 queue holds 1 messages
2015-12-06 15:35:24,475 - pykafka.simpleconsumer - DEBUG - Partition 0 queue holds 1 messages
offset-5842 - 2015-12-06 15:35:24.511403

**Comment by yungchin** [comment]
Hmm yeah that's puzzling. Just to be sure: this is with default settings
for things like `fetch_min_bytes` and `fetch_message_max_bytes` (in
consumer init settings), right?

What stands out to me is that you seem to have a fairly low rate of message
production (unless there's some other reason you can only fetch 4-5
messages at a time - are they each relatively large, say on the order of
`fetch_message_max_bytes`?). At low production rates, it's always going to
be more difficult to hide consumer fetch latency, as fetches block waiting
for more messages, and the consume thread blocks waiting for the fetcher.

Still, I agree the fetch intervals seem strangely long. Hence why I'm
wondering if you've maybe got a larg-ish `fetch_min_bytes` setting or
such...

**Comment by waypointsoftware** [comment]
each message is around 50-75kb, so yes probably much larger than normal.
but this didn't happen with the pyyhon-kafka consumer. we switched to
balanced consumer so we r could handle multiple consumers in parallel.

are the any configuration settings that could help improve this?

**Comment by waypointsoftware** [comment]
also, both those settings are the defaults right now

**Comment by emmett9001** [comment]
@waypointsoftware are you using pykafka to produce messages to kafka, or some other client? If you're using pykafka on the producer side, there may be a simple answer to this, since the producer does have a default `linger_ms` of five seconds and a default `min_queued_messages` of 70000. This means that if you're only sending 150 messages per second, the pykafka producer will wait the full five seconds before flushing a single batched request to the broker.

If this sounds like your situation, you can probably fix it by adjusting `min_queued_messages` and/or `linger_ms` in the `Producer()` constructor - see the [`Producer.__init__` docs](http://pykafka.readthedocs.org/en/latest/api/producer.html#pykafka.producer.Producer.__init__) for specifics.

**Comment by waypointsoftware** [comment]
Thanks for the tips, both of these suggestions helped or fixed the problem directly

**Comment by thao6626** [comment]
thanks @emmett9001 for the answer, it is exactly the reason why the consumer consumes msg every 5s interval.
