### ISSUE TITLE
BalancedConsummer's commit_offsets() stucks if no message yet comsumed (?)

### ISSUE THREAD

**Issue by tigran-a** [Parsely/pykafka#384]
Hi,

it seems to me that if I call commit_offsets() on a consumer that has not yet consumed anything, then the execution is blocked.... Does not seem to be a good behaviour, or maybe i'm doing something wrong

Thanks

**Comment by emmett9001** [comment]
Hi @tigran-a, thanks for the issue. With the following code:
```python
consumer = topic.get_balanced_consumer(
    consumer_group="foo",
    auto_commit_enable=False,
    auto_start=False
)
consumer.commit_offsets()
```
I don't notice any unnecessary blocking, but I do see a crash in `commit_offsets`, which is improved [here](https://github.com/Parsely/pykafka/pull/385/files). Is this code comparable to what you're using to trigger the blocking behavior? If not, please post some code that I can use to replicate the error.

**Comment by tigran-a** [comment]
Hi, 

My settings looks more like that:
```
consumer = topic.get_balanced_consumer(
        consumer_group="...", 
        zookeeper_connect="...", 
        consumer_timeout_ms=100,
        auto_commit_enable=True)

consumer.consume()
time.sleep(5)
consumer.commit_offsets()
```
I've just tried a smaller example myself and it seems working
I think my issue was that I was running the consumer in a separate process and used wrongly inter-process communication... Unfortunately I can't reproduce it, feel free to close. Thanks!
