### ISSUE TITLE
Offset resets while Kafka cluster unavailable.

### ISSUE THREAD

**Issue by cameronmaske** [Parsely/pykafka#396]
Hi,
I had a question about the intended behavior of a consumer and the offset while a Kafka cluster is unavailable. 
This scenario happened when I restarted a `kafka` cluster while a consumer was still running. 

Here is the simplified  consumer code (running on pykafka 2.0.4)

```
    consumer = grid_topic.get_balanced_consumer(
        consumer_group="...",
        zookeeper_connect="..",
        auto_commit_enable=False
    )

    while True:
         message = message.consume()
         process(message)
         consumer.commit()
```
Here are the logs during when the kafka cluster was restarting.
```
Dec 17 17:06:01 <ip> docker[2033]: INFO:pykafka.cluster:Attempting to discover offset manager for consumer group 'dumont'
Dec 17 17:06:01 <ip> docker[2033]: INFO:pykafka.cluster:Found coordinator broker with id 1
Dec 17 17:06:01 <ip> docker[2033]: ERROR:pykafka.simpleconsumer:Error fetching offsets for topic grid (errors: {<class 'pykafka.exceptions.OffsetsLoadInProgress'>: [0]})
Dec 17 17:06:01 <ip> docker[2033]: ERROR:pykafka.simpleconsumer:Error fetching offsets for topic grid (errors: {<class 'pykafka.exceptions.OffsetsLoadInProgress'>: [0]})
Dec 17 17:06:02 <ip> docker[2033]: INFO:pykafka.handlers:RequestHandler worker: exiting cleanly
Dec 17 17:06:02 <ip> docker[2033]: INFO:pykafka.handlers:RequestHandler worker: exiting cleanly
Dec 17 17:06:02 <ip> docker[2033]: ERROR:pykafka.simpleconsumer:Error fetching offsets for topic grid (errors: {<class 'pykafka.exceptions.OffsetsLoadInProgress'>: [0]})
Dec 17 17:06:04 <ip> docker[2033]: ERROR:pykafka.simpleconsumer:Error fetching offsets for topic grid (errors: {<class 'pykafka.exceptions.OffsetsLoadInProgress'>: [0]})
Dec 17 17:06:07 <ip> docker[2033]: ERROR:pykafka.simpleconsumer:Error fetching offsets for topic grid (errors: {<class 'pykafka.exceptions.OffsetsLoadInProgress'>: [0]})
Dec 17 17:06:11 <ip> docker[2033]: INFO:pykafka.simpleconsumer:Starting 1 fetcher threads
Dec 17 17:06:11 <ip> docker[2033]: INFO:pykafka.balancedconsumer:Rebalancing Complete.
Dec 17 17:06:11 <ip> docker[2033]: INFO:pykafka.simpleconsumer:Resetting offsets in response to OffsetOutOfRangeError
Dec 17 17:06:11 <ip> docker[2033]: INFO:pykafka.simpleconsumer:Resetting offsets for 1 partitions
Dec 17 17:06:11 <ip> docker[2033]: INFO:pykafka.simpleconsumer:Flushed queue for partition 0
```

This is my current understanding of what is happening behind the scenes, please point out if I've made a mistake! 

This behavior from the logs matches the [code](https://github.com/Parsely/pykafka/blob/e3fb2e95ff29d9bfcb080991ad6dcbf140a71ac9/pykafka/simpleconsumer.py#L494).

It retries to fetch the offset ([5 times, backing off 1000ms * try number each time](https://github.com/Parsely/pykafka/blob/e3fb2e95ff29d9bfcb080991ad6dcbf140a71ac9/pykafka/simpleconsumer.py#L64)) before continuing. 

**After it continues, it assumes the offset cannot be found, and therefore resets it according to the `auto_offset_reset`.**

This behavior doesn't seem ideal (at least in our application). It seems to be able to detect the `OffsetsLoadInProgress` error, would it make sense to raise an Exception if that is the last  error encountered on the retry as the offset should be available afterward? 

It appears the retry does already do something with [`NotCoordinatorForConsumer` and `OffsetsLoadInProgress`]((https://github.com/Parsely/pykafka/blob/e3fb2e95ff29d9bfcb080991ad6dcbf140a71ac9/pykafka/simpleconsumer.py#L518)) exceptions, but I'm not sure what that is.

Happy to provide more details if it's helpful!

**Comment by yungchin** [comment]
Thanks very much for raising the issue. I think it would make a lot of sense to offer an option to raise an exception. Just to check I understand your point: let's say we'd add a third choice for `auto_offset_reset`, so that we'd have `EARLIEST`, `LATEST`, and `EXCEPT`, where the latter would mean "if all offset fetch retries failed, don't reset the offset but raise an exception", would that fit the bill?

**Comment by emmett9001** [comment]
I don't think that idea works, since `auto_offset_reset` is used in other contexts than offset fetches. @cameronmaske, do I understand correctly that your suggestion is to have `fetch_offsets` raise an exception if after five retries it's left with `OffsetsLoadInProgress` responses - the idea being that client code could wait a bit longer for the offsets load to complete before retrying the offset fetch? If so, it sounds to me like increasing `offsets_commit_max_retries` might solve that problem elegantly.

**Comment by cameronmaske** [comment]
Yup, more along the lines of what @emmet9001 mentioned. This happened as there was a small window (from the logs about 5 seconds) after checking the offset failed where the code started consuming and the offset become writable.


I think there is still merit in raising an exception for certain Kafka errors that show the offset topic is not yet available on a consumer's start. In our case where we are calling commit_offset manually, I rather have the consumer fail at start to prevent it.

We have bumped up the max_retries to something like 20 and an interval of 2500ms. But if Kafka's startup period exceeds that, it will still fail (unlikely but possible) this could still happen. 

Thoughts?

**Comment by emmett9001** [comment]
That makes sense. I'll have to give some thought to how we might support this, though. I don't think we want this case to raise exceptions all the time, but it's possible we could use a config option to enable that behavior.

**Comment by cameronmaske** [comment]
@emmett9001 Thanks for resolving this!
