### ISSUE TITLE
Producer Thread throws 'NoneType' object is not callable

### ISSUE THREAD

**Issue by peacecoder** [Parsely/pykafka#399]
Hi all,

when I use pykafka producer to send msg to kafka. Mostly, it works well, however with time passed by, the following error consistently appears.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 406, in queue_reader
  File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 461, in flush
  File "/usr/local/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/site-packages/pykafka/handlers.py", line 150, in worker
  File "/usr/local/lib/python2.7/Queue.py", line 174, in getException in thread Thread-13 (most likely raised during interpreter shutdown):
```
Here is the way I use pykafka producer, please tell me if i am wrong.

**Pykafka Version: 2.0.3**

```
    client = KafkaClient(hosts=localhost:9092)
    topic = client.topics[topic_name]
    with topic.get_producer() as producer:
        with open(file_name) as f:
            for line in f:
                jsonString = convertToJson(line, log_type, local_host_name, region)
                if not jsonString:
                    logging.getLogger().error('convert log to json fail: %s'%line)
                    continue
                producer.produce(jsonString)
```

finally, I find the doc 

```
if count % 10**5 == 0:  # adjust this or bring lots of RAM ;)
```
what do you mean by this? does it mean that if I change 10**5, it will bring logs of RAM?

**Comment by emmett9001** [comment]
Hi @MuscleCoder, thanks for checking this in. It's a tough one to diagnose without more information. It appears that one of the producer threads is crashing, but it's not clear how exactly that's happening. Is there any additional error output or sample code you can provide? Your sample code looks fine (other than missing quotes around the `hosts` kwarg of `KafkaClient()`, which I assume is a typo).

"adjust this or bring lots of RAM" is an imprecise way of indicating that allowing the delivery report queue to fill up to 100k+ messages wil use up a lot of memory. Since you're not using delivery reports (since `topic.get_producer(delivery_reports=False)`, this shouldn't have any bearing on the error you're seeing.

**Comment by MuscleCoder** [comment]
Hi @emmett9001 thanks for pointing out the typo.

Another information maybe useful is that, when these exception appears, I find that in kafka there is kafka.common.NotLeaderForPartitionException thrown out. Dose this will cause the producer thread crash? Meanwhile, I also find that, when this happens, the producer seems hanging there, And I have to force to kill it. That's really weird.

BTW, will delivery_reports decrease the efficiency of producer, but it will help to guarantee to deliver the msg, right? If I can tolerate duplicate msg, will resending the msg solves the problem, even if the NotLeaderForPartitionException?

Thanks

**Comment by MuscleCoder** [comment]
BTW, @emmett9001 , I find that when the file is empty, the producer tend to be hanging there. I think with 'with' clause, it will close the producer automatically.

Do i need to decrease the linger_ms? or update to the latest version?

**Comment by emmett9001** [comment]
It's hard to say exactly what's causing the producer to hang on `__exit__`, though a likely cause is that it's hitting `_wait_all` with messages in the queue that continue to fail.

Mind posting the output of `bin/kafka-topics.sh --describe --zookeeper zookeeper1:2181 --topic mytopic`? This could be related to frequent leader elections, but it's not clear whether they'd be happening too often in this particular case.

**Comment by MuscleCoder** [comment]
hi @emmett9001 

sorry for reply late. Here is the topic info

```
Topic:test-log    PartitionCount:35       ReplicationFactor:3     Configs:
        Topic: test-log   Partition: 0    Leader: 1       Replicas: 1,5,2 Isr: 1,5,2
        Topic: test-log   Partition: 1    Leader: 2       Replicas: 2,1,3 Isr: 2,3,1
        Topic: test-log   Partition: 2    Leader: 3       Replicas: 3,2,4 Isr: 3,4,2
        Topic: test-log   Partition: 3    Leader: 4       Replicas: 4,3,5 Isr: 4,5,3
        Topic: test-log   Partition: 4    Leader: 5       Replicas: 5,4,1 Isr: 5,1,4
        Topic: test-log   Partition: 5    Leader: 1       Replicas: 1,2,3 Isr: 1,3,2
        Topic: test-log   Partition: 6    Leader: 2       Replicas: 2,3,4 Isr: 2,4,3
        Topic: test-log   Partition: 7    Leader: 3       Replicas: 3,4,5 Isr: 3,4,5
        Topic: test-log   Partition: 8    Leader: 4       Replicas: 4,5,1 Isr: 4,1,5
        Topic: test-log   Partition: 9    Leader: 5       Replicas: 5,1,2 Isr: 5,1,2
        Topic: test-log   Partition: 10   Leader: 1       Replicas: 1,3,4 Isr: 1,3,4
        Topic: test-log   Partition: 11   Leader: 2       Replicas: 2,4,5 Isr: 2,4,5
        Topic: test-log   Partition: 12   Leader: 3       Replicas: 3,5,1 Isr: 3,5,1
        Topic: test-log   Partition: 13   Leader: 4       Replicas: 4,1,2 Isr: 4,1,2
        Topic: test-log   Partition: 14   Leader: 5       Replicas: 5,2,3 Isr: 5,2,3
        Topic: test-log   Partition: 15   Leader: 1       Replicas: 1,4,5 Isr: 1,5,4
        Topic: test-log   Partition: 16   Leader: 2       Replicas: 2,5,1 Isr: 2,1,5
        Topic: test-log   Partition: 17   Leader: 3       Replicas: 3,1,2 Isr: 3,2,1
        Topic: test-log   Partition: 18   Leader: 4       Replicas: 4,2,3 Isr: 4,3,2
        Topic: test-log   Partition: 19   Leader: 5       Replicas: 5,3,4 Isr: 5,3,4
        Topic: test-log   Partition: 20   Leader: 2       Replicas: 2,5,1 Isr: 2,1,5
        Topic: test-log   Partition: 21   Leader: 3       Replicas: 3,1,2 Isr: 3,2,1
        Topic: test-log   Partition: 22   Leader: 4       Replicas: 4,2,3 Isr: 4,3,2
        Topic: test-log   Partition: 23   Leader: 5       Replicas: 5,3,4 Isr: 5,4,3
        Topic: test-log   Partition: 24   Leader: 1       Replicas: 1,4,5 Isr: 1,5,4
        Topic: test-log   Partition: 25   Leader: 2       Replicas: 2,5,1 Isr: 2,1,5
        Topic: test-log   Partition: 26   Leader: 3       Replicas: 3,1,2 Isr: 3,2,1
        Topic: test-log   Partition: 27   Leader: 4       Replicas: 4,2,3 Isr: 4,3,2
        Topic: test-log   Partition: 28   Leader: 5       Replicas: 5,3,4 Isr: 5,3,4
        Topic: test-log   Partition: 29   Leader: 1       Replicas: 1,4,5 Isr: 1,5,4
        Topic: test-log   Partition: 30   Leader: 2       Replicas: 2,5,1 Isr: 2,1,5
        Topic: test-log   Partition: 31   Leader: 3       Replicas: 3,1,2 Isr: 3,2,1
        Topic: test-log   Partition: 32   Leader: 4       Replicas: 4,2,3 Isr: 4,3,2
        Topic: test-log   Partition: 33   Leader: 5       Replicas: 5,3,4 Isr: 5,4,3
        Topic: test-log   Partition: 34   Leader: 1       Replicas: 1,4,5 Isr: 1,5,4
```

**Comment by emmett9001** [comment]
Here's the line from which the original traceback appears to originate: https://github.com/python/cpython/blob/2.7/Lib/threading.py#L168 I'm still not sure what this means, though.

**Comment by emmett9001** [comment]
Looks like this could be related to [this kafka bug](https://issues.apache.org/jira/browse/KAFKA-2082)

**Comment by MuscleCoder** [comment]
Hi @emmett9001,

Here is my pykafka version,

---
Metadata-Version: 1.1
Name: pykafka
Version: 2.0.3
Summary: Full-Featured Pure-Python Kafka Client
Home-page: https://github.com/Parsely/pykafka
Author: Keith Bourgoin and Emmett Butler
Author-email: pykafka-user@googlegroups.com
License: Apache License 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: kazoo, tabulate
Entry-points:
  [console_scripts]
  kafka-tools = pykafka.cli.kafka_tools:main

I will have a try for 2.1.2

Thanks

**Comment by emmett9001** [comment]
@MuscleCoder 2.2.0 was actually released yesterday. Give that a try if you can.

**Comment by emmett9001** [comment]
This issue is old enough and similar enough to #393 that I feel fine closing it, since it seems very likely to have been fixed in the intervening version updates. @MuscleCoder, if you're still experiencing this issue, please feel free to comment and/or reopen this issue. Thanks!

**Comment by abrugh** [comment]
I know this bug has been closed already but I've run across it in my setup, not even in code I wrote, just by using kafka-tools to print the offsets of a topic. It happens quite frequently on my development setup. Here's an example of me hitting up and enter a bunch to cause it to happen. The amount of traceback that makes it to the console seems to vary each run. Sometimes it is a single line, sometimes it looks like two or three tracebacks mashed together (due to threading, as mentioned earlier in this thread).

```
vagrant@head:~/$ date && kafka-tools print_offsets mytopic LATEST
Wed Feb 24 19:57:54 UTC 2016
 Partition    Offset
-----------  --------
     0        470857
     1        470480
vagrant@head:~/$ date && kafka-tools print_offsets mytopic LATEST
Wed Feb 24 19:57:55 UTC 2016
 Partition    Offset
-----------  --------
     0        470857
     1        470480
Exception in thread 1: pykafka.RequestHandler.worker for head:9092 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/dist-packages/pykafka/handlers.py", line 188, in worker
  File "/usr/lib/python2.7/Queue.py", line 174, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callableException in thread 0: pykafka.RequestHandler.worker for localhost:9092 (most likely raised during interpreter shutdown):
vagrant@head:~/$ date && kafka-tools print_offsets mytopic LATEST
Wed Feb 24 19:57:55 UTC 2016
 Partition    Offset
-----------  --------
     0        470857
     1        470480
```

My environment is a single node vagrant running Ubuntu 14.04.3 LTS. One instance of Kafka running and one instance of Zookeeper.

```
vagrant@head:~$ cat /etc/issue.net
Ubuntu 14.04.3 LTS
vagrant@head:~$ uname -a
Linux head 3.13.0-73-generic #116-Ubuntu SMP Fri Dec 4 15:31:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Kafka is 0.8.2.2
Zookeeper is 3.4.6
librdkafka is 0.8.6
pykafka is 2.2.1

The topic description is
```
vagrant@head:~$ /usr/lib/kafka/bin/kafka-topics.sh --describe --zookeeper localhost --topic mytopic
Topic:mytopic   PartitionCount:2        ReplicationFactor:1     Configs:
        Topic: mytopic  Partition: 0    Leader: 0       Replicas: 0     Isr: 0
        Topic: mytopic  Partition: 1    Leader: 0       Replicas: 0     Isr: 0
```

I don't see anything in the kafka or zookeeper logs related to this.
