### ISSUE TITLE
balanced consumer commits offsets on rebalance

### ISSUE THREAD

**Issue by duilio** [Parsely/pykafka#408]
I don't understand why this is the default behavior even if autocommit mode is not enabled.

It looks like the current library is designed for an at-most-once delivery without actually making the caller in condition to decide it. Probably adding a pre-rebalance callback would be a step forward to this direction.

Also, if I've understood correctly the caller would still be running during the rebalance (I guess the zk callbacks are handled in another thread), this means that it could actually still fetch new messages from the consumer making the at-most-once delivery fail.

**Comment by emmett9001** [comment]
Thanks @duilio, this is the [issue](https://github.com/Parsely/pykafka/issues/167) that initially prompted this behavior. I think that even when the user explicitly chooses not to have offsets autocommitted, it's still necessary to commit them before a rebalance for the reasons described in #167. Namely, the reason is that `_rebalance` cannot call `reset_offsets` more than once, because doing so would cause it to skip messages produced during the rebalance. This makes `_rebalance` fully reliant on `fetch_offsets` (the committed offset) for its starting offsets. This does feel like an ugly solution, and I think it would be best to come up with a way around it. That may end up involving a lot of refactoring, though.

I don't fully follow your concern about the consumer running during a rebalance. Pykafka keeps track of the [offset of the last message consumed by the client](https://github.com/Parsely/pykafka/blob/9e8e7a9ee4ab09580fac6917d300f56b9b14c0c3/pykafka/simpleconsumer.py#L834), and it makes sure to [fetch](https://github.com/Parsely/pykafka/blob/9e8e7a9ee4ab09580fac6917d300f56b9b14c0c3/pykafka/simpleconsumer.py#L785) new messages from that offset.

**Comment by duilio** [comment]
Hi @emmett9001, I was assuming a code like this:

```python
for x in consumer:
    process(x)
```

I wonder if during the rebalance this code just goes on. The rebalance lock seems to be used only by `_rebalance` itself and the `close` method. Let's assume this run (offsets are represented by the pair <partition id, offset>, we start with a consumer group with one node and we add a second one later):

```
node1: offset <1,1> consumed
node1: offset <2,1> consumed
node1: offset <1,2> consumed || rebalance (a new consumer joins the group), offsets are committed now
node1: offset <2,2> consumed || rebalance in progress
node1: offset <1,3> consumed || rebalance finished: part1 belongs to node1, part2 to node2
node1: offset <1,3> consumed <-- duplicate processing for partition 1
node2: offset <2,2> consumed <-- duplicate processing also for partition 2
```

As far as I've understood this could actually happen because the rebalance is done in a parallel thread and there is no lock for the `consume` method.

About the issue #167 I still feel like that's the correct behavior when `auto_commit_enable` is `True` but I would rather give the caller the responsibility to commit the offsets when it is `False`. I wonder if this would be possible by just adding a pre-rebalance callback.

**Comment by emmett9001** [comment]
@duilio You're right that the sequence of events you described can occur. Kafka's semantics don't offer a way to ensure exactly-once delivery without the client storing consumer offsets itself. See [this comment](https://github.com/Parsely/pykafka/issues/389#issuecomment-163985917) for more information.

I'm apprehensive about giving forcing the caller to manually commit offsets during a rebalance. It can cause very weird message duplication bugs (of a kind that are actually avoidable) if the offsets are not committed, and making that behavior the default seems dangerous to me. This behavior is a result of the fact that `BalancedConsumer` contains a `SimpleConsumer` instance, so maybe that design decision could stand some scrutiny.

**Comment by duilio** [comment]
Hi @emmett9001, I explain briefly my use case, so to give you a bigger picture of my issue with the current implementation.

Kafka is currently part of our ad serving pipeline (at viralize.com), we are currently developing a new analytics solution that works more or less like this:

```
adservers -> log (kafka) -> sessionizer -> datapoints (kafka)
```

sessionizer is a consumer whose job is to enrich the data from the raw event logs, discard invalid events, run some fraud detection algorithms and produce datapoints for a timeseries database. The balanced consumer looks like a perfect fit for us in order to distribute the sessionizer processing.

sessionizer main loop is kind of:

```python
while True:
    batch = consume_batch()
    datapoints = process(batch)
    commit()
    produce(datapoints)
```

`process` makes use of a status storage. The storage is partitioned the same way as the kafka source, such that each node owns the same log and status partition. This way the nodes can cache the status locally for better performance.

I have the necessity to get an at most once delivery and absolutely avoid duplicates. What I'm gonna do now is:

- extend the BalancedConsumer class to add a pre-rebalance hook
- extend the topic class to return my new BalancedConsumer class
- extend the client class to return my new Topic class
- and change main loop slightly:

```python

rebalance_lock = threading.Lock()
def on_rebalance_start():
    rebalance_lock.acquire()
    flush_status()  # flushes the cache enabling other nodes to get the ownership

consumer.on_rebalance_start(on_rebalance_start)
consumer.on_rebalance_end(lambda: rebalance_lock.release())

while True:
    with rebalance_lock:
         batch = consume_batch()
         ...
```

The lock will let the consumer finish its current batch job before releasing the partition ownership.

I understand this is probably a specific use case still there are some flaws in the current design of pykafka in my opinion:

- subclassing a consumer is not easily supported by the current api (as there is not a `get_custom_consumer` method and I think subclassing all the other involved classes is a complexity that could be avoided)
- when the caller wants to manage the commit manually (by setting auto_commit_enabled to False) probably does not expect an automatic commit in case of rebalance.
- rebalancing cannot be synchronized with the other process threads (the reason why I'm introducing the pre rebalance hook in my subclass)

Probably it should be more explicit in the documentation how to get an at-least-once or at-most-once delivery. The current design doesn't permit any of the two and this wasn't that clear to me without looking at the code. (It is actually also a bit subtle, that's why I've opened this issue, I wasn't sure it was the expected behavior).

**Comment by emmett9001** [comment]
Kafka's semantics guarantee that each message will be consumed at least once - it provides a mechanism (offset tracking) that ensures this. Kafka also has no facilities that allow at-most-once delivery across a consumer group, though we could certainly add example documentation on how to store the additional information necessary to build it oneself. We haven't given any thought to how users can subclass the main classes of pykafka - I suppose the reasoning for this is that they're simple enough that we hope clients won't have to. I agree that having `_rebalance` call `commit_offsets` even when `auto_commit_enabled=False` is an ugly wrinkle, and I'd like to fix it in the future if possible. It sounds like, beyond the ugliness, it's not actually breaking anything for you.

I'm not certain, but it does seem like the existing pre-rebalance callback will satisfy your use case here. If all you need is a hook that will let you call `flush_status` on the set of partitions held by the consumer prior to the rebalance, you can do that in [this callback](https://github.com/Parsely/pykafka/blob/9550e910ad98b1c3b5ba35a637123141fe474bbb/pykafka/balancedconsumer.py#L554). Though it's called `post_rebalance_callback`, it's actually called before the rebalance is finalized (when `self.cns` is reassigned). In this callback, you can get the currently owned set of partitions and their current offsets (that is, the set owned prior to the completion of the rebalance). As far as I can tell from your example, this is the perfect time to call `flush_status`.

You may also want to take a look at https://github.com/Parsely/pykafka/issues/288 and see the use case that @ryan-stateless was dealing with that prompted us to add this callback in the first place. It's the most similar use case to yours that I've come across.
