### ISSUE TITLE
KeyError: 14 from consumer.fetch_offsets()

### ISSUE THREAD

**Issue by jofusa** [Parsely/pykafka#409]
Similar to the issue reported in #401 

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ErrorCodes

Code 14: GroupLoadInProgressCode can be retried. 

Happy to put a pr in for this but want some feed back first.

First is to register a new exception and error callback for that code.
Second, should the consumer.fetch_offsets have a retry.

```py
Traceback (most recent call last):
  File "./kafkaoffsetreporter/reporter.py", line 137, in <module>
    reporter.report_offsets()
  File "./kafkaoffsetreporter/reporter.py", line 126, in report_offsets
    self._report_consumer_groups_offsets(topic_name, consumer_groups)
  File "./kafkaoffsetreporter/reporter.py", line 82, in _report_consumer_groups_offsets
    self._report_consumer_group_offsets(topic_name, consumer_group_name)
  File "./kafkaoffsetreporter/reporter.py", line 86, in _report_consumer_group_offsets
    offset_lags = self.get_latest_offset_for_consumer_group(topic_name, consumer_group_name)
  File "./kafkaoffsetreporter/reporter.py", line 75, in get_latest_offset_for_consumer_group
    consumer_offsets = kafka_tools.fetch_consumer_lag(self.kafka_client, self.kafka_client.topics[to                                                 pic_name], consumer_group_name)
  File "/opt/anaconda/envs/py3/lib/python3.4/site-packages/pykafka/cli/kafka_tools.py", line 55, in                                                  fetch_consumer_lag
    current_offsets = consumer.fetch_offsets()
  File "/opt/anaconda/envs/py3/lib/python3.4/site-packages/pykafka/simpleconsumer.py", line 501, in                                                  fetch_offsets
    partitions_by_id=self._partitions_by_id)
  File "/opt/anaconda/envs/py3/lib/python3.4/site-packages/pykafka/utils/error_handlers.py", line 50                                                 , in handle_partition_responses
    error_handlers[errcode](parts)
KeyError: 14
```

**Comment by emmett9001** [comment]
@jofusa Thanks for filing this. I assume this is happening with Kafka 0.9, since it's a new error code. If that's the case, are you trying to use the new managed consumer groups with the current version of pykafka? I'm not sure how far you'd get - I also don't know how else this error would appear.
That said, if you'd like to open a pull request for this particular error code, please feel free. I think this error should be responded to with a retry in `fetch_offsets` - there's existing retry code there that you can hook into.

**Comment by jofusa** [comment]
I don't know if it's new. We are running kafka 0.8.2.1 only. This is a simple little monitoring app that only uses the kafka_tools.py to periodically query topics and specific consumer groups feeds into our metrics service.

will submit a pr to fix.

From the docs
```
The broker returns this error code for an offset fetch request if it is still loading offsets (after a leader change for that offsets topic partition), or in response to group membership requests (such as heartbeats) when group metadata is being loaded by the coordinator.
```
So this just means the offset broker is busy. This error has been happening on a test cluster which has been going through failure scenarios and restarts a lot, so could be one reason.

**Comment by emmett9001** [comment]
My mistake, I was working from memory and didn't check the docs. Apparently they've [changed](https://github.com/Parsely/pykafka/blob/master/pykafka/exceptions.py#L147) the official meaning of error code 14.

**Comment by jofusa** [comment]
interesting, should i change the exception name in the pr to the new one?

GroupLoadInProgressCode

**Comment by emmett9001** [comment]
Yes, we try to keep those up to date with the protocol documentation (which until a few weeks ago was quite easy :smile:)
