### ISSUE TITLE
message.value is None, stability and other possible problems

### ISSUE THREAD

**Issue by tigran-a** [Parsely/pykafka#419]
Hi, 

These are some problems that we meet using pykafka consumer. Even though, there are some other tools in the chain, I have a feeling that the reason is in pykafka (using the 2.1.2 release). No proofs, unfortunately, this is just for the record. 

### m.value is None
Sometimes, when I do  m= message.cosume(), the m.value is None, while None is never posted to kafka. 
Related thing: we have several consumers (with different consumer group) in parallel on the topic. One started to get None values (because it tried to parse the m.value), the other forwarded the messages (no matter its content) via bruce to another kafka, and the (pykafka) consumer there did not say anything about None messages (at least, it seems so). 

### Failed to acquire partition
We have two consumers running from the one consumer group, treating each two partitions 

One of them got  stuck for some reasons, and the other could not acquire partitions for ~12 hours, 
the code was trying to recreate consumer with 1 seconds delay, but every time got this error:
```
16-01-17 02:45:20,633 - pykafka.balancedconsumer - WARNING - Failed to acquire partition <pykafka.partition.Partition at 0x7f1dd195abd0 (id=2)> after 4 retries.
2016-01-17 02:45:20,634 - pykafka.balancedconsumer - ERROR - Stopping consumer in response to error
2016-01-17 02:45:20,642 - kafkarecon.kafkarecon - ERROR - Got an exception! ConsumerStoppedException()
Traceback (most recent call last):
  File "/usr/local/kafka2aero/kafkarecon/kafkarecon.py", line 98, in start
    m = self.consumer.consume()
  File "/usr/local/lib/python2.7/dist-packages/pykafka/balancedconsumer.py", line 694, in consume
    raise ConsumerStoppedException
ConsumerStoppedException
```
thus, downtime for 12h.

### repeated message reception

We have such a dataflow   php -> bruce (kafka producer daemon) -> kafka -> pykafka balacned consumer -> bruce -> kafka (another one) -> pykafka balanced consumer -> mysql. 

php puts json messages with unique values in field id.  Never None (see the first issue). So, at the end, last pykafka consumer receives (rarely, but it does) repeated messages, thus, getting duplicate on primary key exception with mysql.  I logged the values, so it's really repeated message   kafka->mysql script tries to put in mysql. Here you could blame any of the tools (and arrows) in the chain, but I think it can be related to pykafka.

Any enlightenments or guesses are welcome

Thanks

**Comment by emmett9001** [comment]
@tigran-a If you don't want `consume()` to return `None`, you can try using `consume(block=True)` in combination with `get_balanced_consumer(consumer_timeout_ms=-1)`. This will cause it to block indefinitely until it has a non-`None` message to return.

I'd need some more context to properly diagnose the second issue. The consumer group somehow got into a state where two consumers wanted the same partition at the same time. I imagine this is a bit more likely to happen if you're using a consumer group with a number of participants equal to the number of partitions on your topic, as you say you're doing.

As for the duplicated messages, neither Kafka nor PyKafka make any guarantees about exactly-once delivery in balanced consumer groups, and we've seen in many cases that duplicate message delivery is possible as a result of partition rebalancing. You can check out what @ryan-stateless was doing in [this issue](https://github.com/Parsely/pykafka/issues/288) to serve a use case that sounds similar to yours.

**Comment by tigran-a** [comment]
@emmett9001, consume did not return `None`, it returned a message object whose value (value attribute) is `None`. 

about the second issue, I had 4 partitions and two consumers in one group

Concerning the third issue, if I don't have coming and leaving consumers in the group, but they work in parallel without going down and coming back, the delivery should be not duplicated, right?

Thanks

**Comment by emmett9001** [comment]
It looks like the only place the message's `value` attribute is set is [here](https://github.com/Parsely/pykafka/blob/9ee2acf957cec4780c8e7a87c38389718de91a47/pykafka/protocol.py#L202) - immediately after it's decoded from a `MessageSet` response. PyKafka isn't doing anything to the contents of this field. Maybe you can verify that you're not producing any `None` or `null` messages?

In general a stable consumer group should not duplicate any messages, but rebalances can be triggered by other events in zookeeper, including a partition leader changing.

**Comment by jofusa** [comment]
If they are using the rdkafka consumer it could be [here](https://github.com/Parsely/pykafka/blob/9ee2acf957cec4780c8e7a87c38389718de91a47/pykafka/rdkafka/_rd_kafkamodule.c#L970)

**Comment by tigran-a** [comment]
No, we don't have librdkafka installed. But I think I should try

**Comment by emmett9001** [comment]
@tigran-a I'm going to close out this issue for now, since there's not enough specific information pointing to possible pykafka bugs. The one I'm most concerned about is the `None` message value, but it's not at all clear how to replicate that issue. If you can provide more specific information on any of these issues, please comment here or reopen the ticket. Thanks!
