### ISSUE TITLE
RdKafkaProducer ignores block_on_queue_full=True

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#425]

**Comment by emmett9001** [comment]
@yungchin Can you provide any additional details on this ticket that would make it easier for other folks less familiar with rdkafka to contribute?

**Comment by yungchin** [comment]
Sorry I meant to look into this one sooner. It's actually just a silly omission in `RdKafkaProducer`: the `block_on_queue_full` setting isn't hooked up to anything in that class.

Now, librdkafka doesn't have a "block on queue full" option, so the best we can do is catch the `ProducerQueueFullError` when it's raised from [the call into the C extension][0], and retry (after, I guess, a `sleep()` - does that sound too ugly @emmett9001 ?).

I'm also wondering if we care that that causes slightly different semantics: with the python producer, if you `produce()` from one thread, and it blocks on a full queue, and in the mean time you `produce()` from another thread, those two messages would still get queued in-order (if my quick re-reading of `_wait_for_slot_available()` isn't mistaken). But if we'd implement that try-except-sleep-retry for the rdkafka producer, that scenario might see the two messages reordered when the first call is stuck in `sleep()`.

[0]: https://github.com/Parsely/pykafka/blob/c7755cbf88a608f44e66acc20a26f60daf07da3c/pykafka/rdkafka/producer.py#L73

**Comment by hadsed-genapsys** [comment]
+1

In the meantime, perhaps we can update the documentation to make this limitation clear?

**Comment by hadsed** [comment]
+1

Would it be helpful to temporarily add in the producer documentation that this option doesn't work with rdkafka? Or perhaps raise an exception or something in the constructor.

**Comment by emmett9001** [comment]
@yungchin I'm not terribly worried about that difference in semantics, since we don't guarantee anything about message ordering anyway. Your solution sounds reasonable. @hadsed if you'd like to add an interim exception to the producer constructor, please feel free to open a pull request.

**Comment by yungchin** [comment]
The nasty thing is, it would still potentially reorder messages even if you set `max_retries=0` (which I would expect to guarantee ordering). In practice, I only ever hit a queue-full when really hammering the producer (in benchmarking), so it might be reasonable to leave it at raising a NotImplementedError from the constructor, for now.

**Comment by emmett9001** [comment]
I agree. @hadsed If you'd like to add a `NotImplementedError` to `Producer.__init__`, please go ahead.
