### ISSUE TITLE
Amount of messages in partition ? how to make  earliest_available_offset  works

### ISSUE THREAD

**Issue by Kaydannik** [Parsely/pykafka#427]
Hello, 
I need to figure out amount of messages in partition.

And i cannot do it, because weakref somehow already dead.
Any advices how can i get it ? 

```python
topic='test'
kafkaclient = KafkaClient('somekafka:9092')
partitions = kafkaclient.topics[topic].partitions
for partition in partitions:
    print partition._topic #<weakref at 0x7f74242a4998; dead>
    #print partition.earliest_available_offset()
    #print partition.latest_available_offset()
```

Thanks!

**Comment by yungchin** [comment]
Hi, thanks for raising this question. The trick is to keep a direct reference to the `Topic` instance, like so:

```python
topic = client.topics["test"]
for partition in topic.partitions:
    # etc
```
I'll leave this open for now, with a note to self to update a docstring somewhere.
