### ISSUE TITLE
Simple consumer Fails as it cannot find _rd_kafka python module

### ISSUE THREAD

**Issue by jcontreras000** [Parsely/pykafka#437]
I'm trying to start s simple_consumer, and it complains about it cannot find _rd_kafka.
```pykafka/rdkafka/simple_consumer.py", line 8, in <module>
    from . import _rd_kafka
ImportError: cannot import name _rd_kafka```
If simple_consumer.py tries to import _rd_kafka from local, shouldn't  _rd_kafka be there?

Thanks!

**Comment by jcontreras000** [comment]
I think that pykafka 2.2.0 failed on building the _rd_kafkamodule.c extension.  This may be caused for the either for the absence of the librdkafka/rdkafka.h header or any other issue compiling the extension.
I cloned the repo on my local (i'm on linux trusty), and i had 2 issues installing pykafka (setup.py install).

1. Missing librdkafka/rdkafka.h (i installed librdkafka-dev headers and problem solved)
2. `ykafka/rdkafka/_rd_kafkamodule.c:949:19: warning: assignment makes pointer from integer without a cast [enabled by default]
         rkmessage = rd_kafka_consume_queue(self->rdk_queue_handle, timeout_ms);
                   ^
---------------
INFO: Failed to build rdkafka extension:
command 'x86_64-linux-gnu-gcc' failed with exit status 1
INFO: will now attempt setup without extension.
---------------`

**Comment by jofusa** [comment]
Make sure you have librdkafka installed. Otherwise the c extension will not
build

**Comment by jcontreras000** [comment]
I've installed librdkafka1 , librdkafka-dev and also cloned and compile a librdkafka project (https://github.com/edenhill/librdkafka) and still the same error.. Any other idea?

Thanks!

**Comment by yungchin** [comment]
This is one of those things that are really nasty to debug with distutils builds - I suppose it doesn't offer up any other meaningful details, beyond "failed with exit status 1"?

Peeking at https://packages.debian.org/sid/librdkafka-dev it occurs to me that some dependencies may be missing: do you have `libc6-dev` (which provides pthread headers, and it's usually installed with `build-essential`), and - if that didn't do it - `zlib1g-dev`?

Thanks

**Comment by emmett9001** [comment]
I don't see signs that this is a widespread issue - it seems likely to be a missing dependency. If that turns out not to be the case and there's something that needs to be changed in pykafka's setup logic, please comment or reopen this issue.

**Comment by willangenent** [comment]
I am having this issue too and it's not an error, but still a unnecessarily fear inducing warning. Either way I will have to work around this since I don't want to be staring at this every time I start my app.

Thanks

**Comment by KaizerSchloss** [comment]
I'm having the same issue. I think the problem is not having librdfafka installed _before_ pip installing pykafka causes the file '_rd_kafka.so' not to compile, hence the import error.

Re-pip-installing pykafka with librdkafka present fixed this for me.

**Comment by emmett9001** [comment]
Thanks for the tip @KaizerSchloss!

**Comment by zhipcui** [comment]
Save my life @KaizerSchloss

**Comment by sumeetsarkar** [comment]
I faced this problem recently. I was getting the below error:

`raise ImportError("use_rdkafka requires rdkafka to be installed")`

My setup when I was facing the problem was:

_(The order below is important for this to work, what I believed and ideally it should work, for me it did not)_

```
brew install librdkafka
pip install pykafka
```

**Note:** Even using LD_LIBRARY_PATH with correct path for librdkafka lib it did not work.

**Solution**

```
# Uninstall pykafka if installed in your env
pip uninstall pykafka

# Clone pykafka in your project
git clone git@github.com:Parsely/pykafka.git && cd pykafka

# Build rdkafka
python setup.py develop

# Test if rdkafka is available
python -c "from pykafka import rdkafka"
```

If all steps above are followed well, `from pykafka import rdkafka` works without any errors
