### ISSUE TITLE
Unable to Send and Receive Messages at High Rates

### ISSUE THREAD

**Issue by furlongmt** [Parsely/pykafka#443]
Hi,

I'm attempting to use pykafka in a "ballplate" simulation, and for this messages are being published/consumed at a rate of every .02 seconds. I consistently get a consumer timeout when trying to read messages, even if I set the timeout to 1500ms. Has anyone else had similar issues?

Thanks

**Comment by emmett9001** [comment]
@furlongmt Thanks for posting this! Can you clarify what you mean by "consumer timeout", maybe by posting a traceback and example code that indicate the failure case you're seeing?

**Comment by furlongmt** [comment]
Hi, 

The basic premise is that a controller class will run and publish a message to the model, and then the model should read this message, be interpreted (a custom interpret function for the data), and then send back the interpreted data. I know that the interpret function is not an issue because I have I used this module for multiple other simulations with different pub/sub protocols. 

I would like to be able to consume and publish messages every .02 seconds.

So here is some example code for the my kafka controller (I have put a comment in where it hangs when trying to consume messages very quickly):

kafka,producer,consumer = None,None,None
control_action = "control_action" 
plant_state = "plant_state"
plant_group = "plant_group"

def initialize_handshake(HOST, PORT):    # setup socket and start the connection to the model
    global kafka,producer,consumer
    timeout = 150
    server = HOST+":"+str(PORT)
    
    kafka = KafkaClient(server)
    
    producer_topic = kafka.topics[control_action]
    consumer_topic = kafka.topics[plant_state]

    producer = producer_topic.get_producer()
    #producer.produce('/state?&]')
    #producer.produce('control_action')

    consumer = consumer_topic.get_simple_consumer(consumer_timeout_ms=timeout, consumer_group=plant_group, auto_commit_enable=True, auto_offset_reset=OffsetType.LATEST, reset_offset_on_start=True)
    print "Client's Consumer and SimpleProducer successfully connected..."

def process(HOST, PORT, GET,client_socketport=None):
    global producer,consumer
    try:
    	response = consumer.consume().value #Hangs here
    	print response
    	producer.produce(GET + "&]")
        data = response.split("]")
        response = data[len(data) - 2];
    except Exception, err:
        print("[Warning] in kafka client send and receive :%s\n " % err)
        print GET
        response = (GET.split("time=")[1]).split("&")[0]
    return response

And here is example code for the model file:

kafka,producer,consumer = None,None,None
control_action = "control_action" 
plant_state = "plant_state"
control_group = "control_group"

def initialize_handshake(HOST, PORT):    # setup socket and start the connection to the model
    global kafka,producer,consumer
    timeout = 150
    server = HOST+":"+str(PORT)

    kafka = KafkaClient(hosts=server)
    
    producer_topic = kafka.topics[plant_state]
    consumer_topic = kafka.topics[control_action]

    producer = producer_topic.get_producer()
    
    consumer = consumer_topic.get_simple_consumer(consumer_timeout_ms=timeout, consumer_group=control_group, auto_commit_enable=True, auto_offset_reset=OffsetType.LATEST, reset_offset_on_start=True)
    print "Model's Consumer and SimpleProducer successfully connected..."


  #  read from the consumer

def read_from_consumer():
	try:
		response = consumer.consume().value #Hangs here
		print response
		write_to_producer(response)  
	except:
		pass;

 #   write to the producer
def write_to_producer(msg):
	producer.produce(interpret(msg))

if __name__ == '__main__':
	#connect to a local broker on my machine
	initialize_handshake("localhost", 9092)

	try:
		while 1:
			time = clock()
			while clock() < time + h*.997245:
				read_from_consumer()
			updateState("_", "_")
	except (KeyboardInterrupt, SystemExit):
		print exc_info()
		producer.stop()
		consumer.stop()
		print "Shutting down service"

Let me know if anything wasn't clear or if you would like more information!

Thanks a lot,
Matthew Furlong

**Comment by yungchin** [comment]
@furlongmt for this application, where you call `get_producer()` you probably want to pass it a very low value for `linger_ms`. The default is 5 seconds, meaning that it waits for more messages to produce for all that time, before it batches them into a message set.

You might even be better off with a sync producer (ie `sync=True`), although I'm not sure if that would manage to produce at the rate you need.

**Comment by emmett9001** [comment]
@furlongmt It does seem like you might be better off with a [non-blocking `consume()`](https://github.com/Parsely/pykafka/blob/master/pykafka/simpleconsumer.py#L367) and tuned values for `linger_ms` and `min_queued_messages` on the producer. Tuning these attributes to the appropriate values will allow you more granular control over when individual messages are sent from the producer. See the [documentation](http://pykafka.readthedocs.org/en/latest/api/producer.html#pykafka.producer.Producer) for more information.
