### ISSUE TITLE
Getting latest available offset fails sporadically

### ISSUE THREAD

**Issue by cscheffler** [Parsely/pykafka#455]
Calling the `latest_available_offset()` method on a partition fails sporadically with this trace output:

    Traceback (most recent call last):
      File "/usr/local/tal/tal/venv/lib/python2.7/site-packages/tal_kafka/scripts/consumer_group_lag.py", line 100, in get_consumer_lag
        topic_offset = pykafka_topic.partitions[partition].latest_available_offset()
      File "/usr/local/tal/tal/venv/lib/python2.7/site-packages/pykafka/partition.py", line 111, in latest_available_offset
        return self.fetch_offset_limit(OffsetType.LATEST)[0]
    IndexError: list index out of range

This is in a script that runs once a minute or so, and this exception occurs infrequently, pointing to some transient issue with broker state perhaps.

As a workaround, I have wrapped the `latest_available_offset()` call in a retry loop. I'll post more information here if I notice anything helpful in the logs.

This is with pykafka 2.1.2, but looking at the latest code on the master branch, the code for this call seems unchanged.

**Comment by emmett9001** [comment]
Thanks for the clear report @cscheffler. This looks like one that we can catch and retry or warn about.
