### ISSUE TITLE
Possible race condition when "re-producing queued messages after update"

### ISSUE THREAD

**Issue by gg7** [Parsely/pykafka#458]
Setup:
* OS: Ubuntu 14.04 (x86_64)
* Kafka: 2.11-0.9.0.0 (2 brokers)
* Zookeeper: 3.4.6 (3 servers)
* Python: 2.7.6
* `pip freeze`:
```
decorator==4.0.9
gevent==1.1b6
greenlet==0.4.9
ipython==4.1.1
ipython-genutils==0.1.0
kazoo==2.2.1
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.6
ptyprocess==0.5.1
-e git+https://github.com/Parsely/pykafka@03b0434c34ffbe0a3805b4ccc811de6e05aaa9a9#egg=pykafka
python-snappy==0.5
simplegeneric==0.8.1
six==1.10.0
tabulate==0.7.5
traitlets==4.1.0
virtualenv==14.0.6
```
* `kafka-topics.sh --describe`
```
Topic:pykafka   PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: pykafka  Partition: 0    Leader: 0       Replicas: 0,1   Isr: 1,0
        Topic: pykafka  Partition: 1    Leader: 1       Replicas: 1,0   Isr: 1,0
```

Code & output: https://gist.github.com/gg7/47e3551bf8cb718bd4d6

On [lines 126-128](https://gist.github.com/gg7/47e3551bf8cb718bd4d6#file-stderr-txt-L126-L128) you can see two threads writing to the same partition. The last message batch created is actually the first one to be sent after recovery.

Apologies if this is yet another duplicate.

**Comment by yungchin** [comment]
Thanks for raising this @gg7 

> The last message batch created is actually the first one to be sent after recovery.

If I understand the point correctly, it would be very difficult to prevent that scenario in general - the second batch would often already be in flight (ie pushed to the connection handler thread) at the point where we discover the first batch had errors (not perhaps in the specific example above - but there are other failures, where we do get a response from the broker, and we'd only unpack the response while the next batch was already going out).

We could perhaps be more explicit in the documentation, in stating that if your application cannot afford any reordering of produced messages at all, you should disable retries, or use sync mode.

**Comment by gg7** [comment]
> not perhaps in the specific example above - but there are other failures, where we do get a response from the broker, and we'd only unpack the response while the next batch was already going out

I'm aware that preserving ordering 100% of the time with the async producer + retries is impossible. Quoting Kafka's documentation for the `retries` producer property:

> Setting a value greater than zero will cause the client to resend any record whose send fails with a potentially transient error. Note that this retry is no different than if the client resent the record upon receiving the error. Allowing retries will potentially change the ordering of records because if two records are sent to a single partition, and the first fails and is retried but the second succeeds, then the second record may appear first.

In my test case I was hoping that after pykafka re-establishes a connection to the broker it'd retry the failed messages sets in their original order. This is an edge case and perhaps it's not worth fixing, but I decided to report it anyway.

**Comment by emmett9001** [comment]
Possibly related to #457

**Comment by emmett9001** [comment]
I [updated the documentation](https://github.com/Parsely/pykafka/commit/8333c72f526a5a8dfdf6e353b970fb69d1dc341a) to be clearer on this. The use of a [dictionary](https://github.com/Parsely/pykafka/blob/master/pykafka/producer.py#L220) for the message retries seems to be the root reason for this lack of perfect ordering. Fixing it would require keeping a total ordering of messages across `OwnedBroker` instances. This is doable but I don't think it's worth the change for an edge case like this that's not part of Kafka's official semantics.

@gg7 Thanks for the information, and please let me know if I've misunderstood some part of your report.
