### ISSUE TITLE
Retry_backoff_ms inconsistent between rdkafka and pure python

### ISSUE THREAD

**Issue by jonsource** [Parsely/pykafka#468]
The behaviour of retry_backoff_ms varies greatly between using rdkafka and not. While using rdkafka it equals the time spent between attempting a new re-send, but when not using rdkafka - the time it takes to resend previously failed messages seems to depend also on linger_time_ms and possibly socket_timeout_ms and the internal timeout time.sleep(i) in Broker.request_metadata() on broker.py:280

**PyKafka version**: 2.2.0, latest
**Kafka version**: 0.9.0.0

**Comment by emmett9001** [comment]
I'm not actually convinced this is worth fixing. The rdkafka and pure python producers are different enough internally that it probably doesn't make a ton of sense to force their implementation details to be so closely tied. Maybe a note in the docstring for `retry_backoff_ms` explaining the factors involved is the proper solution here? Thoughts welcome from anyone.
