### ISSUE TITLE
Improve protocol tests

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#475]
The protocol unit tests currently include huge [copypasted bytestrings](https://github.com/Parsely/pykafka/blob/79e8938f55484e4c892744ec203e98998c2f7f2d/tests/pykafka/test_protocol.py#L248) that are hard to make changes to or reason about. To make these tests easier to read and write, we can make a utility that can turn this

```python
"""
00 00 00 00 00 01 00
dummytopic
00 00 00 0c
testuserdata
"""
```

into this:

```python
bytearray(b'\x00\x00\x00\x00\x00\x01\x00\ndummytopic\x00\x00\x00\x0ctestuserdata')
```
In other words, the utility trims whitespace and converts `\b\d\d\b` to the hex equivalent. This kind of utility pays off quickly for writing tests when developing protocol drivers.

**Comment by giulianob** [comment]
What's the rule around the newlines? There's a newline in the bytearray example but it only seems to happen once, whereas the string has many newlines, so I'm wondering how to handle it.

**Comment by emmett9001** [comment]
@giulianob The example in the beginning of this issue breaks up these bytestrings into the parts denoted in the [protocol documentation](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-MetadataAPI). The newline you see in the `bytearray` example isn't actually a newline, it's just some byte sequence representing the length of the string `dummytopic` that happens to also be the ascii code for `\n` (the number 10 represented as a bytestring).

Instead of writing a utility, this change can actually be as simple as taking a test that looks like this
```python
bytearray(b'\x00\x00\x00\x00\x00\x01\x00\ndummytopic\x00\x00\x00\x0ctestuserdata')
```
and reformatting it as this
```python
bytearray(b'\x00\x00'  # version
                b'\x00\x00\x00\x01'  # len(topic names)
                b'\x00\n'  # len(topic name)
                b'dummytopic'  # topic name
                b'\x00\x00\x00\x0c'  # len(user data)
                b'testuserdata')  # user data
```
by using this specification as a reference:
```
ProtocolMetadata => Version Subscription UserData
  Version => int16
  Subscription => [Topic]
    Topic => string
  UserData => bytes
```

**Comment by giulianob** [comment]
Ok makes sense. I guess it would make more sense to write it as \x10 instead of a newline. So do you guys just want to format it and not have this utility? It's a bit more readable as a single string with standard hex formatting but its not native Python.

**Comment by emmett9001** [comment]
I'm in agreement with @rduplain [here](https://github.com/Parsely/pykafka/pull/416#discussion_r54684902) that we should stick with python-formatted bytestrings. Also, the `\n` is formatted as such because it was copypasted directly from a `str(repr(msg))` in pdb. If formatting it as `\x10` would work here (which I assume it would), that's certainly preferable for readability.

@giulianob If you'd like to work on a pull request for this, it would be pretty straightforward to get merged quickly.

**Comment by emmett9001** [comment]
@giulianob I'm going to grab this since I haven't heard anything here.

**Comment by giulianob** [comment]
Sorry about that. Have been working on some other things.

**Comment by rduplain** [comment]
Thanks a bunch for jumping in, @giulianob!
