### ISSUE TITLE
Make delivery report threadlocal by default, but switchable

### ISSUE THREAD

**Issue by jofusa** [Parsely/pykafka#483]
The explanation for why the delivery_report queue is thread local make sense: 

https://github.com/Parsely/pykafka/pull/344#issuecomment-157762655

However I have a use case where i would like a centralize handler of delivery exceptions. That is many "producers" and one background thread monitor the delivery_report queue. If you guys know of a way to accomplish this given the current implementation, please let know and this change might be unneeded.

What are thoughts on allowing the delivery_report to optionally be a global queue. (something like `delivery_report_queue_thread_local` defaults True.) There is an obvious tradeoff between api complexity and flexibility.

**Comment by emmett9001** [comment]
Hi @jofusa. I think this is a reasonable idea, but I'm wary of making the api more complicated than it truly needs to be. Whether or not this is a case that warrants the additional complexity isn't clear to me right now.

The solution I suggested [earlier](https://github.com/Parsely/pykafka/pull/480#issuecomment-192430118) still looks like it could work. Your application can maintain a global queue. Then, for each thread you have calling `produce()`, you can have it call `get_delivery_report()` and put the result into your application's global queue. Your application can then spawn another thread that reads from this queue and performs error handling based on the delivery reports it emits.

If you tried this solution and found real problems with it that I'm not thinking of at the moment, it would make a strong case for making the internal queue switchable between local and global. If not, we could actually add code based on your example to the documentation as a standard way to do global error handling.

**Comment by yungchin** [comment]
What if the API change amounts to this: in addition to the current `True` and `False` options, we allow `delivery_reports` to accept a custom class that implements [][0]

**Comment by jofusa** [comment]
I like the callback mechanism discussed in #506 over a switchable queue. (as long as it also reported failures). I think i would work in my case better.

**Comment by emmett9001** [comment]
Closing in favor of #506
