### ISSUE TITLE
Producer worker thread dies but exception never raised

### ISSUE THREAD

**Issue by andrewkcarter** [Parsely/pykafka#496]
When the producer is setup with `block_on_queue_full=False` and the connection to the broker is lost, if the queue hits capacity the `ProducerQueueFullError` is raised causing the queue reader worker thread to terminate.

The exception is correctly assigned to the `_worker_exception` variable: https://github.com/Parsely/pykafka/blob/master/pykafka/producer.py#L494

... but `_raise_worker_exceptions()` is never called during the normal flow of producing a message when `sync=False`. The application must manually call into `producer._raise_worker_exceptions() before sending a message to detect if the producer is still actually functioning.

I see two obvious solutions, one would be to call `producer._raise_worker_exceptions()` within `producer.produce()` even when `sync=False`. The second would be to set `producer._running=False` when the worker thread terminates which would lead to a `ProducerStoppedException`. Both of these notify the application of the underlying failure so that the producer can be restarted.

When the producer is configured with `sync=True`, it appears that the exception would be properly raised by looking at the code. But I didn't test this.

**PyKafka version**: 2.2.1
**Kafka version**: 0.9.0.0

**Comment by emmett9001** [comment]
Thanks @andrewkcarter, I believe this is just an oversight from [this commit](https://github.com/Parsely/pykafka/commit/201683ffab9715c9c72a5e43dd5ef57e65e69e01). Calling `_raise_worker_exceptions()` regardless of the value of `sync` is the correct solution here.
