### ISSUE TITLE
Kafka community is introducing a means of detecting protocol version

### ISSUE THREAD

**Issue by amontalenti** [Parsely/pykafka#505]
See this wiki page:

https://cwiki.apache.org/confluence/display/KAFKA/KIP-35+-+Retrieving+protocol+version

May be a good idea to have pykafka support this. There is also a call for comment over on that issue.

**Comment by emmett9001** [comment]
I don't have any comments, but I voted on the JIRA issue.

**Comment by emmett9001** [comment]
This is now tracked in #526
