### ISSUE TITLE
pypy snappy compression seg fault on larger messages

### ISSUE THREAD

**Issue by jofusa** [Parsely/pykafka#508]
This is a carry over from #480. It is also an upstream python snappy issue but we should track it some how.

So any byte array above a certain size causes a seg fault.

```
(pypy) ➜ cat s.py
from uuid import uuid4
import snappy

payload = b''.join([uuid4().bytes for i in range(10)])

c = snappy.compress(payload)
assert snappy.decompress(c) == payload
(pypy) ➜  python s.py
[1]    4587 segmentation fault (core dumped)  python s.py
(pypy) ➜  python
Python 2.7.10 (bbd45126bc69, Mar 18 2016, 21:35:08)
[PyPy 5.0.1 with GCC 4.8.4] on linux2
```

while

```
from uuid import uuid4
import snappy

payload = b''.join([uuid4().bytes for i in range(5)])

c = snappy.compress(payload)
assert snappy.decompress(c) == payload
```
passes

Perhaps a warning doc for pypy users.

**Comment by emmett9001** [comment]
We could also use some tests for this case in `test_compression.py`.

**Comment by jofusa** [comment]
woh python-snappy could use some love. last code commit was three years ago and there is no CI hooked up.

**Comment by jofusa** [comment]
from googling.

https://github.com/rjpower/ctypes-snappy
