### ISSUE TITLE
Does the latest PyKafka support SSL connection to latest Kafka broker server?

### ISSUE THREAD

**Issue by zhanghan987** [Parsely/pykafka#509]
Just as the title, thanks!

**Comment by emmett9001** [comment]
@yungchin is currently working on SSL support - we don't have it yet, but we will soon. See [this thread](https://github.com/Parsely/pykafka/issues/349) for updates on SSL/TLS support.

**Comment by emmett9001** [comment]
See also https://github.com/Parsely/pykafka/pull/477

**Comment by zhanghan987** [comment]
Thanks! Looking forward to it.
