### ISSUE TITLE
Pykafka's behavior when kafka server is down

### ISSUE THREAD

**Issue by zhanghan987** [Parsely/pykafka#511]
Hi,
    I am a little confused about the producer and consumer's different behavior when kafka server is down. The producer will keep working but consumer will be crashed by some 'connect confused' exception. And because consumer has it's own worker thread, I can't catch the exception in my main thread.
    How do I keep consumer working after kafka server down like the the producer?

**Comment by emmett9001** [comment]
Hi @zhanghan987, thanks for filing this. The consumer [should](https://github.com/Parsely/pykafka/blob/3afa9a9b628bcd366ab2900b386cff907cff20e5/pykafka/simpleconsumer.py#L408) raise any errors it encounters to the main thread, so it's interesting to hear that it's not doing that in some cases. Do you have a traceback indicating the specific error you're seeing?

**Comment by zhanghan987** [comment]
Hi, 
    I try it today and it seems the exception could be catch now, I can't reproduction it today.
    One more question, the consumer I used can not reconnect by itself after kafka server restarted. Now I  plan to use this steps to reconnect it:
    client.update_cluster()
    consumer.stop()
    consumer.start()
It works now, but how could I detect when consumer lost connection to broker? By the exception? Thanks for your so fast reply!

**Comment by emmett9001** [comment]
Yes, when the consumer loses its connection it will eventually raise `SocketDisconnectedError`, which you can catch.
