### ISSUE TITLE
Kafka Topic Namespaces

### ISSUE THREAD

**Issue by brianbruggeman** [Parsely/pykafka#523]
I was looking for a kafka topic namespace (see: [KIP-37](https://cwiki.apache.org/confluence/display/KAFKA/KIP-37+-+Add+Namespaces+to+Kafka)) feature, and I didn't see this available within the [Topic protocol] (https://github.com/Parsely/pykafka/blob/master/pykafka/protocol.py#L400) code.

Am I missing the feature or is this something that still needs to be created?

**Comment by jofusa** [comment]
I'm not sure that KIP has been implemented. It might just be a proposal. First I've heard of it.

**Comment by emmett9001** [comment]
Yeah, looks like it's still "Under Discussion". If this does end up getting added it will definitely be on our roadmap to support it. I'll close this issue until that happens.
