### ISSUE TITLE
relax gevent requirement

### ISSUE THREAD

**Issue by jianbin-wei** [Parsely/pykafka#525]
Is it possible to relax the gevent version requirements?  Right now it asks for gevent 1.1.0.  We cannot use latest gevent, which is 1.1.1.   Something as 1.1.0 ~ 2.0 would be better.

**Comment by emmett9001** [comment]
Pykafka does take advantage of bugfixes introduced in gevent `1.1`, but I don't think it cares about the `1.1.x` bugfix version. I'll try testing out a branch that relaxes the requirement.

**Comment by jianbin-netskope** [comment]
The reason is because pykafka asks for gevent 1.1.0 only.  If I have gevent 1.1.1 installed, pykafka would uninstall gevent 1.1.1.

**Comment by emmett9001** [comment]
@jianbin-wei I've made the dependency more specific in #529. Let me know if this works for you.

**Comment by jianbin-wei** [comment]
I think I am asking is to relax the dependency.  Do I miss something?

**Comment by emmett9001** [comment]
Sorry, looks like I misunderstood what you were asking. I've changed the dependency to `>=1.1.0`

**Comment by jianbin-wei** [comment]
thanks.
