### ISSUE TITLE
Kafka 0.10.0 Release Plan

### ISSUE THREAD

**Issue by johnistan** [Parsely/pykafka#526]
The 0.10.0 release is scheduled to be cut on April 22, 2016. 

https://cwiki.apache.org/confluence/display/KAFKA/Release+Plan+0.10.0

Here are some changes we should be tracking:
- KIP-32 Add timestamp to message (committed upstream)
  - [KIP](https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message)
  - [Issue](https://issues.apache.org/jira/browse/KAFKA-2511)
- KIP-35 - Retrieving protocol version (in flux)
  - [KIP](https://cwiki.apache.org/confluence/display/KAFKA/KIP-35+-+Retrieving+protocol+version)
  - [Issue](https://issues.apache.org/jira/browse/KAFKA-3304)

**Comment by emmett9001** [comment]
Thanks for centralizing this information, @jofusa - it's really helpful.

**Comment by jianbin-wei** [comment]
how about stream?

**Comment by emmett9001** [comment]
There are currently no plans for pykafka to support Kafka Streams

**Comment by emmett9001** [comment]
See the [`MessageSet v1`](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets) documentation for info about message timestamps.

KIP-35 is apparently going into `0.10.1.0`

**Comment by emmett9001** [comment]
Relevant to 0.10 message format support https://github.com/Parsely/pykafka/issues/644

**Comment by emmett9001** [comment]
https://github.com/Parsely/pykafka/pull/685 merged, master now supports message timestamps.
