### ISSUE TITLE
producer in a thread blocking forever

### ISSUE THREAD

**Issue by leikuang** [Parsely/pykafka#534]
The first code sample works, but the second sample does not. Please help.
**pykafka-2.3.0**
**python2.7**

First sample:
```python
producer = KafkaClient(hosts=kafka_server).topics[topic].get_sync_producer()
print 'start testing' # printed out
producer.produce('test 1') # seen in Kafka
print 'finish testing' # printed out
```

Second sample:
```python
producer = KafkaClient(hosts=kafka_server).topics[topic].get_sync_producer()
class Test(Process):
    def __init__(self, producer):
        self.producer = producer
    def run(self):
        print 'start testing' # printed out
        self.producer.produce('test 2') # not seen in Kafka
        print 'finish testing' # never printed out
test = Test(producer)
test.start()
```

**Comment by yungchin** [comment]
I assume that's a `multiprocessing.Process`? You need to instantiate the `KafkaClient` (and the `Producer`) in the same process from which you're producing. The client maintains communication threads which are not reachable from the other process.

**Comment by leikuang** [comment]
Thanks a lot

_______________________________________
Lei Kuang, Ph.D.
Business Analytics & Mathematical Sciences
IBM T.J. Watson Research Center
914.945.1071
