### ISSUE TITLE
Rdkafka cannot accept message sizes larger than default

### ISSUE THREAD

**Issue by hadsed-genapsys** [Parsely/pykafka#536]
Hi,

There's a bug in the Rdkafka producer code.

First, I configure my broker to accept large messages (with all the proper configs, including message.max.bytes, fetch.message.max.bytes, replica.fetch.max.bytes, socket.send.buffer.bytes, and socket.receive.buffer.bytes). Then I setup an Rdkafka producer and try to send large messages but this fails because the option `max_request_size` does not exist for the Rdkafka producer, and this option is used to set the message.max.bytes config for Rdkafka itself.

Looking at the code, the fix is extremely simple: just add max_request_size to the arguments of the Rdkafka producer constructor and It Just Works as long as I set it to be larger than my max message sizes.

Will try to figure out the contribution process here soon and contribute the pull request, but just wanted to make sure this didn't slip through the cracks.

**Comment by yungchin** [comment]
Thanks very much for catching this. I had a quick look at #480 and I think you're precisely right: the `max_request_size` setting did get hooked up to the corresponding librdkafka setting, the only thing is that it was omitted from the init args. The tests that were added focus on `OwnedBroker`, which the `RdKafkaProducer` doesn't use. It would be super if you want to write the pullreq, thanks!

**Comment by jofusa** [comment]
Good catch.
