### ISSUE TITLE
queued_max_messages default value(2000) cause out of memory

### ISSUE THREAD

**Issue by ajaxhe** [Parsely/pykafka#537]
when I use balancedconsumer class to consumse the kafka message queue, I get the out of memory problem with  queued_max_messages.
To make it simple, I simplly modify the pykafka-demo which worte by [cscheffler](https://github.com/cscheffler/kafka-demo) 

 and as follow code see, just add a line:
**time.sleep(10)**
to simulate the real application.

```
from pykafka import KafkaClient
import time
from threading import current_thread
import uuid
try:
    import configparser  # Python 3
except ImportError:
    import ConfigParser as configparser  # Python 2


config = configparser.ConfigParser()
config.read('settings.conf')

kafka_client = KafkaClient(hosts=config.get('kafka_demo', 'kafka_hosts'))  # Create Kafka client
topic = kafka_client.topics[config.get('kafka_demo', 'topic')]  # This will create the topic if it does not exist
consumer = topic.get_balanced_consumer(
    consumer_group="test_group",
    auto_commit_enable=True,
    zookeeper_connect=config.get('kafka_demo', 'zookeeper_hosts'),
    #queued_max_messages=2000,
    )   
display_interval = int(config.get('kafka_demo', 'display_interval'))

print 'Consuming messagse from topic %r. Press Ctrl-C to interrupt.' % topic.name
display_iteration = 0 
message_count = 0 
partitions = set()  # Track which partitions got consumed by this consumer
process_size = 0 
start_time = time.time()
while True:
    message = consumer.consume()  # Read one message from Kafka
    #identifier = uuid.UUID(message.value)  # Decode the message
    process_size += len(message.value)
    message_count += 1
    time.sleep(10)
    print("total_message_count: %d, total_process_size(KB): %d" % (message_count, process_size/1024))
```

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                 
23252 root      20   0  9.845g 9.072g   4076 S  20.6 58.5   3:40.80 python demo-consumer.py 
```

when i use top -c command, the memory consumption(nearly 10GB)  makes me surprised.

Per message length is below 500KB, althrough queued_max_messages=2000, the total memory consumption may below 2000 * 500KB=1GB, why 10GB memory has been used?

**Comment by emmett9001** [comment]
Thanks for filing this, @ajaxhe. It's clear between this and #470 that there is some memory issue in the consumer. Nothing about your code looks wrong - it's possible that this problem gets worse when the messages being consumed are larger.

**Comment by emmett9001** [comment]
@ajaxhe One thing to note here is that the `queued_max_messages` kwarg is per partition, not total. Thus 10GB of memory might make more sense here if you were testing on a topic with ten partitions. How many partitions does your test topic have?
