### ISSUE TITLE
Error discovering offset manager

### ISSUE THREAD

**Issue by dvenza** [Parsely/pykafka#538]
Using Kafka 0.9.0.1 and pykafka from pip, on python3. The topic has 2 replicas and two partitions on a two broker cluster.

I don't know if it is related to #405 or to some other problem.
When I create a consumer with this code:
```
    consumer = topic.get_simple_consumer(consumer_group='pq_consumer'.encode('utf-8'))
    cursor = pq_conn.cursor()
    for message in consumer:
        if message is not None:
            do_stuff(message)
        consumer.commit_offsets()
```

I get this error:
```
2016-05-03 11:13:28,330 INFO pykafka.cluster (MainThread): Attempting to discover offset manager for consumer group 'b'pq_consumer''
2016-05-03 11:13:28,332 ERROR pykafka.cluster (MainThread): Error discovering offset manager.
2016-05-03 11:13:28,333 DEBUG pykafka.cluster (MainThread): Retrying offset manager discovery
2016-05-03 11:13:29,035 INFO pykafka.handlers (0: pykafka.RequestHandler.worker for 192.168.45.252:9092): RequestHandler worker: exiting cleanly
2016-05-03 11:13:29,325 INFO pykafka.handlers (3: pykafka.RequestHandler.worker for 192.168.45.252:9092): RequestHandler worker: exiting cleanly
2016-05-03 11:13:30,337 ERROR pykafka.cluster (MainThread): Error discovering offset manager.
2016-05-03 11:13:30,338 DEBUG pykafka.cluster (MainThread): Retrying offset manager discovery
2016-05-03 11:13:34,345 ERROR pykafka.cluster (MainThread): Error discovering offset manager.
Traceback (most recent call last):
  File "/home/ubuntu/zoe-logger/pq-consumer.py", line 21, in <module>
    main()
  File "/home/ubuntu/zoe-logger/pq_consumer/entrypoint.py", line 87, in main
    main_loop(kafka_topic, pq_conn)
  File "/home/ubuntu/zoe-logger/pq_consumer/entrypoint.py", line 32, in main_loop
    consumer = topic.get_simple_consumer(consumer_group='pq_consumer'.encode('utf-8'), auto_commit_enable=False)
  File "/home/ubuntu/pykafka/pykafka/topic.py", line 192, in get_simple_consumer
    **kwargs)
  File "/home/ubuntu/pykafka/pykafka/simpleconsumer.py", line 182, in __init__
    self._discover_group_coordinator()
  File "/home/ubuntu/pykafka/pykafka/simpleconsumer.py", line 312, in _discover_group_coordinator
    self._group_coordinator = self._cluster.get_group_coordinator(self._consumer_group)
  File "/home/ubuntu/pykafka/pykafka/cluster.py", line 391, in get_group_coordinator
    res = future.get(GroupCoordinatorResponse)
  File "/home/ubuntu/pykafka/pykafka/handlers.py", line 68, in get
    return response_cls(self.response)
  File "/home/ubuntu/pykafka/pykafka/protocol.py", line 929, in __init__
    self.raise_error(error_code, response)
  File "/home/ubuntu/pykafka/pykafka/protocol.py", line 122, in raise_error
    clsname, response))
pykafka.exceptions.GroupCoordinatorNotAvailable: Response Type: "GroupCoordinatorResponse"	Response: (15, -1, b'', -1)
```
I reference the unicode issue because of that first line: `'b'pq_consumer''` is clearly wrong, but the problem could be somewhere else.

**Comment by emmett9001** [comment]
@dvenza I think that first line is actually just a printing inaccuracy - using `'%s'` to print a bytes object. It looks like the group coordinator request is repeatedly receiving `GroupCoordinatorNotAvailable` and eventually failing after enough retries. Since this is the first connection that the consumer attempts upon starting up, it might be worth checking whether the machine you're running this code on actually does have access to the Kafka hosts you're supplying in the call to `KafkaClient()`. Can you verify that?

**Comment by dvenza** [comment]
On the same machine there is a producer (using pykafka) that works flawlessly and I can ping both brokers.
Here is a more complete log of the consumer:
```
2016-05-04 07:56:01,313 DEBUG pykafka.cluster (MainThread): Updating cluster, attempt 1/3
2016-05-04 07:56:01,315 DEBUG pykafka.connection (MainThread): Connecting to 192.168.45.252:9092
2016-05-04 07:56:01,316 DEBUG pykafka.connection (MainThread): Successfully connected to 192.168.45.252:9092
2016-05-04 07:56:01,407 WARNING pykafka.broker (MainThread): Leader not available for topic 'b'__consumer_offsets'' partition 0.
[... long list of topics that does not contain the topic I want to consume ...]
2016-05-04 07:56:01,487 INFO pykafka.handlers (MainThread): RequestHandler.stop: about to flush requests queue
2016-05-04 07:56:01,487 INFO pykafka.cluster (MainThread): Discovered 2 brokers
2016-05-04 07:56:01,488 DEBUG pykafka.cluster (MainThread): Discovered broker id 1003: b'192.168.45.252':9092
2016-05-04 07:56:01,489 DEBUG pykafka.connection (MainThread): Connecting to b'192.168.45.252':9092
2016-05-04 07:56:01,491 DEBUG pykafka.connection (MainThread): Successfully connected to b'192.168.45.252':9092
2016-05-04 07:56:01,492 DEBUG pykafka.cluster (MainThread): Discovered broker id 1004: b'192.168.45.3':9092
2016-05-04 07:56:01,493 DEBUG pykafka.connection (MainThread): Connecting to b'192.168.45.3':9092
2016-05-04 07:56:01,495 DEBUG pykafka.connection (MainThread): Successfully connected to b'192.168.45.3':9092
2016-05-04 07:56:01,496 INFO pykafka.cluster (MainThread): Discovered 223 topics
[... topic list ...]
2016-05-04 07:56:01,631 DEBUG pykafka.connection (MainThread): Connecting to 192.168.45.252:9092
2016-05-04 07:56:01,632 DEBUG pykafka.connection (MainThread): Successfully connected to 192.168.45.252:9092
2016-05-04 07:56:01,635 INFO pykafka.handlers (MainThread): RequestHandler.stop: about to flush requests queue
2016-05-04 07:56:01,635 INFO pykafka.topic (MainThread): Adding 2 partitions
2016-05-04 07:56:01,636 DEBUG pykafka.topic (MainThread): Adding partition b'docker_logs'/0
2016-05-04 07:56:01,637 DEBUG pykafka.topic (MainThread): Adding partition b'docker_logs'/1
2016-05-04 07:56:01,637 INFO pykafka.cluster (MainThread): Attempting to discover offset manager for consumer group 'b'pq_consumer''
2016-05-04 07:56:01,640 ERROR pykafka.cluster (MainThread): Error discovering offset manager.
2016-05-04 07:56:01,641 DEBUG pykafka.cluster (MainThread): Retrying offset manager discovery
2016-05-04 07:56:02,331 INFO pykafka.handlers (0: pykafka.RequestHandler.worker for 192.168.45.252:9092): RequestHandler worker: exiting cleanly
2016-05-04 07:56:02,639 INFO pykafka.handlers (3: pykafka.RequestHandler.worker for 192.168.45.252:9092): RequestHandler worker: exiting cleanly
2016-05-04 07:56:03,646 ERROR pykafka.cluster (MainThread): Error discovering offset manager.
2016-05-04 07:56:03,646 DEBUG pykafka.cluster (MainThread): Retrying offset manager discovery
2016-05-04 07:56:07,653 ERROR pykafka.cluster (MainThread): Error discovering offset manager.
[... exception as above ...]
```
So it can connect to Kafka correctly.
I verified the same problem with the kafka-python library, so most probably the issue is not in pykafka, but most probably sitting in front of the keyboard.

**Comment by dvenza** [comment]
Ok, my kafka cluster was misconfigured.
For future refence I had a "phantom" broker with ID 1002 defined in zookeeper defined as leader for some of the partitions, but I had no actual broker running with that ID.
Stopped everything, deleted everything on disk and in zookeeper, restarted everything and now it works.

**Comment by mlyashkov** [comment]
Hi, I have the same problem. 
Connection to kafka cluster:
DEBUG:pykafka.cluster:Updating cluster, attempt 1/3
DEBUG:pykafka.connection:Connecting to kafka201:9092
DEBUG:pykafka.connection:Successfully connected to kafka201:9092
WARNING:pykafka.broker:Leader not available for topic '__consumer_offsets' partition 0.
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 3 brokers
DEBUG:pykafka.cluster:Discovered broker id 392: kafka203:9092
DEBUG:pykafka.connection:Connecting to kafka203:9092
DEBUG:pykafka.connection:Successfully connected to kafka203:9092
DEBUG:pykafka.cluster:Discovered broker id 393: kafka201:9092
DEBUG:pykafka.connection:Connecting to kafka201:9092
DEBUG:pykafka.connection:Successfully connected to kafka201:9092
DEBUG:pykafka.cluster:Discovered broker id 394: kafka202:9092
DEBUG:pykafka.connection:Connecting to kafka202:9092
DEBUG:pykafka.connection:Successfully connected to kafka202:9092
INFO:pykafka.cluster:Discovered 13 topics
DEBUG:pykafka.cluster:Discovered topic 'tmp'
...
```python
balanced_consumer = topic.get_balanced_consumer(consumer_group='test_group', auto_commit_enable=True, zookeeper_connect='kafka201:2181,kafka202:2181,kafka203:2181')
```

INFO:kazoo.client:Connecting to kafka201:2181
DEBUG:kazoo.client:Sending request(xid=None): Connect(protocol_version=0, last_zxid_seen=0, time_out=6000, session_id=0, passwd='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', read_only=None)
INFO:kazoo.client:Zookeeper connection established, state: CONNECTED
DEBUG:kazoo.client:Sending request(xid=1): Exists(path='/consumers/test_group/owners/tmp', watcher=None)
DEBUG:kazoo.client:Received response(xid=1): ZnodeStat(czxid=270589522508, mzxid=270589522508, ctime=1467364345728, mtime=1467364345728, version=0, cversion=8, aversion=0, ephemeralOwner=0, dataLength=0, numChildren=0, pzxid=270589534322)
DEBUG:kazoo.client:Sending request(xid=2): Create(path='/consumers/test_group/ids/mlyashkov-comp:06290fc1-bfb6-40fe-bbd7-3077ecddf0aa', data='tmp', acl=[ACL(perms=31, acl_list=['ALL'], id=Id(scheme='world', id='anyone'))], flags=1)
DEBUG:kazoo.client:Received response(xid=2): u'/consumers/test_group/ids/mlyashkov-comp:06290fc1-bfb6-40fe-bbd7-3077ecddf0aa'
DEBUG:kazoo.client:Sending request(xid=3): GetChildren(path='/brokers/ids', watcher=<bound method ChildrenWatch._watcher of <kazoo.recipe.watchers.ChildrenWatch object at 0x7faada985810>>)
DEBUG:kazoo.client:Received response(xid=3): [u'392', u'393', u'394']
DEBUG:kazoo.client:Sending request(xid=4): GetChildren(path='/brokers/topics', watcher=<bound method ChildrenWatch._watcher of <kazoo.recipe.watchers.ChildrenWatch object at 0x7faada985850>>)
DEBUG:kazoo.client:Received response(xid=4): [u'url_class_queue', u'remarketing_queue', u'dsp_delivery_seance_features_queue', u'search_queries_queue', u'site_index_queue', u'second_party_queue', u'identify_queue', u'mobile_app_description_queue', u'test_topic', u'tmp', u'visitor_action_queue', u'audiences_queue', u'__consumer_offsets']
DEBUG:kazoo.client:Sending request(xid=5): GetChildren(path='/consumers/test_group/ids', watcher=<bound method ChildrenWatch._watcher of <kazoo.recipe.watchers.ChildrenWatch object at 0x7faada985890>>)
DEBUG:kazoo.client:Received response(xid=5): [u'mlyashkov-comp:06290fc1-bfb6-40fe-bbd7-3077ecddf0aa']
INFO:pykafka.balancedconsumer:Rebalancing consumer "mlyashkov-comp:06290fc1-bfb6-40fe-bbd7-3077ecddf0aa" for topic "tmp".
DEBUG:kazoo.client:Sending request(xid=6): GetChildren(path='/consumers/test_group/ids', watcher=None)
DEBUG:kazoo.client:Received response(xid=6): [u'mlyashkov-comp:06290fc1-bfb6-40fe-bbd7-3077ecddf0aa']
DEBUG:kazoo.client:Sending request(xid=7): GetData(path=u'/consumers/test_group/ids/mlyashkov-comp:06290fc1-bfb6-40fe-bbd7-3077ecddf0aa', watcher=None)
DEBUG:kazoo.client:Received response(xid=7): ('tmp', ZnodeStat(czxid=270589548533, mzxid=270589548533, ctime=1467365749667, mtime=1467365749667, version=0, cversion=0, aversion=0, ephemeralOwner=96147589277275579, dataLength=3, numChildren=0, pzxid=270589548533))
INFO:pykafka.balancedconsumer:mlyashkov-comp:06290fc1-bfb6-40fe-bbd7-3077ecddf0aa: Balancing 1 participants for 1 partitions. Owning 1 partitions.
DEBUG:pykafka.balancedconsumer:My partitions: ['tmp-393-0']
DEBUG:kazoo.client:Sending request(xid=8): GetChildren(path='/consumers/test_group/owners/tmp', watcher=None)
DEBUG:kazoo.client:Received response(xid=8): []
DEBUG:kazoo.client:Sending request(xid=9): Create(path='/consumers/test_group/owners/tmp/393-0', data='mlyashkov-comp:06290fc1-bfb6-40fe-bbd7-3077ecddf0aa', acl=[ACL(perms=31, acl_list=['ALL'], id=Id(scheme='world', id='anyone'))], flags=1)
DEBUG:kazoo.client:Received response(xid=9): u'/consumers/test_group/owners/tmp/393-0'
INFO:pykafka.cluster:Attempting to discover offset manager for consumer group 'test_group'
ERROR:pykafka.cluster:Error discovering offset manager.
DEBUG:pykafka.cluster:Retrying offset manager discovery
ERROR:pykafka.cluster:Error discovering offset manager.
DEBUG:pykafka.cluster:Retrying offset manager discovery
ERROR:pykafka.cluster:Error discovering offset manager.
ERROR:pykafka.balancedconsumer:Stopping consumer in response to error
Traceback (most recent call last):
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 306, in start
    self._rebalance()
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 603, in _rebalance
    self._update_member_assignment()
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 578, in _update_member_assignment
    if self._setup_internal_consumer(new_partitions):
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 359, in _setup_internal_consumer
    cns = self._get_internal_consumer(partitions=list(partitions), start=start)
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 417, in _get_internal_consumer
    consumer_id=self._consumer_id
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 187, in __init__
    self._discover_group_coordinator()
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 315, in _discover_group_coordinator
    self._group_coordinator = self._cluster.get_group_coordinator(self._consumer_group)
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/cluster.py", line 390, in get_group_coordinator
    res = future.get(GroupCoordinatorResponse)
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/handlers.py", line 68, in get
    return response_cls(self.response)
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/protocol.py", line 929, in __init__
    self.raise_error(error_code, response)
  File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/protocol.py", line 122, in raise_error
    clsname, response))
GroupCoordinatorNotAvailable: Response Type: "GroupCoordinatorResponse"	Response: (15, -1, '', -1)
DEBUG:pykafka.balancedconsumer:Stopping <pykafka.balancedconsumer.BalancedConsumer at 0x7faadaa63450 (consumer_group=test_group)>
DEBUG:kazoo.client:Sending request(xid=10): Close()
DEBUG:kazoo.client:Received EVENT: Watch(type=4, state=3, path=u'/consumers/test_group/ids')
INFO:kazoo.client:Closing connection to kafka201:2181
INFO:kazoo.client:Zookeeper session lost, state: CLOSED
DEBUG:pykafka.simpleconsumer:Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x7faada985a10 (consumer_group=test_group)>
DEBUG:pykafka.balancedconsumer:Finalising <pykafka.balancedconsumer.BalancedConsumer at 0x7faada952e50 (consumer_group=test_group)>

**Comment by emmett9001** [comment]
Hi @mylashkov, please include the code you're using to generate this error. Thanks!

**Comment by mlyashkov** [comment]
@emmett9001, I try this:
` import pykafka`
`import logging`
`logging.basicConfig(level=logging.NOTSET)`
`cl = pykafka.KafkaClient(hosts='kafka201:9092, kafka202:9092, kafka203:9092')`

> DEBUG:pykafka.cluster:Updating cluster, attempt 1/3
> DEBUG:pykafka.connection:Connecting to kafka201:9092
> DEBUG:pykafka.connection:Successfully connected to kafka201:9092
> WARNING:pykafka.broker:Leader not available for topic '__consumer_offsets' partition 0.
> INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
> INFO:pykafka.cluster:Discovered 3 brokers
> DEBUG:pykafka.cluster:Discovered broker id 392: kafka203:9092
> DEBUG:pykafka.connection:Connecting to kafka203:9092
> DEBUG:pykafka.connection:Successfully connected to kafka203:9092
> DEBUG:pykafka.cluster:Discovered broker id 393: kafka201:9092
> DEBUG:pykafka.connection:Connecting to kafka201:9092
> DEBUG:pykafka.connection:Successfully connected to kafka201:9092
> DEBUG:pykafka.cluster:Discovered broker id 394: kafka202:9092
> DEBUG:pykafka.connection:Connecting to kafka202:9092
> DEBUG:pykafka.connection:Successfully connected to kafka202:9092
> INFO:pykafka.cluster:Discovered 13 topics
> DEBUG:pykafka.cluster:Discovered topic 'tmp'
> DEBUG:pykafka.cluster:Discovered topic 'audiences_queue'
> DEBUG:pykafka.cluster:Discovered topic 'second_party_queue'
> DEBUG:pykafka.cluster:Discovered topic 'mobile_app_description_queue'
> DEBUG:pykafka.cluster:Discovered topic 'dsp_delivery_seance_features_queue'
> DEBUG:pykafka.cluster:Discovered topic 'remarketing_queue'
> DEBUG:pykafka.cluster:Discovered topic 'identify_queue'
> DEBUG:pykafka.cluster:Discovered topic 'url_class_queue'
> DEBUG:pykafka.cluster:Discovered topic 'site_index_queue'
> DEBUG:pykafka.cluster:Discovered topic 'test_topic'
> DEBUG:pykafka.cluster:Discovered topic 'visitor_action_queue'
> DEBUG:pykafka.cluster:Discovered topic 'search_queries_queue'
> INFO:pykafka.handlers:RequestHandler worker: exiting cleanly

`topic = cl.topics['site_index_queue']`
> DEBUG:pykafka.connection:Connecting to kafka201:9092
> DEBUG:pykafka.connection:Successfully connected to kafka201:9092
> INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
> INFO:pykafka.topic:Adding 3 partitions
> DEBUG:pykafka.topic:Adding partition site_index_queue/0
> DEBUG:pykafka.topic:Adding partition site_index_queue/1
> DEBUG:pykafka.topic:Adding partition site_index_queue/2
> INFO:pykafka.handlers:RequestHandler worker: exiting cleanly

`balanced_consumer = topic.get_balanced_consumer(consumer_group='test_group', auto_commit_enable=True, zookeeper_connect='kafka201:2181,kafka202:2181,kafka203:2181')`

> Level 5:kazoo.client:ZK loop started
> Level 5:kazoo.client:Skipping state change
> INFO:kazoo.client:Connecting to kafka201:2181
> Level 5:kazoo.client:    Using session_id: None session_passwd: 00000000000000000000000000000000
> DEBUG:kazoo.client:Sending request(xid=None): Connect(protocol_version=0, last_zxid_seen=0, time_out=6000, session_id=0, passwd='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', read_only=None)
> Level 5:kazoo.client:Read response Connect(protocol_version=0, last_zxid_seen=0, time_out=6000, session_id=96147589277990315, passwd='48%\xb6gX\xbb\x13\xf8\x80\x84_\x00\xbf\xcb>', read_only=False)
> Level 5:kazoo.client:Session created, session_id: 96147589277990315 session_passwd: 343825b66758bb13f880845f00bfcb3e
>     negotiated session timeout: 6000
>     connect timeout: 2000
>     read timeout: 4000.0
> INFO:kazoo.client:Zookeeper connection established, state: CONNECTED
> DEBUG:kazoo.client:Sending request(xid=1): Exists(path='/consumers/test_group/owners/site_index_queue', watcher=None)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=1, zxid=270594036847, err=0)
> DEBUG:kazoo.client:Received response(xid=1): ZnodeStat(czxid=270589726248, mzxid=270589726248, ctime=1467375307214, mtime=1467375307214, version=0, cversion=15, aversion=0, ephemeralOwner=0, dataLength=0, numChildren=3, pzxid=270589741377)
> DEBUG:kazoo.client:Sending request(xid=2): Create(path='/consumers/test_group/ids/mlyashkov-comp:f1429529-1b80-41d3-b94a-e73beaddd363', data='site_index_queue', acl=[ACL(perms=31, acl_list=['ALL'], id=Id(scheme='world', id='anyone'))], flags=1)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=2, zxid=270594036848, err=0)
> DEBUG:kazoo.client:Received response(xid=2): u'/consumers/test_group/ids/mlyashkov-comp:f1429529-1b80-41d3-b94a-e73beaddd363'
> DEBUG:kazoo.client:Sending request(xid=3): GetChildren(path='/brokers/ids', watcher=<bound method ChildrenWatch._watcher of <kazoo.recipe.watchers.ChildrenWatch object at 0x7fee4a9a2710>>)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=3, zxid=270594036851, err=0)
> DEBUG:kazoo.client:Received response(xid=3): [u'392', u'393', u'394']
> DEBUG:kazoo.client:Sending request(xid=4): GetChildren(path='/brokers/topics', watcher=<bound method ChildrenWatch._watcher of <kazoo.recipe.watchers.ChildrenWatch object at 0x7fee4a9a2890>>)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=4, zxid=270594036852, err=0)
> DEBUG:kazoo.client:Received response(xid=4): [u'url_class_queue', u'remarketing_queue', u'dsp_delivery_seance_features_queue', u'search_queries_queue', u'site_index_queue', u'second_party_queue', u'identify_queue', u'mobile_app_description_queue', u'test_topic', u'tmp', u'visitor_action_queue', u'audiences_queue', u'__consumer_offsets']
> DEBUG:kazoo.client:Sending request(xid=5): GetChildren(path='/consumers/test_group/ids', watcher=<bound method ChildrenWatch._watcher of <kazoo.recipe.watchers.ChildrenWatch object at 0x7fee4a9a2910>>)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=5, zxid=270594036855, err=0)
> DEBUG:kazoo.client:Received response(xid=5): [u'mlyashkov-comp:f1429529-1b80-41d3-b94a-e73beaddd363', u'mlyashkov-comp:23b510cf-698d-4da8-8509-09471e1811aa']
> INFO:pykafka.balancedconsumer:Rebalancing consumer "mlyashkov-comp:f1429529-1b80-41d3-b94a-e73beaddd363" for topic "site_index_queue".
> DEBUG:kazoo.client:Sending request(xid=6): GetChildren(path='/consumers/test_group/ids', watcher=None)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=6, zxid=270594036856, err=0)
> DEBUG:kazoo.client:Received response(xid=6): [u'mlyashkov-comp:f1429529-1b80-41d3-b94a-e73beaddd363', u'mlyashkov-comp:23b510cf-698d-4da8-8509-09471e1811aa']
> DEBUG:kazoo.client:Sending request(xid=7): GetData(path=u'/consumers/test_group/ids/mlyashkov-comp:f1429529-1b80-41d3-b94a-e73beaddd363', watcher=None)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=7, zxid=270594036857, err=0)
> DEBUG:kazoo.client:Received response(xid=7): ('site_index_queue', ZnodeStat(czxid=270594036848, mzxid=270594036848, ctime=1467613336154, mtime=1467613336154, version=0, cversion=0, aversion=0, ephemeralOwner=96147589277990315, dataLength=16, numChildren=0, pzxid=270594036848))
> DEBUG:kazoo.client:Sending request(xid=8): GetData(path=u'/consumers/test_group/ids/mlyashkov-comp:23b510cf-698d-4da8-8509-09471e1811aa', watcher=None)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=8, zxid=270594036860, err=0)
> DEBUG:kazoo.client:Received response(xid=8): ('site_index_queue', ZnodeStat(czxid=270589744395, mzxid=270589744395, ctime=1467376279362, mtime=1467376279362, version=0, cversion=0, aversion=0, ephemeralOwner=0, dataLength=16, numChildren=0, pzxid=270589744395))
> INFO:pykafka.balancedconsumer:mlyashkov-comp:f1429529-1b80-41d3-b94a-e73beaddd363: Balancing 2 participants for 3 partitions. Owning 1 partitions.
> DEBUG:pykafka.balancedconsumer:My partitions: ['site_index_queue-394-1']
> DEBUG:kazoo.client:Sending request(xid=9): GetChildren(path='/consumers/test_group/owners/site_index_queue', watcher=None)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=9, zxid=270594036865, err=0)
> DEBUG:kazoo.client:Received response(xid=9): [u'392-2', u'393-0', u'394-1']
> DEBUG:kazoo.client:Sending request(xid=10): GetData(path='/consumers/test_group/owners/site_index_queue/392-2', watcher=None)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=10, zxid=270594036865, err=0)
> DEBUG:kazoo.client:Received response(xid=10): ('mlyashkov-comp:2dd374db-71eb-40cf-99a9-dd6502da8d7b', ZnodeStat(czxid=270589740386, mzxid=270589740386, ctime=1467376066940, mtime=1467376066940, version=0, cversion=0, aversion=0, ephemeralOwner=0, dataLength=51, numChildren=0, pzxid=270589740386))
> DEBUG:kazoo.client:Sending request(xid=11): GetData(path='/consumers/test_group/owners/site_index_queue/393-0', watcher=None)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=11, zxid=270594036869, err=0)
> DEBUG:kazoo.client:Received response(xid=11): ('mlyashkov-comp:2dd374db-71eb-40cf-99a9-dd6502da8d7b', ZnodeStat(czxid=270589739687, mzxid=270589739687, ctime=1467376018941, mtime=1467376018941, version=0, cversion=0, aversion=0, ephemeralOwner=0, dataLength=51, numChildren=0, pzxid=270589739687))
> DEBUG:kazoo.client:Sending request(xid=12): GetData(path='/consumers/test_group/owners/site_index_queue/394-1', watcher=None)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=12, zxid=270594036869, err=0)
> DEBUG:kazoo.client:Received response(xid=12): ('mlyashkov-comp:2dd374db-71eb-40cf-99a9-dd6502da8d7b', ZnodeStat(czxid=270589741377, mzxid=270589741377, ctime=1467376119345, mtime=1467376119345, version=0, cversion=0, aversion=0, ephemeralOwner=0, dataLength=51, numChildren=0, pzxid=270589741377))
> DEBUG:kazoo.client:Sending request(xid=13): Create(path='/consumers/test_group/owners/site_index_queue/394-1', data='mlyashkov-comp:f1429529-1b80-41d3-b94a-e73beaddd363', acl=[ACL(perms=31, acl_list=['ALL'], id=Id(scheme='world', id='anyone'))], flags=1)
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=13, zxid=270594036872, err=-110)
> DEBUG:kazoo.client:Received error(xid=13) NodeExistsError((), {})
> INFO:pykafka.cluster:Attempting to discover offset manager for consumer group 'test_group'
> ERROR:pykafka.cluster:Error discovering offset manager.
> DEBUG:pykafka.cluster:Retrying offset manager discovery
> Level 5:kazoo.client:Sending request(xid=-2): Ping()
> Level 5:kazoo.client:Received Ping
> ERROR:pykafka.cluster:Error discovering offset manager.
> DEBUG:pykafka.cluster:Retrying offset manager discovery
> Level 5:kazoo.client:Sending request(xid=-2): Ping()
> Level 5:kazoo.client:Received Ping
> Level 5:kazoo.client:Sending request(xid=-2): Ping()
> Level 5:kazoo.client:Received Ping
> ERROR:pykafka.cluster:Error discovering offset manager.
> ERROR:pykafka.balancedconsumer:Stopping consumer in response to error
> Traceback (most recent call last):
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 306, in start
>     self._rebalance()
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 603, in _rebalance
>     self._update_member_assignment()
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 578, in _update_member_assignment
>     if self._setup_internal_consumer(new_partitions):
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 359, in _setup_internal_consumer
>     cns = self._get_internal_consumer(partitions=list(partitions), start=start)
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 417, in _get_internal_consumer
>     consumer_id=self._consumer_id
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 187, in __init__
>     self._discover_group_coordinator()
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 315, in _discover_group_coordinator
>     self._group_coordinator = self._cluster.get_group_coordinator(self._consumer_group)
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/cluster.py", line 390, in get_group_coordinator
>     res = future.get(GroupCoordinatorResponse)
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/handlers.py", line 68, in get
>     return response_cls(self.response)
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/protocol.py", line 929, in __init__
>     self.raise_error(error_code, response)
>   File "/home/mlyashkov/anaconda2/lib/python2.7/site-packages/pykafka/protocol.py", line 122, in raise_error
>     clsname, response))
> GroupCoordinatorNotAvailable: Response Type: "GroupCoordinatorResponse"	Response: (15, -1, '', -1)
> DEBUG:pykafka.balancedconsumer:Stopping <pykafka.balancedconsumer.BalancedConsumer at 0x7fee4aa0d1d0 (consumer_group=test_group)>
> DEBUG:kazoo.client:Sending request(xid=14): Close()
> DEBUG:kazoo.client:Received EVENT: Watch(type=4, state=3, path=u'/consumers/test_group/ids')
> Level 5:kazoo.client:Reading for header ReplyHeader(xid=14, zxid=270594037147, err=0)
> Level 5:kazoo.client:Read close response
> INFO:kazoo.client:Closing connection to kafka201:2181
> INFO:kazoo.client:Zookeeper session lost, state: CLOSED
> Level 5:kazoo.client:Connection stopped
> DEBUG:pykafka.simpleconsumer:Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x7fee4a9a2b10 (consumer_group=test_group)>

Maybe I have a mistake in configuring clusters. I could not find the description of this error in Google. I hope for your help.

**Comment by emmett9001** [comment]
@mylashkov Looks like you're getting error code 15, which the Kafka protocol documentation describes as 

> The broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active.

**Comment by woisnow** [comment]
I have the same problem,my kafka version is 0.8.2,i use kafka-python it is ok,my code is same as above ,could you help me?
