### ISSUE TITLE
Large messages may linger multiples of linger_ms in Producer

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#539]
I was going to fix this test, which I've seen fail regularly on Travis: https://travis-ci.org/Parsely/pykafka/jobs/126679202#L938 - but then I realised, the failure was in fact highlighting a real problem:

When we produce large messages as in that test, a single `flush()` may not be able to batch them all. We do attempt to make sure that the next message doesn't linger: https://github.com/Parsely/pykafka/blob/e3e49a2301abbd78600b9c1b834c0690eb7b1828/pykafka/producer.py#L613
.... but if the queue isn't very full, this will be overruled: https://github.com/Parsely/pykafka/blob/e3e49a2301abbd78600b9c1b834c0690eb7b1828/pykafka/producer.py#L639

That is, if you produce multiple large messages, you may end up with `linger_ms` waits between each of them, rather than all of them getting shipped after a single interval of `linger_ms`.

**PyKafka version**: current master, e3e49a2301abbd78600b9c1b834c0690eb7b1828
**Kafka version**: any

**Comment by yungchin** [comment]
Quick script to demonstrate:
```python
import pykafka
import time


client = pykafka.KafkaClient("localhost:9092")
topic = client.topics["test-big"]
producer = topic.get_producer(delivery_reports=True)

payload = 800 * 1024 * "_"
for _ in range(10):
    producer.produce(payload)

for _ in range(10):
    msg, exc = producer.get_delivery_report()
    assert exc is None
    print time.time()
```
The times printed are spaced at the `linger_ms` default.

**Comment by emmett9001** [comment]
Good catch, this certainly appears to be a real problem.

**Comment by emmett9001** [comment]
I'm having a hard time seeing where the variance in this test comes from. If `linger_ms` and `queued_min_messages` are kept the same across multiple test runs, shouldn't it either always fail or always succeed?

Aside from that, after looking at this more deeply I'm not sure it's actually a bug in pykafka. All of the logic you've pointed out still seems correct in light of the behavior you're highlighting. I think there's merit to leaning on the user-customizability of `linger_ms` and `min_queued_messages` and simply adjusting the test to never fail in this way using those parameters.
