### ISSUE TITLE
How do I turn off topic auto-creation?

### ISSUE THREAD

**Issue by zhang8473** [Parsely/pykafka#541]
If topic 'foo' does not exist in current Kafka topic list and I use <pre> client.topics['foo'].get_sync_producer().produce('bar') </pre> to push a message, it will automatically create a topic called 'foo' in Kafka, how do I turn this feature off? Can it simply raise an error or give me a return value?

Now I have to always check if the topic exists in kafka topic list before pushing, which causes extra CPU load.

**Comment by yungchin** [comment]
Currently pykafka has no config option to disable this in the client. It wouldn't be hard to add.

But - if that works for you - you can disable it in the broker config through the `auto.create.topics.enable` option: http://kafka.apache.org/documentation.html#brokerconfigs - if you set this false, pykafka will still attempt to create the topic, but should then return an error.
