### ISSUE TITLE
Pykafka : Cant create argument dictionary

### ISSUE THREAD

**Issue by abtpst** [Parsely/pykafka#549]
i have some simple code for monitoring my kafka cluster

    from pykafka import KafkaClient,Topic
    from pykafka.cli import kafka_tools
    if __name__ == '__main__':
        client = KafkaClient(hosts="hostName:port")
        args={
              "topic":"asd",
              "consumer_group":"asdg"
              }
        print kafka_tools.print_consumer_lag(client, args)

but i get

        if args.topic not in client.topics:
    AttributeError: 'dict' object has no attribute 'topic'

at 

    if args.topic not in client.topics:
            raise ValueError('Topic {} does not exist.'.format(args.topic))
        topic = client.topics[args.topic]

what am i doing wrong? I have python 2.7.11

**Comment by emmett9001** [comment]
Hi @abtpst. `kafka_tools` is meant to be used from the command line, so it accepts an `args` object created by `argparse`. Since you're trying to script it, I imagine you could pass a `namedtuple` instance and have it work fine:
```python
Args = namedtuple('args', ['topic', 'consumer_group'])
args = Args(topic="mytopic", consumer_group="mygroup")
kafka_tools.print(consumer_lag(client, args)
```
However note that it's meant to be used from the command line:
```
python kafka_tools.py -b localhost:9200 print_consumer_lag --help
```
