### ISSUE TITLE
Pykafka : How to get consumer offset for each consumer group of each topic

### ISSUE THREAD

**Issue by abtpst** [Parsely/pykafka#550]
I want to print the consumer offsets of all consumer groups for a topic.

    from pykafka import KafkaClient,SimpleConsumer
    from pykafka.cli import kafka_tools
    from argparse import Namespace
    from kazoo.client import KazooClient
    if __name__ == '__main__':
        client = KafkaClient(hosts="hostName:port")
        print kafka_tools.print_topics(client,{})
        zk = KazooClient(hosts='hostName:port')
        zk.start()
        children = zk.get_children('/consumers/')
        print children
        zk.stop()
        args= Namespace(topic="asd",consumer_group="console-consumer-6789")
        print kafka_tools.print_consumer_lag(client,args)

and i get

    Topic        Partitions    Replication
    ----------  ------------  -------------
    asd              64             1
    test             2              0
    test2            4              0
    None
    [u'KafkaManagerOffsetCache', u'console-consumer-1234', u'console-consumer-4567', u'console-consumer-6789']
     Partition   Lag      Latest Offset    Current Offset
    -----------  ------  ---------------  ----------------
         0       26,305       26304              -1
         1       26,258       26257              -1
         2       25,798       25797              -1
         3       26,281       26280              -1
         4       26,375       26374              -1
         5       26,015       26014              -1
         6       26,005       26004              -1
         7       26,096       26095              -1
         8       25,965       25964              -1
         9       26,089       26088              -1
        10       26,028       26027              -1
        11       26,171       26170              -1
        12       26,214       26213              -1
        13       26,136       26135              -1
        14       26,224       26223              -1
        15       26,168       26167              -1
        16       26,131       26130              -1
        17       25,954       25953              -1
        18       26,194       26193              -1
        19       26,338       26337              -1
        20       26,140       26139              -1
        21       26,178       26177              -1
        22       26,112       26111              -1
        23       26,273       26272              -1
        24       26,245       26244              -1
        25       26,237       26236              -1
        26       25,885       25884              -1
        27       26,044       26043              -1
        28       26,181       26180              -1
        29       26,239       26238              -1
        30       26,288       26287              -1
        31       26,058       26057              -1
        32       26,257       26256              -1
        33       26,337       26336              -1
        34       26,203       26202              -1
        35       26,014       26013              -1
        36       26,306       26305              -1
        37       25,901       25900              -1
        38       25,956       25955              -1
        39       26,209       26208              -1
        40       25,913       25912              -1
        41       26,338       26337              -1
        42       25,833       25832              -1
        43       26,320       26319              -1
        44       26,105       26104              -1
        45       26,307       26306              -1
        46       26,008       26007              -1
        47       26,019       26018              -1
        48       26,174       26173              -1
        49       26,242       26241              -1
        50       25,898       25897              -1
        51       26,184       26183              -1
        52       26,438       26437              -1
        53       26,303       26302              -1
        54       26,265       26264              -1
        55       25,820       25819              -1
        56       26,113       26112              -1
        57       26,145       26144              -1
        58       26,038       26037              -1
        59       26,154       26153              -1
        60       25,999       25998              -1
        61       25,921       25920              -1
        62       26,269       26268              -1
        63       26,185       26184              -1
    
     Total lag: 1,672,799 messages.
    None

this is great but note that i have to explicitly specify the consumer group `console-consumer-6789` Is there a way to list all consumer groups for a particular topic?

**Comment by emmett9001** [comment]
Hi @abtpst. pykafka doesn't explicitly support the behavior you're looking for, but you can do something like this:
```python
if __name__ == '__main__':
    client = KafkaClient(hosts="hostName:port")
    zk = KazooClient(hosts='hostName:port')
    zk.start()
    children = zk.get_children('/consumers/')
    zk.stop()
    for consumer_group in children:
        args = Namespace(topic="asd",consumer_group=consumer_group)
        print kafka_tools.print_consumer_lag(client, args)
```
