### ISSUE TITLE
SSL Documentation

### ISSUE THREAD

**Issue by messense** [Parsely/pykafka#556]

**Comment by emmett9001** [comment]
See "getting started" [here](http://pykafka.readthedocs.io/en/latest/#getting-started) and [this docstring](https://github.com/Parsely/pykafka/blob/master/pykafka/connection.py#L34).

I think `SslConfig` needs to be added [here](https://github.com/Parsely/pykafka/blob/master/pykafka/connection.py#L20) to show up in readthedocs.

**Comment by emmett9001** [comment]
@messense See the [`SslConfig` docs](http://pykafka.readthedocs.io/en/latest/api/connection.html#pykafka.connection.SslConfig)
