### ISSUE TITLE
producer fails silently in synchronous mode

### ISSUE THREAD

**Issue by jianbin-wei** [Parsely/pykafka#558]
**PyKafka version**: 2.4.0
**Kafka version**: 0.8.2.1

In testing pykafka compression, I set compression to CompressionType.SNAPPY and sync to True.  I have not installed python-snappy yet and it fails.  However, the producer does not raise any exception.  The `OwnedBroker.queue_reader()` got the exception ImportError and stops.  The `Producer.produce` under synchronous mode does not call `Producer._raise_worker_exceptions` and hence no exception is ever raised.

**Comment by jofusa** [comment]
Thanks for the report. Will take a look.

**Comment by emmett9001** [comment]
Sounds like maybe [this](https://github.com/Parsely/pykafka/blob/e18bdeb3586fab21493b755d564d6b4aa8ec7ef2/pykafka/producer.py#L341) isn't being reached?

**Comment by jianbin-wei** [comment]
yes it stays in the `while True` loop and never get a chance to check the exception.

**Comment by emmett9001** [comment]
Looks like I didn't fully understand the ramifications of [this commit](https://github.com/Parsely/pykafka/commit/26b62cd2094914298be8ecf8179c347be807e7d7). I've included a regression test to make sure this doesn't come up again.
