### ISSUE TITLE
Document possible cause of memory growth

### ISSUE THREAD

**Issue by jmwri** [Parsely/pykafka#560]
If you create a producer with delivery reports but don't check the reports memory grows.

```
>>> with topic.get_producer(delivery_reports=True) as producer:
...     count = 0
...     while True:
...         count += 1
...         producer.produce('test msg', partition_key='{}'.format(count))
```

This has had me stumped looking for a memory leak for a couple of days and although is obvious to me now it could be mentioned in the readme and possibly save someone else the time in the future.

**Comment by emmett9001** [comment]
Thanks @jmwri, I'll add a note.
