### ISSUE TITLE
rdkafka refcnt test failure

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#566]
This error usually shows up at the end of a python3/Kafka 0.9 Travis run, but not always:

```
...
tests/pykafka/utils/test_struct_helpers.py::StructHelpersTests::test_bytearray_unpacking PASSED
tests/pykafka/utils/test_struct_helpers.py::StructHelpersTests::test_string_encoding PASSED
---------------- coverage: platform linux, python 3.4.2-final-0 ----------------
Name                                 Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------------
pykafka/__init__.py                     12      0      0      0   100%
python3.4: rd.h:275: rd_refcnt_sub0: Assertion `!*"refcnt sub-zero"' failed.
ERROR: InvocationError: '/home/travis/build/Parsely/pykafka/.tox/py34/bin/py.test'
___________________________________ summary ____________________________________
ERROR:   py34: commands failed
```

It causes the test run to register as a failure regardless of failed tests. In my experience this error appears independently of whether any tests in the test suite failed. I believe this failure was introduced in the [TLS merge](https://github.com/Parsely/pykafka/commit/b9c36ad1333fa2d64a1edb94f62be729d721d41c).

**PyKafka version**: 2c35e7c8d872be2865cdefd16e855d0340ba5950
**Kafka version**: 0.9

**Comment by emmett9001** [comment]
This can also very occasionally happen on 0.8.2.x test runs.

**Comment by yungchin** [comment]
Do you ever see this locally? I've not seen it here, but it seems to happen a lot on Travis.
We didn't change any extension code in the TLS branch, but we did bump the librdkafka version.

I'm hoping maybe @edenhill has any hints. It could of course be that there's a mistake in the extension code but that earlier librdkafka versions were forgiving about it?

**Comment by emmett9001** [comment]
I don't run the tests locally anymore because there are too many little issues like this that make them fail in various ways. :(

**Comment by edenhill** [comment]
What librdkafka version is this?

**Comment by yungchin** [comment]
Hi, thanks @edenhill. This is with librdkafka 0.9.0.99 - I see you've since released 0.9.1 so let me create a version-bump branch to test (will have to be later today when I'm at my dev machine). Although on the other hand, I don't immediately see relevant commits between the two versions either?

**Comment by edenhill** [comment]
Please try 0.9.1 or latest master, also provide backtrace from gdb.
Thanks

**Comment by emmett9001** [comment]
See [this](https://github.com/Parsely/pykafka/pull/573#issuecomment-227446655)

**Comment by edenhill** [comment]
@emmett9001 You dont need to run the test targets that use trivup, in fact you dont need to run any tests at all when installing librdkafka. The tests are primarily for development use.
Is there anything else blocking the upgrade of librdkafka?

**Comment by emmett9001** [comment]
@edenhill See the comment [here](https://github.com/Parsely/pykafka/pull/573#issuecomment-227865801)

**Comment by emmett9001** [comment]
pykafka master is now using librdkafka 0.9.1. These crashes are still common in the python 3 tests against kafka 0.9. I'm not sure how to get more information for @edenhill - I may have to investigate using gdb for this.

**Comment by emmett9001** [comment]
These failures happen infrequently enough that I've been able to work around them during new releases. This is something that should definitely be fixed, but it's low-priority.

**Comment by emmett9001** [comment]
This appears to happen noticeably less often when testing against Kafka 0.10.

**Comment by emmett9001** [comment]
This is now uncommon enough that I'm comfortable killing this issue.
