### ISSUE TITLE
Python3 consumer groups

### ISSUE THREAD

**Issue by echu** [Parsely/pykafka#567]
When using Python 3.5.1 with PyKafka 2.3.1, the consumer group names and topic names must be bytes (#376). Thanks for updating the API to note this.

However, inside zookeeper, the consumer groups are still stored with a literal 'b'.

```python
import pykafka
client = pykafka.KafkaClient(hosts='localhost:9092')

topic = client.topics[b'test_topic']
consumer = topic.get_balanced_consumer(consumer_group=b'test_group', zookeeper_connect='localhost:2181/kafka')
```

Using `zkCli.sh`,
```
[zk: localhost:2181(CONNECTED) 0] ls /kafka/consumers
[b'test_group']
[zk: localhost:2181(CONNECTED) 0] ls /kafka/brokers/topics
['test_topic']
```

So the topics are properly created (without the literal b), but the consumer groups don't appear to be.

This isn't a deal breaker as I don't share consumer groups across clients, but thought I should bring it to your attention. I believe the offending code is here:

https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L237-L241

If I've mis-used the API, please do let me know. Thanks for your hard work and a great library, nonetheless.

**Comment by emmett9001** [comment]
Thanks @echu, I'm pretty sure at first glance that this is a real bug and that you haven't misused the API. If you'd like to open a pull request that fixes the issue for python 3, please feel free.
