### ISSUE TITLE
Pykafka 2.4.1 release date

### ISSUE THREAD

**Issue by philip-sterne** [Parsely/pykafka#575]
Is there any chance that we can get the current master released as pykafka version 2.4.1?

There are some very useful bugfixes in master for bugs that we're seeing production.  It's also been 7 weeks since 2.4.0 was released, so we're hoping it's about time for a version bump.

If it's not going to happen any time soon, would you mind giving us a rough date of when 2.4.1 will be released?

Thanks for all the great work you guys are doing on pykafka!

**Comment by emmett9001** [comment]
@philip-sterne I can push current master as a development version like `pykafka-2.4.1-dev`. I've been meaning to start doing development releases to lessen the chance of pushing new bugs into people's requirements files. You should be able to use this dev release just like you would a normal PyPI release.

**Comment by emmett9001** [comment]
@philip-sterne Here's a 2.4.1.dev1 release that you can use in requirements files. It's exactly current master, but I'd like to start the practice of running releases in dev mode to make sure no unnecessary regressions are getting into pypi.
