### ISSUE TITLE
Balancedconsumer couldn't work when using SSL feature

### ISSUE THREAD

**Issue by zhanghan987** [Parsely/pykafka#588]
Hi:
I am using the ssl feature of pykafka-2.4.0, and simple consumer and producer works fine now.
But when I trying balancedconsumer, it seems that when using SSL, pykafka can not fecth brokers from zookeeper because broker information in zookeeper is changed:

My question is could I use balancedconsumer and ssl feature at the same time?

**Comment by tdhopper** [comment]
Just came here to ask this question.

**Comment by emmett9001** [comment]
Thanks! Do either of you have a traceback you can share that demonstrates what this issue looks like?

**Comment by zhanghan987** [comment]
Hi emmett,
  My error is as follow:
  ```
    1. self.client = KafkaClient(hosts = self.hosts, zookeeper_hosts = self.zk_hosts, ssl_config=self.ssl_config)
    2. self.client = KafkaClient(hosts = self.hosts, ssl_config=self.ssl_config)
```
     
  The error happens when I used the NO.1 connect code and NO.2 works fine. 
  Error message as follow:

> ERROR:pykafka.cluster:Unable to connect to broker None:-1. Continuing.
> ERROR:pykafka.cluster:[Errno -8] Servname not supported for ai_socktype
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/pykafka/cluster.py", line 242, in _request_metadata
>     ssl_config=self._ssl_config)
>   File "/usr/local/lib/python2.7/site-packages/pykafka/broker.py", line 97, in __init__
>     self.connect()
>   File "/usr/local/lib/python2.7/site-packages/pykafka/broker.py", line 211, in connect
>     self._connection.connect(self._socket_timeout_ms)
>   File "/usr/local/lib/python2.7/site-packages/pykafka/connection.py", line 169, in connect
>     (self.source_host, self.source_port)
>   File "/usr/local/lib/python2.7/socket.py", line 557, in create_connection
>     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
> gaierror: [Errno -8] Servname not supported for ai_socktype

**Comment by emmett9001** [comment]
@zhanghan987 I believe this is happening because the `zookeeper_hosts` argument takes precedence over `hosts`, as noted [here](http://pykafka.readthedocs.io/en/latest/api/client.html#pykafka.client.KafkaClient.__init__) (this could certainly be made more clear in the documentation). Thus, `Cluster` seems to be finding a broker list in zookeeper and attempting to connect to one of those brokers via SSL. Is it possible that the set of brokers you're getting back from zookeeper is different from the set you're supplying via `self.hosts`? You could check this by setting a breakpoint before [this line](https://github.com/Parsely/pykafka/blob/dce20d356387ef0ea0d8f5ef976c7a5925b7918b/pykafka/cluster.py#L269) and examining `broker_connects`.

**Comment by zhanghan987** [comment]
@emmett9001 Thanks for your reply. Actually they are different, because when we config kafka server with only SSL("listeners=SSL://xx.xx.xx.xx:9093" instead of "listeners=PLAINTEXT://xx.xx.xx.xx:9092"), broker hosts and port would be "null" and "-1", so the error happens. 
    And my doubt is when we use only SSL in the client, zookeeper would be useless for both producer and consumer. Am I right or do I miss something?

**Comment by emmett9001** [comment]
@zhanghan987 Does your use case work if you simply omit the `zookeeper_hosts` argument and provide the `zookeeper` connection parameter to `get_balanced_consumer` instead? You can set up your own `KazooClient` connection and pass it to `BalancedConsumer` this way.

**Comment by zhanghan987** [comment]
@emmett9001 Yes, it works.  But a side effect is that we must specify broker hosts(ip and port) now intead of getting them from zookeeper dynamic. When a new broker join kafka cluster, our pykafka client needs to be reconfiguration and restart. Am I right?

**Comment by emmett9001** [comment]
@zhanghan987 Regardless of how the `KafkaClient` is started, it should be able to handle new brokers joining the cluster. The list of hosts given to `KafkaClient.__init__` is simply a set to use for bootstrapping and doesn't have to be inclusive of every hostname that might ever be part of the cluster.

**Comment by zhanghan987** [comment]
@emmett9001 Yes. But if we don't specify the `zookeeper_hosts ` in our `KafkaClient` init function, how could kafkaClient find the new comming broker?

**Comment by jofusa** [comment]
The Metadata requests will keep the clients up to date.

Take a look here: https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Partitioningandbootstrapping

> How can the client find out which topics exist, what partitions they have, and which brokers currently host those partitions so that it can direct its requests to the right hosts? This information is dynamic, so you can't just configure each client with some static mapping file. Instead all Kafka brokers can answer a metadata request that describes the current state of the cluster: what topics there are, which partitions those topics have, which broker is the leader for those partitions, and the host and port information for these brokers.

> In other words, the client needs to somehow find one broker and that broker will tell the client about all the other brokers that exist and what partitions they host. This first broker may itself go down so the best practice for a client implementation is to take a list of two or three urls to bootstrap from. The user can then choose to use a load balancer or just statically configure two or three of their kafka hosts in the clients.

> The client does not need to keep polling to see if the cluster has changed; it can fetch metadata once when it is instantiated cache that metadata until it receives an error indicating that the metadata is out of date. This error can come in two forms: (1) a socket error indicating the client cannot communicate with a particular broker, (2) an error code in the response to a request indicating that this broker no longer hosts the partition for which data was requested.

**Comment by emmett9001** [comment]
Thanks @jofusa. That's right @zhanghan987, the `KafkaClient` doesn't need `zookeeper_hosts` specified to function - it's purely there for user convenience in cases where it's easier to use it than it is to specify `hosts` directly.

**Comment by zhanghan987** [comment]
OK. I get it. Thanks both of you!
