### ISSUE TITLE
Breaking change in latest release – change version number?

### ISSUE THREAD

**Issue by cscheffler** [Parsely/pykafka#590]
Hi, this isn't really a bug, but more of a versioning thing.

My understanding was that 2.4.1.dev1 should be fully backwards compatible with 2.x.

We just had to change this:
```
kafka_client.cluster.get_offset_manager(consumer_group)
```
to this:
```
kafka_client.cluster.get_group_coordinator(consumer_group)
```
to fix a breaking change in our pykafka upgrade from 2.2.1 to 2.4.1.dev1.

It looks like the change happened from 2.2.1 to 2.3.0.

In 2.2.1: https://github.com/Parsely/pykafka/blob/2.2.1/pykafka/cluster.py#L369

In 2.3.0: https://github.com/Parsely/pykafka/blob/2.3.0/pykafka/cluster.py#L369

Should an alias perhaps be created for the old method name (perhaps with a deprecation warning), to maintain backwards compatibility?

**Comment by emmett9001** [comment]
@cscheffler Thanks for pointing this out. When I made that version change, I wasn't treating `get_group_coordinator` as part of the public API. However, I do see that it's confusing not to have it prefixed with a `_` and also not treated as public for the purpose of versioning. I'm not sure exactly how to proceed here - maybe an alias and deprecation warning could work.

**Comment by emmett9001** [comment]
Note to self: the alias and deprecation warning should be added before `2.5.0` is finalized.

**Comment by emmett9001** [comment]
Fixed https://github.com/Parsely/pykafka/commit/8e79985fd6e6aa865beef862371f8af54a646508
