### ISSUE TITLE
Seen some memory leaks?

### ISSUE THREAD

**Issue by messense** [Parsely/pykafka#591]
**PyKafka version**:  e9ac86a  
**Kafka version**: 0.9.0

The code is something like:

```python
import json
import threading
from concurrent.futures import ThreadPoolExecutor

from pykafka import KafkaClient


executor = ThreadPoolExecutor(10)
semaphore = threading.BoundedSemaphore(20)

kafka = KafkaClient(...)
topic = kafka.topics['some-topic']
consumer = topic.get_balanced_consumer(
    consumer_group='test',
    managed=True,
    fetch_message_max_bytes=10 * 1024 * 1024
)
for message in consumer:
    obj = json.loads(message.value)
    semaphore.acquire()
    executor.submit(process, obj)
    consumer.commit_offsets()


def process(obj):
    try:
        # do something
    except Exception:
        # do something
    finally:
        semaphore.release()
```

And I have seen a lot of memory(from ~12G to ~30G) consumed after running for a while.

So I try to debug with objgraph:

### objgraph.show_most_common_types(limit=20)

```
Message                    47050
list                       18440
function                   12654
dict                       5630
tuple                      5319
builtin_function_or_method 3146
weakref                    2962
type                       1754
getset_descriptor          1700
wrapper_descriptor         1518
cell                       1503
method_descriptor          1096
property                   930
module                     748
set                        641
member_descriptor          513
frame                      459
MovedAttribute             332
_Condition                 323
classobj                   316
```

### objgraph.show_growth(limit=20)

```
Message    47052      +215
```

The ``Message`` should be ``pykafka.protocol.Message`` instance.

Any idea how to debug this?

**Comment by emmett9001** [comment]
@messense You might want to adjust the `queued_max_messages` [parameter](http://pykafka.readthedocs.io/en/latest/api/balancedconsumer.html#pykafka.balancedconsumer.BalancedConsumer) to ensure you're not storing too many `Message` instances. If you lower it and still see huge memory usage, it's certainly possible there's a leak.

**Comment by messense** [comment]
@emmett9001 Tried that. Lower it to 500 works better, but still see huge memory usage occasionally (way less often than default 2000 though).
