### ISSUE TITLE
Extended HashingPartitioner, worth contributing?

### ISSUE THREAD

**Issue by lucrussell** [Parsely/pykafka#592]
This is a question rather a problem. 

I had a situation which required a slightly different approach to the HashingPartitioner, and I wondered if it's worth contributing to the main project?

My particular use case sometimes causes many incoming messages have the same partitioning key. This means partitions can be temporarily overloaded, because the HashingPartitioner will (correctly) assign messages with the same key to the same partition. 

To overcome this, I specialized the HashingPartitioner to divide the incoming messages between a configurable subset of the available partitions. For example, given a total of sixteen partitions, one could specify a group size of four to smooth the distribution of incoming messages across a group of four partitions, thus avoiding hot spots in one partition. 

Essentially this is a modification of this line of the HashingPartitioner: https://github.com/Parsely/pykafka/blob/master/pykafka/partitioners.py#L82
with this line:
```return partitions[abs(self.hash_func(key) + randrange(0, self.group_size)) % len(partitions)]```

Please let me know if you think this is more widely useful and I will work on a pull request.

**Comment by emmett9001** [comment]
@lucrussell Thanks for asking! I think this sounds like a useful contribution. Probably the best way to do it will be to extend `HashingPartitioner` or `BasePartitioner` and add your new functionality. I'd be happy to review a pull request when you check one in.
