### ISSUE TITLE
So many 'Broken pipe' exceptions

### ISSUE THREAD

**Issue by zhanghan987** [Parsely/pykafka#596]
Hi,
    My pykafka version 2.4.0, and kafka version is 0.9.0.0.  
    Our system got so many "Broken pipe" exception:

> [2016-08-11 10:40:40,918][140595995432768-MainThread][ERROR]<kafka_producer_client.py:103> send exception: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/itest/scorpio_job/common/kafka/kafka_producer_client.py", line 96, in send
    producer.produce(message)
  File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 341, in produce
    self._raise_worker_exceptions()
  File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 202, in _raise_worker_exceptions
    raise ex
error: [Errno 32] Broken pipe

It will repeat again and again when it suddenly happened.
How did it happen? And what can I do about this exception?

**Comment by emmett9001** [comment]
Hi @zhanghan987. How is your code handling this exception? It might make sense to reinstantiate the consumer when this exception is encountered.

**Comment by zhanghan987** [comment]
Yes, I want to reconnect the consumer for this exception, too. 
How to code it with pykafka, do I need to reconnect kafka broker and get an new consumer? 
Does old consumer thread need to be released or pykafka can do it by self?

**Comment by emmett9001** [comment]
You can do something like this:
```python
try:
    consumer.consume()
except IOError:
    consumer.stop()
    consumer.start()
```
This is very similar to what we do at Parsely in response to `ConsumerStoppedException`. If this doesn't work, you might also try `consumer.stop()` followed by `consumer = topic.get_balanced_consumer()` - ie reinstantiating the consumer after stopping it.

**Comment by zhanghan987** [comment]
OK! Thank you very much, I will try it.

**Comment by pdrtrifork** [comment]
The original incident report above indicates that this is happening in the producer, which is exactly what experience (same versions, same traceback). What fix exists in the case of the producer failing - the proposed fix seems to be for consumers.

**Comment by emmett9001** [comment]
Oops, sorry about that. The logic is actually almost identical for the producer:

```python
try:
    producer.produce()
except IOError:
    producer.stop()
    producer = Producer()
    producer.start()
```

**Comment by pdrtrifork** [comment]
Thanks, no worries.
