### ISSUE TITLE
One topic's consumer offset turn to 'earliest' offset

### ISSUE THREAD

**Issue by zhanghan987** [Parsely/pykafka#597]
Hi:
** kafka version: 0.9.0.0 **
** pykafka version: 2.4.0 **

Last weekend, the linux server which my pykafka process was running on crased.
When I restart the pykafka process this monday, it consume message from the 'earliest' offset. 
PS:
    I call `commit_offsets()` function every time after consume a message.

My question is how did it happen? Do I need some more configuration to resolve it?

**Comment by emmett9001** [comment]
Hi @zhanghan987. Are you using the `reset_offset_on_start` or `auto_offset_reset` parameters on your consumer? If so, they could be interfering with the consumer's handling of stored offsets. Also, you might want to check your cluster's `offsets.retention.minutes` configuration. It defaults to one day, so if you hadn't changed the default I wouldn't be surprised if that were what was causing this behavior.

**Comment by zhanghan987** [comment]
Ah, thanks!
    `offsets.retention.minutes` maybe the reason. I will update this config and monitor it.
    Thank you!
