### ISSUE TITLE
Is there anyway to consume the last x messages for kafka topic?

### ISSUE THREAD

**Issue by hamedhsn** [Parsely/pykafka#601]
I would like to consume the last x msgs in kafka using pykafka. can someone help me?

**Comment by emmett9001** [comment]
Hi @hamedhsn - here's some example code to get you started

```python
client = KafkaClient(hosts="xxxxxxx")
topic = client.topics['mytopic']
consumer = topic.get_simple_consumer(
    auto_offset_reset=OffsetType.LATEST,
    reset_offset_on_start=True)
LAST_N_MESSAGES = 50
offsets = [(p, op.next_offset - LAST_N_MESSAGES) for p, op in consumer._partitions.iteritems()]
consumer.reset_offsets(offsets)
consumer.consume()
```
This code sets the consumer's offset to `LATEST`, then subtracts some arbitrary amount from each partition's offset and gives those values to the consumer. It's untested, but it gets the point across. Check out the `reset_offsets` and `OffsetType.LATEST` attributes on `SimpleConsumer`.

**Comment by alafanechere** [comment]
Hi @emmett9001 , as far as SimpleConsumer is now deprecated do you have any clue on how I could accomplish the same thing with the KafkaConsumer ?

I managed to use the seek method to consume from a custom offset but I cannot find a way to get the latest offset of the partition assigned to my consumer.

**Comment by emmett9001** [comment]
@alafanechere Where do you see that `SimpleConsumer` is deprecated? The method given above should still work fine, and pykafka has never had a `KafkaConsumer` class.
