### ISSUE TITLE
Eventlet support with celery . 

### ISSUE THREAD

**Issue by madhur230491** [Parsely/pykafka#602]
Hi , 

Am looking for some help here . Am using celery workers to send some data to kafka brokers. Am starting celery with evenlet and pykafka client initialization is not working . 

Below are the option with which I start celery - 
`CELERYD_OPTS="-Q prppush,productemails -P eventlet"`

I read that recenlty supprt for greenlets and gevent was added but not working for me . 
This is how am initialising my client - 
`self._kafka_connection = KafkaClient(hosts="kafkabroker0.moengage.com:10252,kafkabroker1.moengage.com:10252,kafkabroker2.moengage.com:10252" ,use_greenlets=True)`

My python version - Python 2.7.6
My pykafka version - latest [_maintainer's note: on 11/19/16, this is 2.5.0_]
kafka brokers - 0.8.2.1

**My implementation is below** - 

``` python
class PyKafkaProducerConsumer(object):
    # Put the bellow in all classes which needs singleton!
    __metaclass__ = SingletonMetaClass

    _kafka_connection = None
    # Moved this to uwsgi init section, check delight/__init__.py

    def __init__(self,topic="test"):

        print "*********** entered pykafka init"
        self._kafka_connection = KafkaClient(hosts="kafkabroker0.moengage.com:10252,kafkabroker1.moengage.com:10252,kafkabroker2.moengage.com:10252",use_greenlets=True)
        print "*********** exit pykafka init"
        #self._topic_connection = self._kafka_connection.topics[topic]



    def sendToKafka(self, topic="test" ,msg={}):
        print "******* sending thru pykafka"
        topic_connection = self._kafka_connection.topics["test"]
        json_msg=json.dumps(msg)
        # Asynchronous by default
        producer=topic_connection.get_sync_producer(min_queued_messages=1,delivery_reports=True)
        print producer
        producer.produce(json_msg)
```

I only see "**********\* entered pykafka init" when I try to initialize the client , and it doesnt return the client object form there . Any help would be very much appreciated as am stuck on this from a long time . 

Also if celery is started without eventlet , this works fine .

**Comment by emmett9001** [comment]
Hi @madhur230491, and thanks for filing this. Are you running the above code as a celery task? I wonder if you can set breakpoints inside of `KafkaClient.__init__` and the functions it calls to see exactly where this call is hanging. I'm guessing it will happen on the first network request, but I'm not certain. My hunch at the moment is that `KafkaClient.__init__` is performing some blocking operation that doesn't play nicely with eventlet.

**Comment by emmett9001** [comment]
@madhur230491 any update on this?

**Comment by madhur230491** [comment]
No , I cudn't find what the issue was .. Since I was initializing it thru celery start , cudnt put debug point there.

**Comment by emmett9001** [comment]
A reasonable way forward toward closing this ticket is to verify that the sync producer works when `use_greenlets=True`.

**Comment by emmett9001** [comment]
Since [this commit](https://github.com/Parsely/pykafka/commit/33d6533af6b172c06f9742ae01efebf1b6cb748b), we've been automatically verifying that the sync producer works with gevent. Given that, plus the lack of additional details on this ticket, I'm closing.
