### ISSUE TITLE
Pykafka lost messages when exception happens

### ISSUE THREAD

**Issue by zhanghan987** [Parsely/pykafka#603]
Hi:

**PyKafka version**:  2.4.0
**Kafka version**:  0.9.0.0

We got some exceptions with pykafka as follow:
```
Traceback (most recent call last):
  File "/home/itest/scorpio_job/common/kafka/kafka_producer_client.py", line 136, in send
    producer.produce(message)
  File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 341, in produce
    self._raise_worker_exceptions()
  File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 202, in _raise_worker_exceptions
    raise ex
error: [Errno 32] Broken pipe
```
We sended messages with async producer, so pykafka's sending thread will send more than one messages(let's say 100 messages) in a sending round. When it get "broken pipe" exception, this 100 messages would be lost because pykafka had remove these 100 from sending queue.
    Am I right or do I miss something?

**Comment by emmett9001** [comment]
Hi @zhanghan987. The producer includes [retry logic](https://github.com/Parsely/pykafka/blob/bddcc4206a2688dccfd4df25716d4380520e883c/pykafka/producer.py#L466) that is used by the worker threads that send messages to brokers. You're correct that the entire message batch (in your example, 100 messages) would be lost when an unhandled error such as yours is encountered in the producer's worker thread. To handle this, I recommend keeping recently produced messages in memory and checking them against `Producer.get_delivery_report()`. If you fail to receive a delivery report for a given message after a crash, you can have your program retry that message.
