### ISSUE TITLE
linger_ms = 0 not working with rdlibkafka

### ISSUE THREAD

**Issue by amitripshtos** [Parsely/pykafka#604]
Hi,
I`m using pykafka and it`s been great, but I found a tiny bug:
when using rdlibkafka, and trying to create a producer with linger_ms=0, it raises this exception:

```
RdKafkaException(\'Configuration property "queue.buffering.max.ms" value 0 is outside allowed range 1..900000\\n\',)
```

However, in the documentation , it says that "linger_ms=0 indicates no lingering."
So I guess it should notice that this option does not work with rdlibkafka

Thanks for this awesome package!
Amit :)

**PyKafka version**: 2.4.0
**Kafka version**: 0.9.1

**Comment by emmett9001** [comment]
Hi @amitripshtos, thanks so much for the feedback and issue report - I'm glad you're getting some use out of pykafka.

I think the solution here is a combination of clearer documentation around rdkafka's interpretation of this argument and possibly logic in `__init__` that ensures the given value for `linger_ms` is within the appropriate range.

**Comment by pemontto** [comment]
I'm getting a similar error with rdkafka even using what the documentation says is the default value

```
>>> producer = topic.get_producer(delivery_reports=True, max_retries=100, retry_backoff_ms=100, use_rdkafka=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pykafka/topic.py", line 95, in get_producer
    return Cls(self._cluster, self, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pykafka/rdkafka/producer.py", line 52, in __init__
    super(RdKafkaProducer, self).__init__(**callargs)
  File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 186, in __init__
    self.start()
  File "/usr/local/lib/python2.7/site-packages/pykafka/rdkafka/producer.py", line 62, in start
    self._rdk_producer.configure(topic_conf=topic_conf)
pykafka.exceptions.RdKafkaException: Configuration property "message.timeout.ms" value 1212000 is outside allowed range 0..900000

>>> producer = topic.get_producer(delivery_reports=True, max_retries=100, retry_backoff_ms=100)
>>> 
```

**Comment by emmett9001** [comment]
Thanks @pemontto. Looks like pykafka is doing [some math](https://github.com/Parsely/pykafka/blob/bddcc4206a2688dccfd4df25716d4380520e883c/pykafka/rdkafka/producer.py#L170-L171) to calculate `message.timeout.ms` that relies on the `max_retries` kwarg. When you set this value to `100`, it results in a `message.timeout.ms` that is larger than rdkafka allows. I'm guessing we should add a check there that ensures the resulting value is within the allowable range. An easy workaround for the moment is to simply adjust `mac_retries`.

**Comment by emmett9001** [comment]
@amitripshtos If you're interested in opening a pull request fixing the documentation and allowed value checks around `linger_ms`, please feel free. If not, I'll get to it next time I'm building a new pykafka release.

**Comment by emmett9001** [comment]
I'm opposed to adding logic to the rdkafka components that validates config values based on their acceptable ranges in librdkafka. Those ranges can theoretically change at any time, and it makes more sense to leave a note in the docstring that certain combinations of values can make librdkafka unhappy than to maintain code that relies on a number in another project not changing.
