### ISSUE TITLE
Sync producer with rdlibkafka is way slower

### ISSUE THREAD

**Issue by amitripshtos** [Parsely/pykafka#605]
Hey guys again !
I found weird behaviour - 
I try to create a sync consumer kafka_topic.get_producer(sync=True) and it`s not working that fast (1-2K / sec) and I understand that because of sync behaviour,

However, when I tried to use rdlibkafka for this sync producer, it`s starts to produce really slow (10-100 / sec)

How to reproduce:
1. Create sync producer without rdlibkafka and produce messages and measure it.
2. Create sync producer with rdlibkafka and produce messages and measure it.

I tried to play with all the settings (including linger_ms and max_queued_messages) but it did not help a bit.

Thank you very much for your help !

**PyKafka version**: 2.4.0
**Kafka version**: 0.9.1

**Comment by emmett9001** [comment]
Thanks @amitripshtos. In general I would not advise using the synchronous producer if speed is a major concern for you. The producer in synchronous mode waits for a delivery report for every single message it sends, which under librdkafka can take a long time. It's possible that there are some optimizations we can make to the rdkafka-based synchronous producer, but it's not a particularly high priority since synchronous mode has never been about speed.

If the reason you're interested in using the synchronous producer is to have stronger guarantees about message delivery, you might consider using the asynchronous producer's delivery reports feature. A common pattern for this is copied here from the README:
```python
>>> with topic.get_producer(delivery_reports=True) as producer:
...     count = 0
...     while True:
...         count += 1
...         producer.produce('test msg', partition_key='{}'.format(count))
...         if count % 10 ** 5 == 0:  # adjust this or bring lots of RAM ;)
...             while True:
...                 try:
...                     msg, exc = producer.get_delivery_report(block=False)
...                     if exc is not None:
...                         print 'Failed to deliver msg {}: {}'.format(
...                             msg.partition_key, repr(exc))
...                     else:
...                         print 'Successfully delivered msg {}'.format(
...                         msg.partition_key)
...                 except Queue.Empty:
...                     break
```

**Comment by amitripshtos** [comment]
@emmett9001 , My problem is that the order of the messages is crucial for me, and that`s why I use the sync producer..

There is another way to make sure the ordering is fine?

**Comment by emmett9001** [comment]
@amitripshtos Are you using a topic with more than one partition? If so, Kafka itself will not provide strong guarantees about message ordering. Each partition is a total ordering of messages, but the random way in which any client will choose which partition to read from makes the topic as a whole only a partial ordering. If you really want to be sure that your messages are totally ordered, you should use a topic with a single partition. However, doing so means you'll lose a lot of the stability and replication benefits that Kafka provides.

**Comment by johnistan** [comment]
To add a little to Emmett's comment. If you use a single partition you can
still replicate the partition for safety. However, you are limited for
scaling, if your consumers can't keep up you will have no ability to
horizontally scale. The usual approach is the set a message key to a common
id and use a hashing parititioner in the producer. This way all messages
with the same key goes to the same partition and can have ordering among
themselves. Now if you you need full global ordering you will have to use a
single partition.

**Comment by amitripshtos** [comment]
Thank you very much guys for your help.
I have a topic with 40-100 partitions and a database table that match partition ID to a machine (my partition keys - each machine take over a partition) so I have ordering per partition.

The issue is that async producing might ruin the order within the partition, no? because if it will retry to produce failed events, it will change the order within the bulk and might ruin the ordering...

That`s why I used sync producer, but the performance is pretty bad so I switched to async producer..

**Comment by emmett9001** [comment]
One thing you could do here is set `max_retries=0` on the producer. This will make sure that the producer never retries a message, and that dropped messages will not interrupt the ordering. You could then use delivery reports to figure out which of your messages were dropped, giving you control over exactly how and when they're replayed. It's not a perfect solution, but unless I'm forgetting something basic, message production that's fully reliable, fast, *and* correctly ordered is not an easy problem.
