### ISSUE TITLE
Update c library path in readme

### ISSUE THREAD

**Issue by sammerry** [Parsely/pykafka#607]
Please add example values for the following c-compiler settings for rdkafka in the readme.md
C_INCLUDE_PATH, LIBRARY_PATH, and LD_LIBRARY_PATH

Installing rdkafka with `sudo apt-get install librdkafka-dev` is not picked up by pykafka with ubuntu 16.04.

**Comment by emmett9001** [comment]
Thanks for checking this in, @sammerry. What's the output of `$ sudo find / -name librdkafka.so` on your system? I believe the path to that shared object should be in your `$LD_LIBRARY_PATH`.
