### ISSUE TITLE
pykafka raises an exception about BalancedConsumer

### ISSUE THREAD

**Issue by armavrdsp** [Parsely/pykafka#610]
when I use pykafka, it raise an exception which I don't know the problem, anyone know?:

```
No handlers could be found for logger "pykafka.simpleconsumer"
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run 
    self._target(*self._args, **self._kwargs)
  File "pyConsumerKafka.py", line 96, in consumer
    for message in kafka_consumer:
  File "/home/idm/.local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 742, in __iter__
    message = self.consume(block=True)
  File "/home/idm/.local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 728, in consume
    message = self._consumer.consume(block=block)
  File "/home/idm/.local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 415, in consume
    self._raise_worker_exceptions()
  File "/home/idm/.local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 227, in _raise_worker_exceptions
    raise ex
KeyError: 20
Exception KeyError: (19,) in <bound method BalancedConsumer.__del__ of <pykafka.balancedconsumer.BalancedConsumer at 0x16d4e10 (consumer_group=kafkarec)>> ignored
```

**and the codes is:**

``` python
def consumer(queueName):

    global pid 
    pid = os.getpid()
    LOGGERS[pid] = logging.getLogger('MyLogger' + str(pid))
    LOGGERS[pid].setLevel(logging.DEBUG)
    LOG_PATH = 'log/hh.redis.out' + str(pid)
    HANDLER = logging.handlers.TimedRotatingFileHandler(LOG_PATH,'midnight',1)
    formatter = logging.Formatter('%(asctime)s - %(message)s')
    HANDLER.setFormatter(formatter)
    LOGGERS[pid].addHandler(HANDLER)

    client = KafkaClient(hosts = kafka_hosts)
    topic = client.topics[kafka_topics]

    kafka_consumer = topic.get_balanced_consumer(
        consumer_group = kafka_group,
        auto_commit_enable = True,
        auto_offset_reset = OffsetType.LATEST,
        ##-+ reset_offset_on_start = True
        ## | reset_offset_on_start = False
        #auto_commit_interval_ms = 1000,
        #reset_offset_on_start = False,
        zookeeper_connect = kafka_zk_connect
    )   
    for message in kafka_consumer:
        if message is not None:
            callback(message.value)

def callback(value):

    global pid
    try:
        lineInfo = json.loads(value.strip())
        eventId = lineInfo['eventId'] if 'eventId' in lineInfo else ''
        account = lineInfo['userId']
        nuId = lineInfo['sessionUuid']
        deviceId = lineInfo['deviceUdid']
        actionTime = int(lineInfo['occurTime'])
        appVersion = lineInfo['appVersion']
        category = lineInfo['category']
        if account in testUsers: return
        if category == 'pageJump':
            LOGGERS[pid].info("[%s,%s,%s]\t%s\t%s\t%s\t%s\t%s" % \
                (account, deviceId, nuId, appVersion, eventId, category, actionTime, timeStamp2Date(actionTime)))
    except Exception as e:
        LOGGERS[pid].info("Exception with %s in log:%s" % (e, value))

if __name__ == '__main__':

    while(1):
        try:
            print 'start python worker ', datetime.datetime.now()
            processList = [ Process(target=consumer, args=("kafka",)) for i in xrange(PROCESS_NUM)]
            for i in xrange(PROCESS_NUM):
                processList[i].start()
            for i in xrange(PROCESS_NUM):
               processList[i].join()
            #consumer("kafka")
        except Exception as e:
            print 'python workder error occur: ', e
            error = 'kafka error: %s' % str(e)
            alert_sms(error)
            time.sleep(3)
    print 'end python worker ', datetime.datetime.now()
```

**Comment by emmett9001** [comment]
@armavrdsp Thanks for filing this. It looks like a real error, but it's hard to see exactly where it's originating. In your log, are there any additional tracebacks prior to the one you posted? This one is the  wrapper exception that the main thread raises to indicate a failure on a worker thread. If you can find the original traceback from the worker itself (which should immediately precede yours in the log), we will have a much better chance of fixing this quickly. Thanks!

**Comment by arpit1997** [comment]
I tried to reproduce this error and yeah it throws an exception .
```
File "/home/.local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 728, in consume
    message = self._consumer.consume(block=block)
  File "/home/.local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 415, in consume
    self._raise_worker_exceptions()
  File "/home/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 227, in _raise_worker_exceptions
    raise ex
KeyError: 20
Exception KeyError: (19,) in <bound method BalancedConsumer.__del__ of <pykafka.balancedconsumer.BalancedConsumer at 0x16d4e10 (consumer_group=kafkarec)>> ignored
```
:smile_cat:

**Comment by emmett9001** [comment]
@arpit1997 Looks like that traceback is the same as the original - notice the `self._raise_worker_exceptions` call indicating that this is the wrapper exception, not the root one. When you reproduce the issue, you should see another traceback before this one. If I can see that root exception (the one not containing `self._raise_worker_exceptions`), I may be able to give more information.

**Comment by dskoda1** [comment]
Does this have anything to do with an exception that looks like this?
```python
Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method BalancedConsumer.__del__ of <pykafka.balancedconsumer.BalancedConsumer at 0x2316290 (consumer_group=group one)>> ignored
```
It is happening in about the same situation, using balanced consumers in a single program (integration test file), but I can't find any other issues/pr's as close as this one to the problem.

**Comment by emmett9001** [comment]
@dskoda1 It looks to me like what you're seeing is another side effect of the root cause - we don't really gain much information by knowing that the thread crashed if we don't know what caused it to crash. Thanks for the help solving this one!

**Comment by dskoda1** [comment]
@emmett9001 Some more background on the exception I am getting:

Instead of creating actual processes like OP is doing, in a test case I am creating two instances of balanced consumer in the main process, and they both belong to the same group (important to note, because test cases where I have two consumers in different groups, this exception is not being raised).

Also since it is in the `__del__` method of the BalancedConsumer:
`<bound method BalancedConsumer.__del__ of <pykafka.balancedconsumer.BalancedConsumer at 0x2316290 (consumer_group=group one)>>`
I was able to avoid the exception by explicitly calling the `__del__` method on the `BalancedConsumer`, which makes it seem to me like some threading resources potentially are not being handled correctly.

**Comment by emmett9001** [comment]
@arpit1997 It looks like you may be getting error code 20 (`NOT_ENOUGH_REPLICAS_AFTER_APPEND`) from the server. What does your topic's replication look like, and do you think this might indeed be happening?

**Comment by emmett9001** [comment]
@armavrdsp @dskoda1 @arpit1997 I recommend changing your consumer instantiation to `with topic.get_balanced_consumer(...) as kafka_consumer:` and performing message consumption inside of that `with` block. This will ensure that the consumers internal threading resources are cleaned up properly when your child process completes, and I'd expect to see these errors go away.

**Comment by rohitpandey5491** [comment]
Hey @emmett9001 :  I am trying to write python code for calculating Kafka Consumer Lag, after executing the code, I am getting no handlers could be found for logger "pykafka.simpleconsumer".
Here is my code:

import pykafka

def fetch_consumer_lag(topic, consumer_group):
"""Get raw lag data for a topic/consumer group.

:param client: KafkaClient connected to the cluster.
:type client:  :class:`pykafka.KafkaClient`
:param topic:  Name of the topic.
:type topic:  :class:`pykafka.topic.Topic`
:param consumer_group: Name of the consumer group to fetch lag for.
:type consumer_groups: :class:`str`
:returns: dict of {partition_id: (latest_offset, consumer_offset)}
"""
latest_offsets = fetch_offsets(topic, 'latest')
# consumer = topic.get_simple_consumer(consumer_group=consumer_group,
#                                         auto_offset_reset=OffsetType.LATEST,
#                                         auto_commit_enable=False,
#                                         auto_commit_interval_ms=1000)


consumer = topic.get_simple_consumer(consumer_group=consumer_group,
                                     auto_start=False,
                                     auto_offset_reset=OffsetType.LATEST,
                                     consumer_timeout_ms=5000)

current_offsets = consumer.fetch_offsets()
def kafkaLagCalculator(client):
"""Calculate lag for a topic/consumer group.

:param client: KafkaClient connected to the cluster.
:type client:  :class:`pykafka.KafkaClient`
"""
topic_list = get_all_topics(client)
consumer_group_topics, consumer_groups = get_consumer_group_for_topic(client, topic_list)

# Don't auto-create topics.
for consumer_group_topic in consumer_group_topics:
    if consumer_group_topic not in client.topics:
        raise ValueError('Topic {} does not exist.'.format(consumer_group_topic))

    topic = client.topics[consumer_group_topic]
    threads = [None] * len(consumer_groups)
    i = 0
    try:
        for consumer_group in consumer_groups:
            threads[i] = Thread(target=fetch_consumer_lag, args=(topic, consumer_group))
            threads[i].start()
            i += 1

        for i in range(len(threads)):
            threads[i].join()
    except Exception as e:
        print "ERROR: ", e.message

Any suggestion would be appreciated.

**Comment by emmett9001** [comment]
@rohitpandey5491 It's not clear from your post what error you're getting. It's easier to pinpoint the issue if you post the minimum amount of code you can use to replicate it.
