### ISSUE TITLE
Support ListGroupRequest/ListGroupResponse commands in protocol

### ISSUE THREAD

**Issue by tobad357** [Parsely/pykafka#620]
Hi
I haven't had time to write up a proper pull request. 
In the meantime if someone wants to use these for checking on lag or listing consumer groups go ahead. Add the two classes below to your code and then

```
req_handler = self.connect(broker.host, broker.port, self.handler)
future = req_handler.request(ListGroupRequest())
res = future.get(ListGroupResponse)

for group in res.groups:
   print group
```

Please note that you need to connect to all brokers to get the consumer groups
Also Kafka doesn't show consumer groups that are currently not connected
I believe this will be fixed in a later version of kafka

```
class ListGroupRequest(Request):
    """A list group request

    Specification::

    ListGroupsRequest =>
    """
    @property
    def API_KEY(self):
        """API_KEY for this request, from the Kafka docs"""
        return 16

    def get_bytes(self):
        """Create a new list group request"""
        output = bytearray(self.HEADER_LEN)
        self._write_header(output)
        return output


class ListGroupResponse(Response):
    """A list group response

    Specification::

    ListGroupsResponse => ErrorCode Groups
      ErrorCode => int16
      Groups => [GroupId ProtocolType]
        GroupId => string
        ProtocolType => string
    """
    error = None
    groups = None

    def __init__(self, buff):
        """Deserialize into a new Response

        :param buff: Serialized message
        :type buff: :class:`bytearray`
        """
        fmt = 'h [SS]'
        response = struct_helpers.unpack_from(fmt, buff, 0)

        error, groups = response
        self.error = error
        self.groups = []
        for group_name,_ in groups:
            self.groups.append(group_name)
```

**Comment by emmett9001** [comment]
Hi @tobad357, and thanks for the contribution. Support for the administrative API has been pending for a while, so it's great to have a start on it. If you'd like to put these classes into a pull request for review, it would be a great help. If not, I'll likely use your code as a basis when I add support for this API.

**Comment by tobad357** [comment]
Hi @emmett9001 I won't have time todo a pull request until end of next week
If you want to please go ahead and use the code above or you can wait and I will give you a proper pull request.. I just need to work out the testing part

I can also contribute some small code that gets consumer lag across all groups.
Seems to be a common problem for 0.10 kafka

**Comment by emmett9001** [comment]
@tobad357 I've started work on a pull request #621 to support the admin api calls. Your consumer lag code would be a welcome contribution if it's doing something different or building on [this call](https://github.com/Parsely/pykafka/blob/f4aa1e7e437921e5ec8b601ab8712350baed0a22/pykafka/cli/kafka_tools.py#L121).

**Comment by emmett9001** [comment]
#621 has been merged into master. It also adds the convenience function `Cluster.get_managed_group_descriptions` that returns descriptions of all managed consumer groups in the cluster.
