### ISSUE TITLE
100% CPU when a consumer does not have any partitions to consume

### ISSUE THREAD

**Issue by amitripshtos** [Parsely/pykafka#628]
Hey guys!
I found a weird bug and it's really easy to simulate it:
1. Create a topic with 1 partition
2. Open 3 python shells and use BalanceConsumer with the same group name for all shells
3. Start consuming until the .consume() is blocking
4. htop and see you CPUs dying

It's a problem since I'm not always aware of how much consumers I have and currently I have 100% CPUs on my consumers when they are just too much.

Thank you for your help! 

**PyKafka version**: 2.5.0
**Kafka version**: 0.9.1

**Comment by emmett9001** [comment]
Hi @amitripshtos. It sounds like your program might be hitting [this line](https://github.com/Parsely/pykafka/blob/a9dd498392a2f78682719f44c56229cfff486c30/pykafka/simpleconsumer.py#L441) repeatedly and chewing up your CPU, but it's hard to be sure based on the information provided. What exactly do you mean by "until the .consume() is blocking"? Can you share some code that shows how you're calling consume? Also, does the topic you're consuming have any messages in it, or is it empty as part of the test?

**Comment by amitripshtos** [comment]
Thanks for replying!
I'll explain better:
1. Create topic with one partition - no need for messages
2. Open 3 Python shells
3 create a balance consumers in each shell and start consuming

You will see that first shell CPU is fine, but two other having 100 precent CPU

That's the problem - consumers with no partitions assigned are killing the CPU

**Comment by amitripshtos** [comment]
I tried playing with timeout settings and even in blocked=false it's happening

**Comment by emmett9001** [comment]
Thanks for the clarification - I'll try to replicate this.

**Comment by emmett9001** [comment]
I've replicated this issue locally, and it appears to be happening because `BalancedConsumer.consume()` [busywaits](https://github.com/Parsely/pykafka/blob/3ea3a6b585b6bd1fd8472ff3947eaa8a6fe3f962/pykafka/balancedconsumer.py#L723) when its internal `SimpleConsumer` doesn't return any messages and `block=True`. We can probably take advantage of the `SimpleConsumer`'s internal use of a semaphore to avoid busywaiting.

**Comment by emmett9001** [comment]
@amitripshtos Please give #681 a try and see if it fixes the issue for you.

**Comment by amitripshtos** [comment]
It's working, thanks!
