### ISSUE TITLE
deprecate SimpleConsumer's consumer_id parameter

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#630]
According to the Kafka protocol documentation, `consumer_id` is invalid on group requests from non-managed consumers.

> Note that when this API is used for a "simple consumer," which is not part of a consumer group, then the generationId must be set to -1 and the memberId must be empty (not null). Additionally, if there is an active consumer group with the same groupId, then the commit will be rejected (typically with an UNKNOWN_MEMBER_ID or ILLEGAL_GENERATION error).

That means that [the consumer_id parameter](https://github.com/Parsely/pykafka/blob/a9dd498392a2f78682719f44c56229cfff486c30/pykafka/simpleconsumer.py#L76) on `SimpleConsumer` should not actually be allowed. It should be deprecated in the next release and removed in the next major version.

The reason this parameter exists at all is because it's [used](https://github.com/Parsely/pykafka/blob/a9dd498392a2f78682719f44c56229cfff486c30/pykafka/balancedconsumer.py#L411) by `ManagedBalancedConsumer`. The interface should be adjusted to allow `ManagedBalancedConsumer` to set this value appropriately for its needs without making it part of the public interface.

Andrew Boot from the [google group thread](https://groups.google.com/forum/#!topic/pykafka-user/2cBD-nWP-4Y) has offered to work on a pull request for this.

**Comment by bootandy** [comment]
How do you see the redesigned classes looking?

I would guess this:
OldSimpleConsumer will subclass NewSimpleConsumer. 
NewSimpleConsumer hides the deprecated params to stop people like me setting them :-) and ManagedBalanceConsumer can create an OldSimpleConsumer just like it does now.

**Comment by emmett9001** [comment]
@bootandy as I look more deeply at this, I'm realizing a basic issue is that [this logic](https://github.com/Parsely/pykafka/blob/c3c5507f1106716af8a935ee2253c94f58751efb/pykafka/simpleconsumer.py#L197) in `SimpleConsumer.__init__` depends on `consumer_id` being set appropriately. This means that removing it from the kwargs list will require some rethinking of how the initial consumer setup happens. It's not entirely clear to me what the best way to handle this is - deprecating and later removing the kwarg would require a redesign, and keeping it around leads to the interface problem you encountered. It seems like bad practice to keep the kwarg and have it come with a warning not to use it, or to make the kwarg "private" (like `_consumer_id`). I wonder if there are examples of this kind of thing being handled in other open source projects.

I'm opposed to creating any new classes since we already regularly get the complaint that pykafka's API is too fragmented by multiple classes.

**Comment by bootandy** [comment]
We could pull _consumer_id  and _generation_id out of the constructor and instead add setter methods for them. ManagedBalancedConsumer could set the values by calling the setters. The down side would be that we'd have 2 junk methods on SimpleConsumer - you would have to know not to call either of these setters.

A private kwarg seems strange to me - I haven't seen that before and it feels counter-intuitive. 

If we did create another class it wouldn't be a public facing class it would just be created by the 2 existing classes SimpleConsumer & ManagedBalanceConsumer.

Thinking 'outside the box' is it possible to go the other way and merge ManagedBalanceConsumer & SimpleConsumer ? Move the ManagedBalanceConsumer zookeeper methods into functions and then If zookeeper args are provided call them?

**Comment by emmett9001** [comment]
Continuing progress [here](https://github.com/Parsely/pykafka/pull/770)
