### ISSUE TITLE
Avro consumer SerializationException: Unknown magic byte!

### ISSUE THREAD

**Issue by erincat** [Parsely/pykafka#645]
I am able to produce and consume avro messages in python using pykafka and avro.schema

I can also produce and consume avro messages using kafka-avro-console-producer/consumer

But when I try to consume avro messages from the topic I made with pykafka in the command line using kafka-avro-console-consumer I get:
```
ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$:105)
org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
```
Any thoughts? Thank you.

**Comment by emmett9001** [comment]
Thanks @erincat. Can you share the code you're using to build and produce these messages? Also, what version of pykafka are you testing against?

**Comment by erincat** [comment]
Here's the code @emmett9001 

from pykafka import KafkaClient
import avro.schema
import io, random
from avro.io import DatumWriter

schema_path="user.avsc"
schema = avro.schema.parse(open(schema_path).read())
 
client = KafkaClient(hosts="localhost:9092")
topic = client.topics['avro-python']

with topic.get_sync_producer() as producer:
    writer = avro.io.DatumWriter(schema)
    bytes_writer = io.BytesIO()
    encoder = avro.io.BinaryEncoder(bytes_writer)
    writer.write({"id":14,"username":"Princess Sophia"}, encoder)
    raw_bytes = bytes_writer.getvalue()
    producer.produce(raw_bytes)`


I read that I'm getting the error because the data is not written using the schema-registry. I'm currently looking into this.

**Comment by emmett9001** [comment]
@erincat Looks like this is not an issue with pykafka, but rather your use of the avro library. The crash you're hitting appears to be [this one](https://github.com/confluentinc/schema-registry/blob/c8c0ca8a09ea99b3288c63d2a0c725e45fd102b7/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java#L76), which has something to do with how you're building `raw_bytes`.

**Comment by erincat** [comment]
Using  [https://github.com/verisign/python-confluent-schemaregistry](url) in producing avro messages with pykafka worked. This uses the schema-registry in writing avro unlike the code that I had before.
