### ISSUE TITLE
linger_ms setting taking precedence over min_queued_messages and sync=True while producing messages

### ISSUE THREAD

**Issue by saran87** [Parsely/pykafka#649]
It takes 5sec to send the Kafka message irrespective of the min_queued_messages=1 and sync=True settings. The producer documentation says otherwise http://pykafka.readthedocs.io/en/latest/api/producer.html

```Python
 #!/usr/bin/env python

from pykafka import KafkaClient
import json
from datetime import datetime
import time

created_topic     =  'test'
group_id = 'test'
kafka_broker_list = 'localhost:9092,localhost1:9092,localhost2:9092'

payload = {'command': 'test_command', 'task-id':'3', 'key':'123e4567-e89b-12d3-a456-426655440000'}
payload = {'message':payload, 'creation-time':str(datetime.now())}

client = KafkaClient(hosts=kafka_broker_list)
topic = client.topics[created_topic]

with topic.get_sync_producer() as producer:
        producer.produce(json.dumps(payload))

print payload
```
Below code works fine as expected, sending the message immediately without lingering.
```Python
with topic.get_sync_producer(linger_ms=0) as producer:
        producer.produce(json.dumps(payload))
```
**PyKafka version**: 2.5.0
**Kafka version**: 0.9.0.1

**Comment by emmett9001** [comment]
Hi @saran87, and thanks for checking this in. I'm a bit confused by your example, since it doesn't specify `min_queued_messages`. When I run a local test with `min_queued_messages=1` and `sync=True`, My messages are delivered immediately in single-message batches, showing the expected behavior. What am I missing?

**Comment by saran87** [comment]
Hi @emmett9001 doesn't get_sync_producer() returns a producer with `sync=True` and `min_qeued_messages=1`. And there was bug fix which went with version [2.3.0](https://github.com/Parsely/pykafka/releases/tag/2.3.0) `Limited Producer.min_queued_messages to 1 when sync=True`.

**Comment by emmett9001** [comment]
`get_sync_producer` does result in `min_queued_messages` being set to `1`, you're right. I still can't replicate your issue with the default `sync` producer settings.

**Comment by emmett9001** [comment]
I am unable to replicate the behavior noted in this ticket. When I run the given code, my single message is delivered immediately (no lingering). @saran87, please comment or reopen this ticket if you're still experiencing the issue.
