### ISSUE TITLE
Consumer not reading from newly added partitions

### ISSUE THREAD

**Issue by arvind-kalyan** [Parsely/pykafka#653]
Hi, 

We're using pykafka consumers in production. Currently there is only 1 consumer process in the consumer group. We recently added more partitions to the topic the consumer is reading from. After this process, we're facing data loss issues.

I think what's happening is that consumer is not reading from the newly added partitions. When does the consumer become aware of newly added partitions? Is there a periodic sync call for getting partition list, like a producer does for broker/partitions? 

I've restarted the consumer for now.

Please help. 
Thanks in advance!

**Comment by emmett9001** [comment]
Hi @arvind-kalyan, and thanks for reaching out. I believe [this watcher function](https://github.com/Parsely/pykafka/blob/e3621a6dab2e0737108d33f0c4783942ba1c3138/pykafka/balancedconsumer.py#L668) should trigger when the number of partitions in a topic changes. Assuming you're using the `BalancedConsumer`, I'd expect this to work. However, altering the number of partitions in a topic while it's being actively consumed is not something I've ever tried in production before, so I don't know for certain that this works as advertised. If I were doing that to a production topic, I'd definitely start by killing the consumer processes, only bringing them back up after the partition update had completed.
