### ISSUE TITLE
Support standard partition assignment strategies

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#657]
#655 points out pykafka's lack of support for the standard `roundrobin` and `range` partition assignment strategies, described [here](https://kafka.apache.org/documentation/#oldconsumerconfigs). Support for these strategies is required for interoperability with other kafka clients. The strategy should be selectable by a kwarg on `BalancedConsumer` that will accept a string `roundrobin|range` and will effectively swap between different implementations of `_decide_partitions`.

**Comment by jeffwidman** [comment]
Are you sure you want the `kwarg` to be a string? There are more partition strategies coming down the pipe, for example one is slated for Kafka `0.10.3`. Plus a user may wish to implement a custom one. So you might want to make the kwarg be a subclass of a basic partitioning class, with the two shipped by default being `RoundRobin` and `Range`
