### ISSUE TITLE
List Consumer Groups for Topic

### ISSUE THREAD

**Issue by johnistan** [Parsely/pykafka#664]
Now that consumer groups and offsets are managed by kafka I have an need for an admin tool to report all existing consumers on a given topic.

I know the java cli tools has this command:

`bin/kafka-consumer-groups.sh  --list --bootstrap-server localhost:9092`

I don't see the corresponding command in pykafka. Am I missing a call or is this an enhancement thats needs a PR?

**Comment by emmett9001** [comment]
The [kafka_tools](https://github.com/Parsely/pykafka/blob/master/pykafka/cli/kafka_tools.py) module has never been particularly feature-complete. A command that lists all existing consumer groups for a topic would be a welcome pull request.

**Comment by emmett9001** [comment]
This CLI feature was generously contributed by @tanaysoni in #706.
