### ISSUE TITLE
Rebalancing not work properly when Monkey patching

### ISSUE THREAD

**Issue by marcofvera** [Parsely/pykafka#671]
**PyKafka version**:  2.5.0
**Kafka version**: 0.10.2

PyKafka can't balancing consumers when using `gevent` and `patch_all()` function.

Looking further it seems there is an issue when pykafka tries to acquire the lock to rebalance on `_rebalance` function in `BalancedConsumer` class.

Here is a code example:
```python
from gevent import monkey
monkey.patch_all()

import logging
logging.basicConfig(level=logging.INFO)

import gevent

from pykafka import KafkaClient
from pykafka.common import OffsetType


def consume(consumer):
    while True:
        message = consumer.consume()
        print('Message: %s' % message.value)


if __name__ == '__main__':
    client = KafkaClient(hosts='localhost:9092')
    topic = client.topics['test']

    consumer = topic.get_balanced_consumer(
        consumer_group='consumer',
        auto_commit_enable=True,
        auto_commit_interval_ms=1000,
        zookeeper_connect='localhost:2181',
        reset_offset_on_start=False,
        auto_offset_reset=OffsetType.LATEST,
        rebalance_max_retries=10
    )

    jobs = [gevent.spawn(consume, consumer)]
    gevent.joinall(jobs)
```
And here is my pip freeze output:
```
gevent==1.2.1
greenlet==0.4.12
kazoo==2.2.1
pykafka==2.5.0
six==1.10.0
tabulate==0.7.7
wsgiref==0.1.2
```

**Comment by emmett9001** [comment]
I've managed to reproduce this bug locally. Adding `use_greenlets=True` to the `KafkaClient.__init__` call doesn't fix the problem.

**Comment by marcofvera** [comment]
I'm sorry @emmett9001 I forgot to mention that I have already tried it.. 😞

**Comment by marcofvera** [comment]
I added one by one all the "patches" and `monkey.patch_thread()` is the one that reproduce this bug.

**Comment by tanaysoni** [comment]
@emmett9001 This seems to now work on my local after the merge of https://github.com/Parsely/pykafka/pull/718.

**Comment by emmett9001** [comment]
@tanaysoni Yup, it works locally for me too. I had no idea these two issues were related - your fix was clearly very sorely needed!

**Comment by carsonip** [comment]
It works for me too. Thanks.

**Comment by marcofvera** [comment]
Thanks, guys! I'll try it out.
