### ISSUE TITLE
Producer in tag 2.6.0.dev2 will deadlock on a call to _update()

### ISSUE THREAD

**Issue by josephaltmaier** [Parsely/pykafka#673]
This problem occurs in tag 2.6.0.dev2 commit hash c9a5f1c7627b408f1709366c5b5ec034e0ba1db9

Any call to Producer._update() that finds a non-zero number of queued_messages must always deadlock.

The Producer has a non-reentrant Lock _update_lock declared here: https://github.com/Parsely/pykafka/blob/c9a5f1c7627b408f1709366c5b5ec034e0ba1db9/pykafka/producer.py#L185

The Producer's _update() function acquires the lock here: https://github.com/Parsely/pykafka/blob/c9a5f1c7627b408f1709366c5b5ec034e0ba1db9/pykafka/producer.py#L228

The Producer's _update() function calls the _produce() function while it has the _update_lock here: https://github.com/Parsely/pykafka/blob/c9a5f1c7627b408f1709366c5b5ec034e0ba1db9/pykafka/producer.py#L238

The Producer's _produce() function tries to acquire the _update_lock here: https://github.com/Parsely/pykafka/blob/c9a5f1c7627b408f1709366c5b5ec034e0ba1db9/pykafka/producer.py#L371

This sequence of events will always result in a deadlock.

I found this deadlock while looking for solutions to hung producer problems I have been having and using a RLock seemed to fix the problem.  I don't know enough about how the Producer is supposed to work to know if using an RLock is an acceptable solution.

**Comment by josephaltmaier** [comment]
Edited to include the commit hash of the Pykafka version.

**Comment by emmett9001** [comment]
Thanks @josephaltmaier for your detective work here. It doesn't seem to me at a glance that an `RLock` is an appropriate fix in this case, but I'll have to look more closely to know for sure. If you'd like to open a pull request that fixes the issue for you, that would provide a great jumping-off point for someone looking to fix this issue.

**Comment by emmett9001** [comment]
The locking logic you're referring to was removed [here](https://github.com/Parsely/pykafka/commit/b5be2527f2ea1392523003117a22de470ca562c7) - please give 2.6.0 a try and post here whether that change fixed the issue. Thanks again for your report.
