### ISSUE TITLE
During deployment, new instances raise PartitionsOwned error.

### ISSUE THREAD

**Issue by sloan-dog** [Parsely/pykafka#677]
We utilize a balanced consumer with rdkafka, running inside a docker container orchestrated by AWS ECS. We run two consumer instances in a group consuming a topic of 2 partitions. I have noticed a trend during deployment, in which the new instances raise PartitionsOwned error. The deployment process involves spinning up new container instances, and deprecating old containers, and switching over connections. This leads me to believe that, for a moment, kafka perceives that 4 consumers are trying to consume 2 partitions, and as kafka law dictates, those newest consumers will receive no partitions. My question is, does pykafka provide an interface to explicitly deregister a consumer. I am hoping to de-register consumer upon a sigint, as provided by container stop. 

Below is how we instantiate consumer, roughly...

```
ConsumerClass(object):
	def __init__(self, consumer_group, auto_commit_enable=True, auto_commit_interval=1000, managed=False, use_rdkafka=False):
	    self.consumer = self.topic.get_balanced_consumer(
	        consumer_group=consumer_group.encode("utf-8"),
	        auto_commit_enable=auto_commit_enable,
	        auto_commit_interval_ms=auth_commit_interval,
	        managed=managed,
	        use_rdkafka=use_rdkafka)
```
We use rdkafka==0.9.1,
Python==3.6
Pykafka==2.5.0

Also, fyi we utilize python tornado in this service, but that doesn't really affect pykafka as the consumer runs on its own thread(s).

How would you suggest de-registering a consumer, is the library handling this ? I did not see in library code where this happens...

**Comment by emmett9001** [comment]
Thanks @sloan-dog. This can happen when consumers are not stopped before new consumers are started. See [this logic](https://github.com/Parsely/pykafka/blob/c73f060abbf46f81ccc42798e5dc7e55bb3c65a2/pykafka/balancedconsumer.py#L323) in `BalancedConsumer` that explicitly releases all of the consumer's held partitions from the zookeeper registry. I'd first ensure that your deployment code is calling `stop()` on the old consumers.

**Comment by johnistan** [comment]
We use marathon and the upgrade strategy deal with this problem.
https://mesosphere.github.io/marathon/docs/deployments.html#rolling-restarts.
This will kill half your existing workers, deploy new code and wait for
them to come up and own a partition and report healthly, and then finally
marathon will replace the remaining workers with the new version.

If you have more then one partition in a topic this will allow the balanced
worker to keep processing during your deployment and protect you from
deploying completely broken code.

ECS might support something like this.

**Comment by amitripshtos** [comment]
I have this error also, combined with:
kazoo.exceptions.NodeExistsError: ((), {})

I don`t see a reason why balanced consumer can not have new workers joined and why we need to stop all consumer before adding a new one..

thanks :)

**Comment by emmett9001** [comment]
These errors happen because of short-lived race conditions between zookeeper and pykafka, which I'm inclined to say are inherent to kafka's design, at least in versions that depend on zookeeper for partition assignment. The workaround is to ensure that existing consumers are fully `stop`ped before new consumers in the same group are started.
