### ISSUE TITLE
Socket disconnected during offset manager discovery. This can happen when using PyKafka with a Kafka version lower than 0.8.2. 

### ISSUE THREAD

**Issue by amitripshtos** [Parsely/pykafka#678]
Hey guys,
I'm getting this error:
ERROR - Socket disconnected during offset manager discovery. This can happen when using PyKafka with a Kafka version lower than 0.8.2. [get_group_coordinator [cluster.py]]

When I'm consuming with balanced consumer (using zookeeper ofcourse)
While my pykafka and kafka versions are upgraded,

Does this error related to something I'm doing wrong?
Thanks

**PyKafka version**: 2.5.0
**Kafka version**: 0.9.1

**Comment by emmett9001** [comment]
@amitripshtos Does this error crash your consumer process, or does the consumer manage to successfully connect on its own? I've seen complaints about this message enough times that it's probably worth lowering the log level.

**Comment by amitripshtos** [comment]
Not always, I did had this error when my kafka crashed, but got a lot more of these errors while everything worked fine

**Comment by emmett9001** [comment]
Lowered the loglevel [here](https://github.com/Parsely/pykafka/commit/be04e3c4e066f4507e307f67bedcea8202dfe92b)
