### ISSUE TITLE
Add an upper limit to __iter__()

### ISSUE THREAD

**Issue by jgujgu** [Parsely/pykafka#680]
Hello,

I wanted to see your opinion on adding an upper limit to `__iter__()`. The reason for this is because I ran into a spout problem on `streamparse/storm` where, though the Kafka Consumer could read all the messages in correctly, the spout seemingly ran into an overflow problem and eventually timed out. For example, my consumer would successfully read in 2000 messages, but the spout would hang on the `emit()` of message 1771.

My wrapping code looks like this:
```
def __iter__(self):
        counter = 0
        limit = self.limit
        while True and counter < limit:
            message = self.consumer.consume(block=True)
            if not message:
                return
            counter += 1
            yield message
```

https://github.com/Parsely/pykafka/blob/3ea3a6b585b6bd1fd8472ff3947eaa8a6fe3f962/pykafka/balancedconsumer.py#L740

-jgujgu

**Comment by emmett9001** [comment]
Hi @jgujgu, and thanks for reaching out. I'm not sure that I see enough widely applicable utility in this feature to add it to pykafka. It seems like the example code you've provided here could be easily added to your application code. You could even use slicing syntax in your application code:
```python
for message in consumer[:limit]:
    ...
```
If you can provide an example of a use case that this would make significantly simpler, it might be worth reconsidering.

**Comment by jgujgu** [comment]
I think `queued_max_messages` provides this functionality. Definitionally, it sounds like it: `The maximum number of messages buffered for consumption in the internal`
