### ISSUE TITLE
Make gevent dependency opt-in?

### ISSUE THREAD

**Issue by messense** [Parsely/pykafka#684]
Currently `pykafka` always requires to install `gevent` even if we don't use it. Would be great be able to opt-in.

Basically, `pip install pykafka` will not install `gevent`, while we can add a `extra_requires` param in `setup.py` to make `pip install pykafka[gevent]` install `pykafka` with `gevent`.

**Comment by emmett9001** [comment]
Sure, this seems reasonable. Thanks for the suggestion @messense, and if you'd like to open a PR that implements this, that would be great.
