### ISSUE TITLE
Wrong error message when certificate verify fails

### ISSUE THREAD

**Issue by rubenbouman** [Parsely/pykafka#699]
I was debugging an issue with setting up my connection and the error message I got was:

'Unable to connect to a broker to fetch metadata. See logs.'

So I enabled debug logging and indeed, some more context was given there:

```
2017-07-12 14:25:06,311 Failed to connect to 123.123.123.123:9093
2017-07-12 14:25:06,311 Failed to connect newly created broker for 123.123.123.123:9093
2017-07-12 14:25:06,311 Socket disconnected during metadata request for broker 123.123.123.123:9093. Continuing.
```

After looking for some time, I found out that this is not a metadata issue, but my (SSL) CA file was incorrect, which resulted in a certificate verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

But this error wasn't logged... So here are the steps that I took to find out:

I was looking into this issue and trying to find out what was going wrong here. I found all three messages in the source code (respectively connection.py, broker.py, cluster.py). I noticed that in connection.py in the function def connect two errors are caught in one line:

`except (self._handler.SockErr, self._handler.GaiError):`

And when one of those 2 errors happen, the following will be executed:

```
log.info("Failed to connect to %s:%s", self.host, self.port)
raise SocketDisconnectedError
```

So that's my first logmessage. Then the SocketDisconnectedError is raised and caught by the Broker constructor:

`log.warning("Failed to connect newly created broker for {host}:{port}".format(host=self._host, port=self._port))`

That's my second logmessage and the constructor just continues. So where does the 3rd logmessage comes from: def _request_metadata in cluster.py:

```
except SocketDisconnectedError:
   log.error("Socket disconnected during metadata request for "
       "broker %s:%s. Continuing.", host, port)
```

So if the Broker constructor has caught the SocketDisconnectedError itself, some other line must raise a SocketDisconnectedError also. So the call to broker.request_metadata is the one that also raises such error. And indeed the @_check_handler doest this.

_check_handler raising a SocketDisconnectedError is fine, but logging "Socket disconnected during metadata request" is not completely right. Because request_metadata is not reached because of @_check_handler. So I was figuring out what was wrong in metadata context... but I found out something else was going on.

Drilling down the code I came again at the lines in connection.py:

```
def connect(self, timeout):
    """Connect to the broker."""
    log.debug("Connecting to %s:%s", self.host, self.port)
    try:
        self._socket = self._wrap_socket(
            self._handler.Socket.create_connection(
                (self.host, self.port),
                timeout / 1000,
                (self.source_host, self.source_port)
            ))
    except (self._handler.SockErr, self._handler.GaiError):
        log.info("Failed to connect to %s:%s", self.host, self.port)
        raise SocketDisconnectedError
    log.debug("Successfully connected to %s:%s", self.host, self.port)
```

No actual errormessage is logged... so I logged the SockErr itself:

```
    except (self._handler.SockErr as, self._handler.GaiError) as e:
        log.info("Failed to connect to %s:%s %s", self.host, self.port, str(e))
```

And found out that this is going on:

Failed to connect to 123.123.123.123:9093 [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

So I would like to suggest to log this str(e) error so you exactly know what's going on.

**Comment by emmett9001** [comment]
Thanks for picking this apart, @rubenbouman. This process mirrors something I've had to do a bunch while debugging SSL-related issues, so it makes a lot of sense to make these errors more visible to save others the headache.
