### ISSUE TITLE
balancedconsumer will get a PartitionOwnedError

### ISSUE THREAD

**Issue by nsf-remoter** [Parsely/pykafka#701]
1. start a kafka server and not include any data, create a topic with 3(any number greater than one)partition.
2. create a balancedconsumer, set `consumer_timeout_ms = -1`.
3. start the balancedconsumer client, and then start it again, here are two client named clientA, clientB.
4. after rebalance_max_retries*rebalance_backoff_ms ms, clientB will get a `PartitionOwnedError`.
5. i have debug the code, find the reason is `consume()` function will always acquire the `_rebalancing_lock` and not to release it, so `_rebalance()` will block at `with self._rebalancing_lock`.

it occur in both master and dev version.

**Comment by emmett9001** [comment]
Thanks @nsf-remoter, this sounds like it should be looked into.

**Comment by tanaysoni** [comment]
@emmett9001 I have looked into it. Here's my hypothesis:

A blocking consumer releases the `_rebalancing_lock` when it either times out or consumes a message. 

Like @nsf-remoter discussed, in the case when `consumer_timeout_ms=-1`,  a triggered rebalance will not make progress(unless it receives a message), as consumer won't give up the lock.  

One workaround is `release` the lock, when a `_rebalance()` is triggered. Do you suspect anything breaking in this approach?

**Comment by emmett9001** [comment]
@tanaysoni I think your approach sounds promising. I'd like to test it out when I get a chance.
