### ISSUE TITLE
RdKafkaSimpleConsumer ignores worker exceptions

### ISSUE THREAD

**Issue by bobgrigoryan** [Parsely/pykafka#704]
I'm using RdKafkaSimpleConsumer with auto_commit enabled.
At some point autocommit worker thread receives some exception and dies.
Before exiting it sets:
`self._worker_exception = sys.exc_info()` 

This worker exception never reaches main thread and it continues to work like nothing happened, since nowhere self._raise_worker_exceptions() is called.

In difference with SimpleConsumer which calls self._raise_worker_exceptions() from consume() function, the overridden consume() function in RdKafkaSimpleConsumer does not raise worker exceptions.

Can be reproduced by manually raising some exception in autocommit worker thread.
Also simulated exception on SimpleConsumer, and it works as expected - consume() exits.

pykafka==2.6.0

**Comment by emmett9001** [comment]
@bobgrigoryan Sounds like this is an oversight and the rdkafka consumer should call `_raise_worker_exceptions`.

**Comment by bobgrigoryan** [comment]
there's some logic differences:
1. simple/balance consumers raise exception before starting consuming messages.
2. rdkafka consumer raises exception after consuming.

this can introduce behavior differences between using different consumers in app.

**Comment by emmett9001** [comment]
@bobgrigoryan I think [this change](https://github.com/Parsely/pykafka/pull/719) should bring the `RdkafkaSimpleConsumer` behavior more inline with the pure python version.

**Comment by bobgrigoryan** [comment]
@emmett9001, looks like the exception is raised only in this case:
`if timeout_ms < 0:`

**Comment by emmett9001** [comment]
https://github.com/Parsely/pykafka/commit/1f85b9656e1528ccd0d51c21c2197fdd1b540701
