### ISSUE TITLE
Connecting pykafka to Spark and loading to HDFS

### ISSUE THREAD

**Issue by riomario1** [Parsely/pykafka#708]
Hi,

I have 2 questions:

1. How do you connect pykafka with Spark 2.x? Both Spark streaming and structured streaming.

2. How to load consumer data into HDFS using pykafka?

Thanks,
Rio

**Comment by emmett9001** [comment]
Hi @riomario1. I think this question is better suited to the pykafka users mailing list, which you can find [here](https://groups.google.com/forum/#!forum/pykafka-user). There, it's likely you'll find someone with experience using pykafka with third-party tools like HDFS and Spark.

For what it's worth, there's no secret magic to getting messages from pykafka into Spark / HDFS. You simply need to use a normal consumer instance (`consumer = topic.get_simple_consumer()`) and consume messages from it (`msg = consumer.consume()`) into your python process' memory, then transform those messages and use the Spark / HDFS python driver to load them into your downstream system.
