### ISSUE TITLE
lz4 Support

### ISSUE THREAD

**Issue by sghaskell** [Parsely/pykafka#709]
Is support for lz4 compression on the roadmap and if so, when do you anticipate a release?

**Comment by emmett9001** [comment]
Yes, pykafka should definitely support all of Kafka's supported compression methods. There is no timeline for it at the moment, but it's something I'm interested in adding when I next have some availability to write a big-ish feature. In the meantime, any community member reading this who's interested in contributing lz4 compression support should feel free to open a pull request for review.

**Comment by sghaskell** [comment]
Thanks for the quick reply @emmett9001. I'll look into it and see if I can't get something working.

**Comment by emmett9001** [comment]
See [`utils/compression.py`](https://github.com/Parsely/pykafka/blob/master/pykafka/utils/compression.py) for a template of how new compression formats should be added.

**Comment by sghaskell** [comment]
I've got working code for producing and consuming lz4 compressed data utilizing python-lz4. @emmett9001 can you help me understand how PyKafka determines what message protocol to use? Is this configurable by the end user or determined via some other mechanism? Can you produce messages in PyKafka using protocol versions v1 or v2?

Kafka 0.8.2 and 0.9 clients had a bug with calculating the frame checksum for lz4 compressed data - see [KAFKA-1493](https://issues.apache.org/jira/browse/KAFKA-1493) . It was fixed in 0.10.0 but the behavior is to still calculate the broken checksum for any v0 produced messages for compatibility. 

See [KIP-57](https://cwiki.apache.org/confluence/display/KAFKA/KIP-57+-+Interoperable+LZ4+Framing) for more details on the issue.

It seems that every message I send from a PyKafka producer uses protocol version v0 which results in the incorrectly calculated checksum. I'd like to test with v1/v2 message format if possible. Thanks for your help.

**Comment by emmett9001** [comment]
Pykafka determines protocol version entirely on the basis of the user-supplied [broker version](https://github.com/Parsely/pykafka/blob/2a98573bcdd1ab1382928d587aa0268a619a667e/pykafka/client.py#L91). For example, here's how the `Producer` [does it](https://github.com/Parsely/pykafka/blob/2a98573bcdd1ab1382928d587aa0268a619a667e/pykafka/producer.py#L161). This check is pretty [simplistic](https://github.com/Parsely/pykafka/blob/2a98573bcdd1ab1382928d587aa0268a619a667e/pykafka/utils/__init__.py#L31) at the moment, so it's possible/likely that the way we determine protocol version will need to be adjusted to allow it to be set independently from broker version. Please feel free to update `msg_protocol_version` in a pull request to accommodate your needs.

**Comment by emmett9001** [comment]
@sghaskell What's the status of your lz4 support code? If you want to open a work-in-progress pull request, I'm happy to work through the details together.

**Comment by sghaskell** [comment]
@emmett9001 The code seems to be working well. I'll go ahead and open a work-in-progress pull request so we can hash out the integration together. Thanks!

**Comment by sghaskell** [comment]
@emmett9001 I just submitted a pull request for the work I've done so far. Have a look and we can go from there. Thanks!
