### ISSUE TITLE
Issue while importing pykafka

### ISSUE THREAD

**Issue by riomario1** [Parsely/pykafka#710]
Hi,

I have installed pykafka but when I import it, I get an error. Any help?

    from pykafka import KafkaClient 
    ImportError: cannot import name KafkaClient

    (test) [cloudera@quickstart ~]$ pip list | grep pykafka
    DEPRECATION: The default format will switch to columns in the future. You can use --format=
    (legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to 
    disable this warning.
    pykafka (2.6.0)

This is how I installed pykafka:
pip install pykafka

Thanks,
Rio

**Comment by emmett9001** [comment]
It's hard to tell based on the information you've supplied, but my best guess is that the python environment you're using doesn't have your `test` virtualenv activated, and thus can't access the pykafka instance you've installed in that virtualenv.

At any rate, this is not a pykafka issue. I'm able to `from pykafka import KafkaClient` on current master.
