### ISSUE TITLE
simpleconsumer does not raise errors in fetch_offsets.

### ISSUE THREAD

**Issue by iciclespider** [Parsely/pykafka#720]
simpleconsumer is not correctly raising KafkaException in the fetch_offsets method. This is due to the following test: 
 https://github.com/Parsely/pykafka/blob/master/pykafka/simpleconsumer.py#L597-L598
```
        if len(parts_by_error) > 1:
            raise KafkaException(parts_by_error)
```
When the same error code is returned for all partitions, such as GroupLoadInProgress.ERROR, then the length of parts_by_error will be 1, preventing the raising of KafkaException. This results in the subsequent reseting of the partition's offsets when messages are consumed.

**Comment by emmett9001** [comment]
Nice catch, @iciclespider! This looks to me like it must have been a simple typo - it should be `len(parts_by_error) > 0`.

**Comment by iciclespider** [comment]
Is there ever a case when the len(parts_by_error) is 0?  Isn't the only only exit out of that loop in the test here? https://github.com/Parsely/pykafka/blob/master/pykafka/simpleconsumer.py#L586
