### ISSUE TITLE
Support CreateTopics / DeleteTopics APIs

### ISSUE THREAD

**Issue by messense** [Parsely/pykafka#722]
https://kafka.apache.org/protocol#The_Messages_CreateTopics

It would be awesome to be able to create/delete topics in pykafka.

**Comment by emmett9001** [comment]
@messense I agree pykafka should support the topic creation and deletion APIs. Do you know when support for these APIs was added to kafka?

**Comment by messense** [comment]
I think it was added in Kafka 0.11, a new Java AdminClient was added too.

https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations

**Comment by nikhilbiyani** [comment]
@emmett9001 I was able to create a topic with kafka broker 0.11.0 with the following setup:

- Assuming that 'mytopic' does not exist
- Create a producer from topic in the following way:
```
client = KafkaClient(hosts='localhost:9092', broker_version="0.11.0")
topic = client.topics['mytopic']
p = topic.get_producer()
```
- Produce some message by the producer:
```
for msg in range(0,10):
        p.produce('%i message' % msg, partition_key='key/garbage', timestamp=time.time()*1000)
p.stop()
```

- The topic was automatically created and the message were properly written.

NOTE:
While running all of this, I get one warning from pykafka:
```
No handlers could be found for logger "pykafka.cluster"
```

**Comment by emmett9001** [comment]
@nikhilbiyani What you're noticing is pykafka's support for automatic topic creation, which is distinct from use of the topic create/delete API. The API provides a rich interface to topic settings as they're being created and deleted, where the autocreation interface simply uses broker defaults to create a topic for which a metadata request is sent.

**Comment by emmett9001** [comment]
This is blocked by #755

**Comment by emmett9001** [comment]
#750 is now unblocked and needs a bit more work, but should be mergeable in the next few weeks.
