### ISSUE TITLE
Read all messages on startup in log compacted topic and exit

### ISSUE THREAD

**Issue by nikhilbiyani** [Parsely/pykafka#724]
I have a Kafka topic with log compaction (partition_key -> values) and in an application I want to read in all the messages present in the topic at startup and exit the loop. 

I did the following now:
```
client = KafkaClient(broker_version="0.11.0")
c = client.topics['mytopic'].get_simple_consumer(
                auto_offset_reset=OffsetType.EARLIEST,
                reset_offset_on_start=True,
                compacted_topic=True)
while True:
        message = c.consume(False)
        if message is not None:
                print message.offset, message.partition_key, message.value
        else:
                break
```

But it is quite possible that there is a `None` message before consuming all messages, and then the logic breaks.

Thanks for the help in advance.

**Comment by emmett9001** [comment]
@nikhilbiyani `None` is a valid return value for `consume(False)` (that is, `block=False`). Since this call doesn't block, it will return `None` when its first attempt to find a message from the topic fails. You can either simply ignore `None` messages or change your call to `consume(block=True)`, which will ensure that you don't get `None` back except in the case of timeouts. The ideal solution probably incorporates both of these changes.

**Comment by willguxy** [comment]
hi i was wondering if this is the best way to get the latest message for each key in a log-compacted topic.

```
consumer = topic.get_simple_consumer(compacted_topic=True,
    reset_offset_on_start=True, auto_offset_reset=OffsetType.EARLIEST,
    consumer_timeout_ms=10000)

for message in consumer:
    if message is None:
        break
    # do something with message
```
It this the right way or we can somehow directly query Kafka for the latest value of each key? If it is, what should the `consumer_timeout_ms` be set in general?

**Comment by emmett9001** [comment]
@willguxy I'm not sure what you mean by "each key" (maybe you're referring to partitions?), but [this recipe](https://github.com/Parsely/pykafka/issues/601#issuecomment-247143250) can get you started on consuming the latest N messages of a topic. As for `consumer_timeout_ms`, it has no bearing on the starting offset for consumption. See the [documentation](http://pykafka.readthedocs.io/en/latest/api/simpleconsumer.html) for more specifics.
