### ISSUE TITLE
Fetch offsets using timestamp

### ISSUE THREAD

**Issue by nikhilbiyani** [Parsely/pykafka#728]
The functionality to fetch offsets using time stamps is coded in the `Topic` class method: `fetch_offset_limits`. But I am having problems with fetching the offsets. In principle, this method should return a list of offsets that were written at a timestamp.

See this test code snippet below:

```
client = KafkaClient(broker_version="0.11.0")
topic = client.topics['mytopic']
p = topic.get_producer()
tm = long(time.time() * 1000)
for m_id in range(0,10):
        p.produce('-%d-' % m_id, timestamp = tm, partition_key='k/e/y')
p.stop()

# The following should give me a list of 10 offsets
print topic.fetch_offset_limits(tm, 10)
```
The last line prints:
```
{0: OffsetPartitionResponse(offset=[], err=0)}
```
This `offset` list should have been of length 10, but is empty.

FYI: I tried `kafka-python` consumer method `offset_for_time` and it works fine in this test.

Can you please help me with this.

Thanks.

**Comment by emmett9001** [comment]
@nikhilbiyani This looks like a real issue, and one that I believe I've personally run into before.

**Comment by nikhilbiyani** [comment]
Same goes with `reset_offsets` method in consumer classes. 

With the code snippet below:
```
client = KafkaClient(broker_version="0.11.0")
topic = client.topics['mytopic']
p = topic.get_producer()
tm = long(time.time() * 1000)
for m_id in range(0,2):
       p.produce('-%d-' % m_id, timestamp = tm, partition_key='k/e/y')
p.stop()

c = topic.get_simple_consumer()
c.reset_offsets([(topic.partitions[k], tm) for k in topic.partitions ])
print(c.held_offsets)
c.stop()
```

Does not produce desired results. Also in the `debug` mode following warnings are produced:
```
WARNING:pykafka.simpleconsumer:Offset reset for partition 0 to timestamp 1507099128549 failed. Setting partition 0's internal counter to 1507099128549
```

Which is because of a bug that is not able to fetch correctly from Kafka broker.

**Comment by emmett9001** [comment]
@nikhilbiyani I've just updated the [documentation](https://github.com/Parsely/pykafka/blob/340f8e16c8b0d9830b6fd889f3be7570015ba3eb/pykafka/topic.py#L111) on `fetch_offset_limits` to make it a lot clearer how the function is intended to work. The issue you're running into is caused by the fact that you're requesting offsets of messages that were written prior to a timestamp from *before* you starting writing messages. Based on my tests, supplying a timestamp from *after* writing was finished provides the desired result. Please see the updated documentation and see if you still have questions. Thanks, and feel free to reopen this ticket if necessary.

**Comment by saich** [comment]
Unable to figure this out.

- This is not an equivalent to `offsetsForTimes` method - Is it?
- Is there an example I can refer to to get offsets per partition given a timestamp?

**Comment by emmett9001** [comment]
@saich it sounds like the [`offsets_before`](https://github.com/Parsely/pykafka/blob/340f8e16c8b0d9830b6fd889f3be7570015ba3eb/pykafka/topic.py#L165) argument on `fetch_offset_limits` is what you're looking for. See that function's docstring for depth on how exactly that timestamp is used. The basic usage of this function looks like this:
```python
from pykafka import KafkaClient
client = KafkaClient()
topic = client.topics["mytopic"]
offset = topic.fetch_offset_limits(1550690088000)
```

**Comment by colin404** [comment]
i also have this problem，here is the code:

```python
self.offset_type = "1595286000000"                          
consumer = KafkaConsumer("Bzhantest", group_id=self.group_id, bootstrap_servers=[self.kafka_address])
tp = TopicPartition("Bzhantest", 0)                                                                  
o = consumer.offsets_for_times({tp:int(self.offset_type)})                                               
print("kafka", o[tp].offset, o)                                       
                                                                            
tm = datetime.datetime.fromtimestamp(int(self.offset_type)/1000)               
offsets = topic.fetch_offset_limits(tm, max_offsets=10)                        
print("pykafka", offsets[self.partition_id])            
```

here is the output:

```bash
('kafka', 1546658, {TopicPartition(topic=u'Bzhantest', partition=0): OffsetAndTimestamp(offset=1546658, timestamp=1595762664524)})
('pykafka', OffsetPartitionResponse(offset=[], err=0))
```

offsets_for_times function can report the offset currect(expected result).

but fetch_offset_limits report [] offset list, and this is not a expected result
