### ISSUE TITLE
Add pykafka recipe to conda-forge

### ISSUE THREAD

**Issue by mrocklin** [Parsely/pykafka#730]
It might be useful to have a `pykafka` recipe on conda-forge.  This would automatically build conda packages for various platforms and would probably help users looking to use pykafka with librdkafka, for which there is already a [binary package](https://github.com/conda-forge/librdkafka-feedstock/).  

[Adding a recipe](https://conda-forge.org/#add_recipe) is relatively easy.  I'm happy to help, though the conda-forge maintainers are also some of the most helpful devs that I've met online.  

There might also be some opportunity to help pykafka automatically find librdkafka when installed in this manner.

**Comment by emmett9001** [comment]
@mrocklin This sounds like a welcome addition - any code you're willing to contribute via pull request would be appreciated.

**Comment by mrocklin** [comment]
I've gone ahead and submitted recipes to conda-forge's staged recipes here

- https://github.com/conda-forge/staged-recipes/pull/4091
- https://github.com/conda-forge/staged-recipes/pull/4090

However this is slightly more complicated than just a PR to the PyKafka repository and would require some involvement from you long-term in the following ways:

1.  You would have to consent to being listed as a maintainer of the PyKafka recipe.  This is analagous to being given ownership rights on PyPI
2.  Ideally you would submit a PR bumping the version number and SHA-256 when you release PyKafka and want that release to also be available through conda.   The sha-256 is easily available through pypi.org . 
3.  We might think about a slightly more complex installation that robustly properly links pykafka to the librdkafka dependency that will also be installed.  Currently this requires some manual work on the part of the user, I suspect that doing this for them in a sure-fire way would be welcome from users (I certainly would have benefitted)
4.  You might look at the current [librdkafka recipe](https://github.com/conda-forge/librdkafka-feedstock/blob/master/recipe/meta.yaml) to verify that it is in good shape.  I don't have much experience here.
5.  You might consider adding a note to your own installation docs that people can install everything with 

        conda install -c conda-forge pykafka

**Comment by emmett9001** [comment]
Steps remaining:

* Add note to release process docs about bumping version and SHA on conda-forge
* Add note to install docs about conda installation
