### ISSUE TITLE
How to get timestamp of message?

### ISSUE THREAD

**Issue by Joukosucl** [Parsely/pykafka#734]
I want to get timestamp of message with pykafka, but i checked the code and didn't find the way.  I checked the `Message`  structor and only find following attributes:

 `
   
    __slots__ = [

        "compression_type",

        "partition_key",

        "value",

        "offset",

        "partition_id",

        "partition",

        "produce_attempt",

        "delivery_report_q"

    ]
`
what should i do for that ?

**PyKafka version**:  2.6.0
**Kafka version**: 0.10.2

**Comment by emmett9001** [comment]
@Joukosucl message timestamps are supported in [2.7.0.dev1](https://github.com/Parsely/pykafka/releases/tag/2.7.0.dev1)
