### ISSUE TITLE
producer thread safe

### ISSUE THREAD

**Issue by thao6626** [Parsely/pykafka#740]
Is the producer in pykafka is thread safe?  

I want to run multi threads to fetch data from other place, and in every thread, i will produce the message to kafka. Using multi threads to increase the throughtput.

but i did not find  instruction about producer  thread safety. 

the Kakfa-python library has illustrated the producer thread safety, the link is: [https://kafka-python.readthedocs.io/en/master/index.html](https://kafka-python.readthedocs.io/en/master/index.html)
`Thread safety
The KafkaProducer can be used across threads without issue, unlike the KafkaConsumer which cannot.`

**Comment by saich** [comment]
@emmett9001: Does the above apply to a producer with `sync=True` as well?

I think its not, but I'm not 100% sure. Would love to know your opinion.

**Comment by emmett9001** [comment]
Yes, `sync=True` is also threadsafe. The waiting mechanism is handled via threadsafe `Queue` instances.
