### ISSUE TITLE
fetch_offsets unconditionally resets the offsets

### ISSUE THREAD

**Issue by bsideup** [Parsely/pykafka#745]
Hi,

In pykafka v2.6.0, call to `fetch_offsets` will populate `partition_offsets_to_reset` and consumer will attempt to reset the offsets.
This is very unpleasant side-effect because we use pykafka to calculate consumer lag and except it to operate in read-only mode.

Is it possible to add some flag to make sure that `fetch_offsets` will not reset the offsets?

**Comment by emmett9001** [comment]
Thanks @bsideup, this sounds like a really useful feature for the read-only use case.

**Comment by bsideup** [comment]
@emmett9001 until it's fixed, my current workaround is:
```python
def noop_reset_offsets(self, partition_offsets=None):
    return

pykafka.SimpleConsumer.reset_offsets = noop_reset_offsets
```

yes, Monkey Patching :D
Ugly, hacky, but doesn't break anything in case of a read-only usage
