### ISSUE TITLE
can not use bootstrap-server in new kafka version?

### ISSUE THREAD

**Issue by thao6626** [Parsely/pykafka#747]
In new version of kafka, consumer does not need to connect zookeeper, instead of bootstrap-server.

Does the pykafka not support this way for consumer?  I do not find any options in simpleConsumer or balancedConsumer

Does this mean that the balanced consumer in pykafka has to connect zookeeper ?

**Comment by emmett9001** [comment]
@thao6626 If you want to avoid having pykafka connect to zookeeper, you can use the [`ManagedBalancedConsumer`](https://github.com/Parsely/pykafka/blob/master/pykafka/managedbalancedconsumer.py). It uses Kafka to store partition ownership information.

**Comment by thao6626** [comment]
@emmett9001    thank you very much.  One suggestion:  Kafka-python is very clear about consumer and producer, but pykafka is not very clear.
