### ISSUE TITLE
it's better to identify which partitioner in producer doc

### ISSUE THREAD

**Issue by j-style** [Parsely/pykafka#762]
**PyKafka version**: latest
**Kafka version**:  any

if initing a produce without specifying partitioner, pykafka will use RandomPartitioner rather than HashingPartitioner to identify partion_id, no matter setting an unnull partition_key or not.

this leads msg with same partition_key sended to random partition,  which is unexpected.

=============
i think it's necessary to notice this feature in document.

**Comment by emmett9001** [comment]
Thanks @j-style, this was fixed in https://github.com/Parsely/pykafka/pull/763
