### ISSUE TITLE
Storing Offsets Outside Kafka

### ISSUE THREAD

**Issue by dev-walker** [Parsely/pykafka#767]
Hi!

How I can implement ["Storing Offsets Outside Kafka"](https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#rebalancecallback)? In Java Consumer they have method [`seek`](https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#seek-org.apache.kafka.common.TopicPartition-long-). 
I'm interested to do this with `ManagedBalancedConsumer`.
I can see that there is the method `reset_offsets` in `SimpleConsumer`, but it seems that it commits offset to Kafka anyway.

pykafka **v2.7.0**
kafka **v1.0.0**

Thanks in advance!

**Comment by emmett9001** [comment]
Hi @dev-walker, and thanks for reaching out. If you're interested in storing offsets outside of Kafka, you should use the `auto_commit_enable=False` kwarg on `ManagedBalancedConsumer`. This will cause offsets not to be stored automatically. You're correct that `reset_offsets` is pykafka's equivalent to `seek`.
