### ISSUE TITLE
testing pykafka in spark nodes

### ISSUE THREAD

**Issue by arita37** [Parsely/pykafka#775]
We aiming to use pykafka under this configuration :   
   python 3.5.4  (anaconda)
   Docker image Centos
   Spark nodes managed with Mesos.
   Run the docker image with spark-submit
  
Is there any restriction using this config ?

We do not want to use spark streaming but pykafka for memory reasons...

**Comment by emmett9001** [comment]
As far as pykafka itself is concerned, this configuration should be fine.
