### ISSUE TITLE
Monitor pykafka stream

### ISSUE THREAD

**Issue by arita37** [Parsely/pykafka#776]
Hi,

When running in production, just wondering how people are monitoring
pykafka streaming flows (producer sending message) ?

Is there any tool similar to Spark Streaming  monitor ?

**Comment by emmett9001** [comment]
@arita37 I assume you're referring to [this](https://spark.apache.org/docs/latest/monitoring.html#metrics). If so, pykafka does not include a pluggable metrics system at this time. There was a [ticket](https://github.com/Parsely/pykafka/issues/121) for this for a time, but as you can see from the comments on that ticket, pykafka probably isn't the place for a metrics tool beyond what it already includes in the [CLI module](https://github.com/Parsely/pykafka/blob/b1bf00778d3f6458d99ddc14bb5ebf9bbeee9fab/pykafka/cli/kafka_tools.py#L150). If you have suggestions for what metrics pykafka might include, please feel free to share them here.

For what it's worth, at Parse.ly our Kafka cluster monitoring is handled mostly by Datadog's monitoring agents that report on machine stats like load average and network throughput. We also generate Datadog graphs of consumer group lag using pykafka's CLI module. The combination of these two sources has proven to be enough for our use case.

**Comment by arita37** [comment]
Hello,
Some metrics like :
     throughput / second
     consumer lag

How the CLI output the consumer lag log ?
(on disk ?)

This is more of a format.








On Mar 16, 2018, at 1:34, Emmett J. Butler <notifications@github.com> wrote:

@arita37 I assume you're referring to this. If so, pykafka does not include a pluggable metrics system at this time. There was a ticket for this for a time, but as you can see from the comments on that ticket, pykafka probably isn't the place for a metrics tool beyond what it already includes in the CLI module. If you have suggestions for what metrics pykafka might include, please feel free to share them here.

For what it's worth, at Parse.ly our Kafka cluster monitoring is handled mostly by Datadog's monitoring agents that report on machine stats like load average and network throughput. We also generate Datadog graphs of consumer group lag using pykafka's CLI module. The combination of these two sources has proven to be enough for our use case.

―

**Comment by emmett9001** [comment]
The `fetch_consumer_lag` function in the CLI module [returns](https://github.com/Parsely/pykafka/blob/b1bf00778d3f6458d99ddc14bb5ebf9bbeee9fab/pykafka/cli/kafka_tools.py#L59) a dict mapping partition IDs to tuples of `(latest_available_offset, current_consumer_offset)`.
