### ISSUE TITLE
print_managed_consumer_groups fails with SocketDisconnectedError when listing consumer groups

### ISSUE THREAD

**Issue by aldraco** [Parsely/pykafka#777]
CLI command:
`kafka-tools -b <broker>:9092 print_managed_consumer_groups <topic>`

Traceback:
```
Traceback (most recent call last):
  File ".../bin/kafka-tools", line 11, in <module>
    sys.exit(main())
  File ".../pykafka/cli/kafka_tools.py", line 460, in main
    args.func(client, args)
  File ".../pykafka/cli/kafka_tools.py", line 133, in print_managed_consumer_groups
    groups = broker.list_groups().groups.keys()
  File ".../pykafka/broker.py", line 45, in wrapped
    return fn(self, *args, **kwargs)
  File ".../pykafka/broker.py", line 544, in list_groups
    return future.get(ListGroupsResponse)
  File ".../pykafka/handlers.py", line 74, in get
    raise self.error
pykafka.exceptions.SocketDisconnectedError: <broker ..redacted:9092>
```
This is a known topic on this broker and can be seen when running `print_topics`. 

Kafka 2.11-0.8.21

**Comment by emmett9001** [comment]
@aldraco Were you using the `.lan` host strings that are internal to our AWS network? Also, managed consumer groups are only supported in kafka >= 0.10 - our internal 0.8 cluster doesn't use them.

**Comment by aldraco** [comment]
No, I was using the broker name (first part), and like I mentioned above, it worked for `print_topics`. However, if we aren't managed consumer groups, that might explain why it couldn't find them. The error was just vague (which I understand may just be an artifact of how the interface between python/kafka is going to work).

Thanks! Will close.

**Comment by emmett9001** [comment]
I'm not actually sure if lack of support for the request this call is making would result in a `SocketDisconnected` error, but I suppose closing this is fine since the operation is definitely unsupported.
