### ISSUE TITLE
[question, but maybe problem?] is there any way to force the broker to use the same port used when accessing kafka?

### ISSUE THREAD

**Issue by joshsleeper** [Parsely/pykafka#780]
# versions
* `kafka 0.11.0.1`
* `pykafka 2.7.0`

# context
* running kafka (among other services) in a `docker-compose` cluster locally
* running kafka tests on the host machine, which means I'm using host ports mapped to internal container ports to get access to the container services
* ports for services are exposed at _random_ host ports
    * this is done by telling `docker-compose` which ports to expose for which container, but not telling it _which_ host ports to map to. in that case, `docker-compose` finds open ports on the system and maps the exposed internal ports to those.
    * e.g. kafka may use port `9092` inside the container, but be randomly mapped to `31953` on the host
* interested in querying the offset information for various topics with commands such as `pykafka.topic.Topic.latest_available_offsets()

# problem/experience
`pykafka.KafkaClient()` connects to kafka at the random port **just fine**, but always uses port `9092` when attempting to connect to the broker, which doesn't work because `9092` is only valid inside the container.

## example connection pseudocode
```py
from pykafka import KafkaClient

kafka_port = determine_random_kafka_port()
kclient = KafkaClient(hosts='127.0.0.1:{}'.format(kafka_port))
latest_offsets = kclient.topics['topic-name'].latest_available_offsets()
```

# question
as the title says, is there any way to get the broker connection to use the same port that's provided to `pykafka.KafkaClient()` in the `hosts` parameter?

**Comment by joshsleeper** [comment]
hey @emmett9001, so sorry for the delayed response.

i ended up solving my issue by monkey patching the connection function.
given that my interest was exclusively for testing, this is a fine solution for me.

as for my original suggestion, the more i read/learned about kafka, the more i realized that what i was asking for didn't make sense _except_ from a container-ized testing perspective.
what i essentially needed was to override zookeepers view of the kafka brokers, but in a way that doesn't actually make sense to zookeeper.
basically, it's nonsensical except for my very specific situation haha.

to avoid being a stereotypical example of a poster who magically solved their problem but gives no examples, here's a sample code block of how i resolved the issue i was having.

```py
import socket
import pykafka
import pytest

@pytest.fixture()
def kafka_client(mocker):
    rand_kafka_port = determine_random_kafka_port()

    def create_connection(address, *args):
        '''
        monkey-patching to facilitate kafka broker connection at random host port
        '''
        if address == (CONTAINER_KAFKA_NAME, CONTAINER_KAFKA_PORT):
            address = ('127.0.0.1', rand_kafka_port)
        return socket.create_connection(address, *args)

    mocker.patch(
        'pykafka.handlers.ThreadingHandler.Socket',
        create_connection=create_connection)

    return pykafka.KafkaClient('{}:{}'.format(CONTAINER_KAFKA_NAME, CONTAINER_KAFKA_PORT))
```

**Comment by emmett9001** [comment]
@joshsleeper Thanks for the detailed explanation, I bet this will help someone out in the future. I'm adding it to the `info-archive` tag for posterity.
