### ISSUE TITLE
Subscribe to a regex topic pattern in pykafka?

### ISSUE THREAD

**Issue by vikt0rs** [Parsely/pykafka#786]
Hello, folks,

please, suggest, if there is a possibility in pykafka to get a consumer, subscribed to the topic pattern (not a single topic) as kafka-python [has](http://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafka.KafkaConsumer.subscribe) ?
If not - could you please suggest a workaround for this feature?

Thanks,
Viktor

**Comment by emmett9001** [comment]
Consumers in pykafka can only subscribe to one topic at a time, so regex subscription from a single consumer is not supported. It's blocked by https://github.com/Parsely/pykafka/issues/354.

The closest you could get to this in pykafka's current form is something like this:
```python
import re
from pykafka import KafkaClient
expr = re.compile(MY_TOPIC_REGEX)
client = KafkaClient(hosts=MY_HOSTS)
consumers = {}
for topic_name, topic in client.topics.items():
    if expr.match(topic_name):
        consumers[topic_name] = topic.get_simple_consumer()
```

**Comment by vikt0rs** [comment]
@emmett9001 thanks a lot!
