### ISSUE TITLE
Producer linger_ms=0 blocks gevent

### ISSUE THREAD

**Issue by carsonip** [Parsely/pykafka#788]
**PyKafka version**: 2.8.0dev2 (master) (but any would do)
**Kafka version**: 0.10+, 1.0+ (but any would do)

I am using Gevent handler.
To flush messages right away, I set `linger_ms=0` in producer. When there is no message, it keeps flushing in queue_reader and effectively blocks the whole program. I can imagine that the threaded version will not really "block" but a high CPU usage may be observed.

I realize that to flush when there is at least 1 message, `min_queued_messages=1` should be used. 

However, the inline comment says:

> linger_ms=0 indicates no lingering.

without indicating the consequences, which may be misleading. If there is no plan to change the flush loop, I suggest adding a note of the consequences of `linger_ms=0`.

**Comment by carsonip** [comment]
This reminds me of the other problem, which is the flush code is still run every 5000ms (default linger_ms). Although the performance impact is minimal, is it possible to block until there is something in queue? I suppose it is possible with gevent queues but the code will be less generic then. I still don't think any code changes are needed but I'm just writing this as a note to other users / developers.

**Comment by emmett9001** [comment]
@carsonip Thanks for pointing this out. Waiting to flush until the queue actually contains messages is worth adding in my opinion. It doesn't make a ton of sense that `flush` is called even in cases where no messages are ready to be sent. This would fix your `linger_ms=0` issue as well.

**Comment by emmett9001** [comment]
@carsonip Let me know your thoughts on the proposed fix in https://github.com/Parsely/pykafka/pull/799. Essentially this change causes the flusher thread to wait indefinitely once it's completed a full linger timeout and there are no messages in its queue. This wait is only broken when a message is added to the queue or `stop()` is called. This solution is agnostic to the value of `linger_ms` - it essentially adds a "sleeping" mode to the producer's operation which is automatically entered after lingering and finding an empty queue.

I'd appreciate any feedback you have. If you're able to test my change yourself and see if it fixes your issue, that would be great too.
