### ISSUE TITLE
pykafka.exceptions.SocketDisconnectedError: when call function broker.list_groups().groups.keys()

### ISSUE THREAD

**Issue by foreversunyao** [Parsely/pykafka#792]
Hello,

The environment is as below:
**PyKafka version**: 
pykafka-tools (0.1.8)  - The pykafka-tools extend the functionalities of python pykafka module.
pykafka (2.7.0)        - Full-Featured Pure-Python Kafka Client
**Kafka version**: 0.8.2.1

And I used python 2.7 and when I call function as below:
```
client = KafkaClient(hosts=kafka_brokers)
topics = client.topics
brokers = client.brokers
consumer_groups = []
for broker_id, broker in brokers.iteritems():
        consumer_groups = consumer_groups + broker.list_groups().groups.keys()
```
seems all work well except  **broker.list_groups().groups.keys()**

the stack trace message are below:
```
Traceback (most recent call last):
  File "/opt/kafka_consumer_offset_check.py", line 49, in <module>
    consumer_groups = consumer_groups + broker.list_groups().groups.keys()
  File "/usr/lib/python2.7/site-packages/pykafka/broker.py", line 45, in wrapped
    return fn(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pykafka/broker.py", line 544, in list_groups
    return future.get(ListGroupsResponse)
  File "/usr/lib/python2.7/site-packages/pykafka/handlers.py", line 74, in get
    raise self.error
pykafka.exceptions.SocketDisconnectedError: <broker ip:9092>
```

And I can guarantee  to connect broker ip and port, and the same code works well when request kafka 1.0 version.

**Comment by emmett9001** [comment]
@foreversunyao The administrative API, which contains the `ListGroupsRequest` you're trying to use, is only [supported](https://github.com/Parsely/pykafka/pull/621) in Kafka >=0.10. Since you're using 0.8, it won't work.
