### ISSUE TITLE
'NoneType' object has no attribute 'api_versions'

### ISSUE THREAD

**Issue by rubenbouman** [Parsely/pykafka#793]
Hi @emmett9001 ,

I've got pykafka 2.7.0 installed and what I see is that when I try to connect to a Kafka cluster, which is disconnected at that time, the following error occurs:

'NoneType' object has no attribute 'api_versions'

Normally I should get a SocketDisconnectedError, but since a change in cluster.py which is incorporated in 2.7.0 the above error appears. The fetch_api_versions function is new and is being called once from the Cluster class constructor. The fetch_api_versions function is getting the api version info from the response object, but when a connection isn't possible, the following line in fetch_api_versions results in above error:

if response.api_versions:

And that's because reponse is None.

Would be nice if this could be fixed.

I'm referring to commit 80a74ca on URL:
https://github.com/Parsely/pykafka/commit/80a74cacc8f6d48d749a7a08432208f4cdc9c00d#diff-27e6827c14ac03e8b996238c6e8813be

Kind regards,
Ruben

**Comment by emmett9001** [comment]
Thanks for pointing this out, @rubenbouman. See the fix here https://github.com/Parsely/pykafka/pull/794
