### ISSUE TITLE
How to maintain SimpleConsumer and Producer connection

### ISSUE THREAD

**Issue by rubenbouman** [Parsely/pykafka#796]
Hi @emmett9001,

I'm looking for a proper way to handle connection error situations. I'm setting up different threads with each a KafkaClient connection and either a SimpleConsumer object or Producer object (trying with and without rdkafka). A consumer thread notes a connection problem very quickly and then generates an error like: "Unable to connect to a broker to fetch metadata.". But what do I need to do then? Simply clean the consumer and kafkaclient objects and setup a new connection?

And in case of the Producer: the producer doesn't notice a connection problem directly, so I want to monitor the connection every 10 seconds for example. I thought calling the latest_available_offsets every 10 seconds is an idea, to check the connection and if it's broken set it up again (by cleaning the kafkaclient and producer and setup a new connection).

I couldn't find a good reference how to implement this in a proper and stable way and if my thoughts are making any sense. So a reference to a good document / post or some help would be appreciated.

**Comment by emmett9001** [comment]
@rubenbouman In the case of the `SimpleConsumer`, the [failure](https://github.com/Parsely/pykafka/blob/fd8e89347bc48c2de7a9bc9a68dab5c5a84ef544/pykafka/cluster.py#L304) of the `MetadataRequest` can be caught by client code. In this case, the `SimpleConsumer` should be cleaned up, but the `KafkaClient` shouldn't need to be reinstantiated.

It's less clear to me what you're seeing in the `Producer` case. The `Producer` is designed to notice connection problems that render it unable to continue message production. However, it does attempt to continue producing messages if some but not all brokers are inaccessible - maybe this is what you're noticing?

For both of these cases, the most durable way to monitor connection status independent of production/consumption is probably to examine `[broker.connected for _, broker in KafkaClient.brokers]`, calling `client.update_cluster()` when there are any brokers not connected.

Hope that helps - I'll keep this ticket open as a reminder to document this a bit more clearly and in a [central location](http://pykafka.readthedocs.io/en/latest/usage.html).

**Comment by rubenbouman** [comment]
Hi @emmett9001 It's clear now. I was putting effort in handling error situations for both SimpleConsumer and Producer, but didn't realise pykafka was handling this for me ;-) I'm now successfully catching the failure on metadatarequest and getting a new SimpleConsumer on the existing KafkaClient.

For the Producer I was thinking that it wouldn't notice a failure because it isn't continuously listning like the consumer does (in my perception). So I thought it was necessary to implement a kind of ping/keepalive thing. But indeed, you're right, the Producer is noticing connection problems too and I do not have to code it myself.

So indeed, I think it would be nice to document this a bit more, to help others implementing a good recovery of failure situations.

**Comment by emmett9001** [comment]
See the note added to the usage guide here: https://github.com/Parsely/pykafka/commit/e7dd3097ed00069f848dc5b359961c8d8d7bdeb2
