### ISSUE TITLE
KeyError when connecting to partially started cluster

### ISSUE THREAD

**Issue by rubenbouman** [Parsely/pykafka#797]
Hi @emmett9001 

I have a Kafka cluster setup running 3 servers. I have a topic which has a replication-factor of 2. When I describe my topic, I see that Kafka configured my topic this way:

Topic: mytopic Partition: 0 Leader: 1 Replicas: 2,1 Isr: 1

So the topic is residing in Kafka servers 1 and 2. Then I start server 0 and 1 and I do not start server 2. In theory, mytopic is available on server 0, so I should be able to access this topic.

But when I start my application using pykafka 2.7.0, I'm getting a KeyError when calling:

`kafka_client_object.topics["mytopic"]`

Debugging into the topics property I see that my topic name is actually in the dictionary. Digging deeper I see that it's a custom dictionary of type TopicDict. Getting an item from this dict is calling __getitem__ function on TopicDict class. Within this function, a Topic class is instantiated:

`topic = Topic(self._cluster(), meta.topics[key])`

In the constructor of Topic the update function is called and that's were the error originates:
```python
if meta.id not in self._partitions:
  log.debug('Adding partition %s/%s', self.name, meta.id)
  self._partitions[meta.id] = Partition(
    self, meta.id,
    brokers[meta.leader],
    [brokers[b] for b in meta.replicas],   # <---- this line
    [brokers[b] for b in meta.isr],
  )
```
For mytopic meta.replicas holds 2,1 but there are only 2 brokers connected: 0,1. So when accessing broker[2] it is throwing an KeyError.

I think the solution is to just only append brokers to this list when the broker exists, but I can't oversee if this covers the whole issue.

**Comment by emmett9001** [comment]
Thanks for reporting this, @rubenbouman - it seems like an old oversight that's probably worth fixing now. I'll have to look a bit closer, though.

**Comment by rubenbouman** [comment]
Thank you @emmett9001 If you need any help or testing, plz let me know!

**Comment by emmett9001** [comment]
@rubenbouman I'm unable to replicate your issue locally, but it makes sense to me theoretically. I've put together https://github.com/Parsely/pykafka/pull/804 as a potential fix. Please let me know if that change fixes your issue, as well as any other thoughts you have or information on how to replicate the error.

**Comment by rubenbouman** [comment]
@emmett9001 I tested it in my environment, and the probleem indeed is fixed! Tnx for that.

My setup: 3 kafka servers on one machine making a cluster of 3 with 1 zookeeper, running kafka 0.10.2.0 and since today 1.1.0. I create a topic with the following settings:

bin/kafka-topics.sh --zookeeper localhost:2181 --create --replication-factor 2 --partitions 1 --topic mytopic

So a replication factor of 2 on 3 servers. When having 2 out of three Kafka servers running, my application gives the KeyError while running pykafka 2.7.0. With your fix, the KeyError is gone and the problem seems fixed!

Thanks!

**Comment by emmett9001** [comment]
Hm, that exactly matches my local testing setup (except for Kafka broker version). I wonder why it's not working. Either way, this fix seems innocuous to me and I'm happy to merge it.
