### ISSUE TITLE
logging issue in cluster.py

### ISSUE THREAD

**Issue by BonuV** [Parsely/pykafka#800]
Hi,
Facing json searlizing issue while logging the logs .
In cluster.py , consumer_group value  is used  for logging which is basically a bytes type  provided while connecting.

Iis there any way to supress the library logs

**PyKafka version**: d710898
**Kafka version**: NA

**Comment by emmett9001** [comment]
@BonuV Thanks for the ticket. Please provide a copy-pasted error traceback or message along with the code you're running to trigger the error you're seeing. Without those, it's not possible to debug your issue. I'm closing the issue, but please comment and reopen if you have additional information. Thanks again.
