### ISSUE TITLE
Help with message serialization 

### ISSUE THREAD

**Issue by georgeha** [Parsely/pykafka#806]
**PyKafka version**: '2.7.0'
**Kafka version**: Latest

Hello,
I am trying to use pickle to serialize the messages that I am producing.

```
with topic.get_sync_producer( max_request_size=21000012) as producer:
    #producer.produce(unp)
    producer.produce(pfile)
```

with pickle this is how I serialize my messages:

```
pfile = pickle.dumps(data, pickle.HIGHEST_PROTOCOL)
```

How can I use pickle for that and not utf-8?

Thanks

**Comment by emmett9001** [comment]
@georgeha If you're asking about the [serializer interface](https://github.com/Parsely/pykafka/blob/97c764a860429d7a59e2680fd41aeee6a001d28b/pykafka/producer.py#L83) on the `Producer`, it's a convenience but not a necessity. Without it, you can do something like this to serialize your messages:
```python
with topic.get_sync_producer( max_request_size=21000012) as producer:
    for data in generate_data():
        pfile = pickle.dumps(data, pickle.HIGHEST_PROTOCOL)    
        producer.produce(pfile)
```
If you wanted to implement this logic as a serializer function, you could follow the [example implementation](https://github.com/Parsely/pykafka/blob/97c764a860429d7a59e2680fd41aeee6a001d28b/pykafka/utils/__init__.py#L31), replacing calls to `encode` with calls to `pickle.dumps`.

Please comment or reopen if you have additional questions, and thanks for using pykafka.
