### ISSUE TITLE
Question on multi threading

### ISSUE THREAD

**Issue by rubinatorz** [Parsely/pykafka#808]
Hi @emmett9001,

I've got a multi threaded application, where each thread consumes from or produces to a specific topic. It's a Python application with Threading module (so not using multiprocessing). Am I right when I implement a KafkaClient connection per thread? Or is it better to use one connection in my entire application and "re-use" it in the different threads? I can image that consuming multiple topics and producing to multiple topics through one KafkaClient creates a kind of funnel which could lead to silting up? What is your advice on this?

Thanks!

**Comment by emmett9001** [comment]
I'd recommend one `KafkaClient` instance per *process* - sharing the same client across multiple *threads* shouldn't be a problem. Consuming the same topic from multiple threads can get a bit hairy, but if each thread is talking to its own topic, this setup should be fine. Something similar has worked for me in the past.
