### ISSUE TITLE
client CPU 100% after brokers restart

### ISSUE THREAD

**Issue by lokesh-b** [Parsely/pykafka#816]
**PyKafka version**: 2.5.0 (Also happens in 2.7.0)
**Kafka version**: 0.10.2.1

Steps to Reproduce:

1. Start Kafka server with multiple brokers say 5 and 15 partitions 
2. Set replication factor of a test topic to maybe 3
3. Start python client with gunicorn
4. Send messages to test topic (Maybe greater than 10 CPM)
4. Do rolling restart of brokers
5. Watch out for the CPU percentage of gunicorn workers
6. Repeat step 4. At some point you will see python CPU usage of one or more workers reach 100%

Below screenshot shows you that _produce method is in loop forever because it doesn't have the right owned brokers list.
![image](https://user-images.githubusercontent.com/5994573/41320640-6f1c216e-6e55-11e8-9e65-2e101b7dcacb.png)

Screenshot which shows the cpu usage of the worker:
![pykafka2](https://user-images.githubusercontent.com/5994573/41320699-b0198094-6e55-11e8-9bf0-10d2819e8e6d.png)

Screenshot which shows the leader ID is right but the owned_brokers dict is not updated.
![image](https://user-images.githubusercontent.com/5994573/41320778-fb89ec4e-6e55-11e8-8a91-ec3c9bdbda51.png)

Please advice on what can be done here. Thanks

**Comment by emmett9001** [comment]
Thanks @lokesh-b, this looks like a real issue.

**Comment by lokesh-b** [comment]
@emmett9001 Could you please review https://github.com/Parsely/pykafka/pull/819 and let me know if this can help in fixing this issue. Thanks.
