### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by pri22296** [Parsely/pykafka#823]
Hi, I'm using kafka as a queue for web crawling. I noticed that some times some spiders just hang and stop crawling. I noticed the following exception from pykafka each time the spider hangs. Any help would be appreciated.

```
Exception in thread 35: pykafka.SimpleConsumer.autocommiter:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/priyam.singh/venv/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 387, in autocommitter
    self.cleanup()
ReferenceError: weakly-referenced object no longer exists
```

**PyKafka version**: 2.7.0

**Comment by emmett9001** [comment]
Thanks for filing this report, @pri22296. I'll need a bit more example code to properly diagnose the issue. Can you post some code that shows how you're using pykafka?

From the look of it, you might be instantiating a consumer outside of a thread and then attempting to use it in a thread.

**Comment by pri22296** [comment]
Hi, I'm using pykafka within scrapy framework which itself is single threaded and I'm not spawning any new threads. This is how I am instantiating the consumer
```
consumer = topic.get_balanced_consumer(consumer_timeout_ms=25,
                                       auto_commit_enable=True,
                                       consumer_group=self.consumer_group)
```

**Comment by emmett9001** [comment]
You might be attempting to use the `consumer` in a context where it's already been garbage collected. This would explain the weakref error, since the autocommitter thread is trying to operate on an object that no longer exists. Is there anywhere in your code where you might be manually cleaning up the consumer instance without first calling `stop()` on it?

**Comment by emmett9001** [comment]
It's also worth looking through https://github.com/Parsely/pykafka/issues/422 to see if any of the examples listed there look similar to your issue.

**Comment by pri22296** [comment]
This only happens when I'm using the auto_commi optiont. If I commit manually on regular intervals, this issue does not occur. My code is supposed to run 'forever'. So I'm never cleaning up any consumer instances.

**Comment by vikt0rs** [comment]
this issue is the reason we don't use the latest pykafka version :(

@emmett9001 - from my side it seems that this happens after commit https://github.com/Parsely/pykafka/commit/bed40690ed01955b0f703806f75328c373a76cab - could you please suggest?

**Comment by emmett9001** [comment]
Thanks for the info @vikt0rs and @pri22296. I've opened https://github.com/Parsely/pykafka/pull/827 that I think fixes this issue. If you're able, please test your use cases with that banch and let me know here if it does indeed fix the problem. Thanks!

**Comment by emmett9001** [comment]
This is not fully fixed https://github.com/Parsely/pykafka/pull/827#issuecomment-435072567

**Comment by emmett9001** [comment]
https://github.com/Parsely/pykafka/pull/891
