### ISSUE TITLE
Efficiently pulling latest message from a topic

### ISSUE THREAD

**Issue by rueberger** [Parsely/pykafka#829]
I am interested in a method to efficiently pull the last message from an existing consumer

After a little bit of digging I've come up with the following incantation

```python
consumer = client = KafkaClient(hosts="xxxxxxx")
topic = client.topics['mytopic']
consumer = topic.get_simple_consumer()

def consume_latest():
     latest_offsets = [
           (partition, pykafka.common.OffsetType.LATEST) for partition in consumer._partitions.keys()
        ]
     consumer.reset_offsets(latest_offsets)
     # now step the offset back by one to fetch the latest...
     almost_latest_offsets = []
     for partition, owned_partition in consumer._partition.items():
         almost_latest_offsets.append(
              (partition, owned_partition.next_offset - 1)
          )

     consumer.reset_offsets(almost_latest_offsets)
     return consumer.consume()
```

which looks a little funky but to me but I _think_ it should work. However because of the funkiness I wanted to check if there might be better way to do it?

**Comment by emmett9001** [comment]
See https://github.com/Parsely/pykafka/issues/601#issuecomment-247143250 for the canonical method for this. It should probably be added to the [usage guide](https://github.com/Parsely/pykafka/blob/master/doc/usage.rst).

**Comment by rueberger** [comment]
Thanks @emmett9001. I did see that comment, but as far as I understand the logic there will reset the offset to the latest upon consumer creation and subsequently step through new messages sequentially. 

Whereas I am after a method to adjust the offset and consume the latest message, for an existing consumer. So repeated calls to `consume_latest()` will always return`messages[-1]`. Only interested in simple consumers/single partitions for the time being. 

Since the original post I have realized that I can use negative indices for offsets, so my current best guess for the incantation is

```python
consumer = client = KafkaClient(hosts="xxxxxxx")
topic = client.topics['mytopic']
consumer = topic.get_simple_consumer()

def consume_latest():
     latest_offsets = [
           (partition, -2) for partition in consumer._partitions.keys()
        ]
     consumer.reset_offsets(latest_offsets)
     return consumer.consume()
```

although this doesn't handle empty topics nicely - I would like it to return None instead of hanging for that case. 

The desired behavior is as follows:

```python
assert consume_latest() is None

producer = topic.get_sync_producer()
producer.produce('1'.encode())
assert consume_latest().value == '1'.encode()

producer.produce('2'.encode())
producer.produce('3'.encode())
assert consume_latest().value == '3'.encode()
```

**Comment by emmett9001** [comment]
I'm afraid I still don't understand the difference between the canonical example and what you're looking for. The [standard pattern](https://github.com/Parsely/pykafka/issues/601#issuecomment-247143250) does reset offsets to `LATEST` (`-1`, not `-2`), but this is used only for the purpose of discovering the actual latest offset so that `1` can be subtracted from it to get the offset of the current last message instead of the "next" message to be added to the partition. In fact, this logic is nearly identical to what you posted in the OP. With this logic, you should be able to implement `consume_latest` by resetting the offset on an existing consumer to `LATEST`, then resetting that consumer's offsets to `partition.next_offset - 1` and consuming. The key insight is that the initial reset to `LATEST` can happen either on instantiation or on an existing consumer.

**Comment by rueberger** [comment]
Ah, thanks for working through this with me, that did the trick. 

Where my internal model was going wrong was that I was putting the split between initialization and step in the wrong place. 

As 

```python
client = KafkaClient(hosts="xxxxxxx")
topic = client.topics['mytopic']
consumer = topic.get_simple_consumer(
    auto_offset_reset=OffsetType.LATEST,
    reset_offset_on_start=True)
LAST_N_MESSAGES = 1

def consume_latest()
    offsets = [(p, op.next_offset - LAST_N_MESSAGES - 1) for p, op in consumer._partitions.iteritems()]
    consumer.reset_offsets(offsets)
     return consumer.consume()
```

instead of 

```python
client = KafkaClient(hosts="xxxxxxx")
topic = client.topics['mytopic']
LAST_N_MESSAGES = 1

def consume_latest()
    consumer = topic.get_simple_consumer(
        auto_offset_reset=OffsetType.LATEST,
        reset_offset_on_start=True
    )
    offsets = [(p, op.next_offset - LAST_N_MESSAGES - 1) for p, op in consumer._partitions.iteritems()]
    consumer.reset_offsets(offsets)
     return consumer.consume()
```
(the extra -1 compensates for `op.next_offset` being current offset + 1)

The latter does what I want (just tested). 

I guess my hang up was not treating `SimpleConsumer`s as ephemeral. They are ephemeral, right? Initialization is cheap?  

My two cents on docs: I think some simple examples that step through common operations with a nice diagram showing topic contents and consumer offset pointers would work wonders in illustrating basic `kafka` mechanics and  `pykafka` usage. Whether this would be widely useful I think would depend on what the use case for typical users of `pykafka` are. For the time-being, my use cases are relatively simple (single partitions only), which uses such a small subset of `kafka`'s full complexity that I had a hard time finding what I wanted to know at a glance from `kafka`'s ponderous docs.

**Comment by rueberger** [comment]
One more thing: 

This snippet fails when a topic contains only one message. In this case offsets will be like `[(partition, -1)`, and since `-1` is a special offset that is interpreted as latest the offset will not be properly reset.

I think this should fix it:

```
client = KafkaClient(hosts="xxxxxxx")
topic = client.topics['mytopic']
LAST_N_MESSAGES = 1

def consume_latest()
    consumer = topic.get_simple_consumer(
        auto_offset_reset=OffsetType.LATEST,
        reset_offset_on_start=True
    )
    offsets = [(p, op.next_offset - LAST_N_MESSAGES - 1) for p, op in consumer._partitions.iteritems()]
    offsets = [(p, o) if o != -1 else (p, -2) for p, o in offsets]
    consumer.reset_offsets(offsets)
    return consumer.consume()
```

**Comment by emmett9001** [comment]
@rueberger I don't actually see that this is the case. The example uses `next_offset`, which is [set](https://github.com/Parsely/pykafka/blob/f95258719de63b0d0870cb7df0ad451e73b22129/pykafka/simpleconsumer.py#L872) to `0` on initialization. This means that in the case where only one of many partitions has a single message on it, most partitions will have a `next_offset` of `0` and the partition with the message will have a `next_offset` of `1`. This is corroborated by my local testing. For this reason, I think it's safe to simply add a `max(0, op.next_offset - LAST_N_MESSAGES)` to the documentation example.
