### ISSUE TITLE
Revisit SimpleConsumer.reset_offsets

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#830]
With the knowledge gained [here](https://github.com/Parsely/pykafka/blob/83e61962d240448f8c611971157376d4866101a0/pykafka/topic.py#L113), the logic [here](https://github.com/Parsely/pykafka/blob/83e61962d240448f8c611971157376d4866101a0/pykafka/simpleconsumer.py#L696) in `SimpleConsumer.reset_offsets` can probably be improved to address issues like https://github.com/Parsely/pykafka/issues/733 and https://github.com/Parsely/pykafka/issues/187#issuecomment-403971167.

**Comment by emmett9001** [comment]
Opened https://github.com/Parsely/pykafka/pull/834 that addresses this cc @rueberger

**Comment by emmett9001** [comment]
How many log segments does your topic have @rueberger? If it's just one, I think this might be the expected behavior.

**Comment by rueberger** [comment]
Ah, thanks, I did not read the docstring for reset_offsets carefully enough.

**Comment by emmett9001** [comment]
Doing all of my local testing with a single log segment a few years ago is a big part of the reason this took me so long to figure out. Nowhere in the documentation of Kafka itself is the behavior of this API clearly explained.
