### ISSUE TITLE
Standardize timestamp interfaces

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#833]
There are a few functions in the public API that accept timestamps, for example [`Topic.fetch_offset_limits`](https://github.com/Parsely/pykafka/blob/83e61962d240448f8c611971157376d4866101a0/pykafka/topic.py#L110). All such functions should accept a `datetime.datetime` instance instead of `int` or any other type.

**Comment by emmett9001** [comment]
https://github.com/Parsely/pykafka/pull/834 addresses this for `SimpleConsumer.reset_offsets` and `BalancedConsumer.reset_offsets`.

**Comment by emmett9001** [comment]
#837 addresses this for `Topic.fetch_offset_limits` and `Partition.fetch_offset_limit`.

**Comment by rueberger** [comment]
Are you targeting a `2.8.0` release for this?  If so, I wonder if it would be feasible to backport to `2.7` as well?

I only ask because I've noticed there are some breaking changes in `2.8.0` (namely unicode topic names). Not the end of the world either way.

**Comment by emmett9001** [comment]
@rueberger Where was the breaking change in `2.8.0`? I thought I took care to ensure that bytes were still accepted as topic names.

**Comment by rueberger** [comment]
You're probably right, I didn't read that carefully. It was just the unicode topic names.

**Comment by emmett9001** [comment]
I'm trying to avoid any backporting amongst 2.x versions. It might eventually happen when there's a 3.0 release, but we still need to accumulate a lot more deprecations for that to be worth it.

**Comment by rueberger** [comment]
That's fine, no reason to backport if topic names can still be bytes.
