### ISSUE TITLE
"Consuming the last N messages" example is broken

### ISSUE THREAD

**Issue by matthew-d-jones** [Parsely/pykafka#843]
The example code for "Consuming the last N messages from a topic" (http://pykafka.readthedocs.io/en/latest/usage.html#consuming-the-last-n-messages-from-a-topic) appears to get the last N - 2 messages rather than the last N. 

(note: using python 3.6)
```python
LAST_N_MESSAGES = 10  # adjust this depending on how many messages you want

consumer = topic.get_simple_consumer(
    auto_offset_reset=OffsetType.LATEST,
    reset_offset_on_start=True)
offsets = [(p, op.next_offset - LAST_N_MESSAGES) for p, op in consumer._partitions.items()]
consumer.reset_offsets(offsets)
consumer.consume()

for message in consumer:
    print("offset: " + str(message.offset))
```

Results in only the last 8 messages rather than the expected 10:
```
offset: 1071434
offset: 1071435
offset: 1071436
offset: 1071437
offset: 1071438
offset: 1071439
offset: 1071440
offset: 1071441
```
When 1071442 is the high watermark offset.

I observe this behaviour on pykafka 2.7.0 and current `master` (commit: 1ba51f6).

**Comment by emmett9001** [comment]
Thanks @matthew-d-jones. My guess is that this is two cooperating off-by-one errors.
