### ISSUE TITLE
feature request: allow log level configuration

### ISSUE THREAD

**Issue by cdaringe** [Parsely/pykafka#860]
**Kafka version**: 2.x

# problem

`pykafka` can be _very, very noisy_, and doesn't expose any config for its logging mechanisms

# discussion

it would be great if we could config the loggers via any supported means

**Comment by emmett9001** [comment]
Thanks for the feedback, @cdaringe.

Something along these lines is the existing recommendation for how to manage noisy logging:
```
import logging
log = logging.getLogger(__file__)

console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
console_handler.setFormatter(formatter)
logging.getLogger("pykafka").addHandler(console_handler)
log.addHandler(console_handler)
```
It sounds like you'd like some interface in pykafka that ran something like this logic with a configurable logging level?

**Comment by cdaringe** [comment]
if throughout the lib `"pykafka"` is the logger name, then your proposed solution is good enough for me!

**Comment by emmett9001** [comment]
We should audit to ensure that the above method works comprehensively.

**Comment by carsonip** [comment]
pykafka uses only the `logging` module. In pykafka source, it looks like this:
```python
log = logging.getLogger(__name__)
log.info("RequestHandler.stop: about to flush requests queue")
```

Everything logs under `pykafka`. So logging can be configured just like other modules (e.g. [urllib3](https://stackoverflow.com/a/11029841/3315725)) like this in your code:
```python
logging.getLogger('pykafka').setLevel(logging.WARNING)
```
