### ISSUE TITLE
Pykafka failing with AttributeError: 'module' object has no attribute 'Timeout'

### ISSUE THREAD

**Issue by mukkanti1241** [Parsely/pykafka#865]
Hi,

I started building Kafka application using Pykafka and ended up with issues. Please help me out to fix it.
I am getting the following error when I executed.

File "C:\Users\167212\Anaconda2\lib\site-packages\kazoo\handlers\gevent.py", line 63, in SequentialGeventHandler
class timeout_exception(gevent.event.Timeout):

AttributeError: 'module' object has no attribute 'Timeout'
![pykafka error](https://user-images.githubusercontent.com/40744137/45630403-a0159680-ba66-11e8-8863-5dd3bbf7459f.png)

I am using the following versions:
pykafka-2.7.0
kazoo-2.4.0
tabulate-0.8.2
conda-4.5.11

Please find the attached screen shot and help me out ASAP.

Thanks,
Mukkanti

**Comment by emmett9001** [comment]
Hi @mukkanti1241. This issue was addressed in https://github.com/Parsely/pykafka/issues/801 and can be fixed by upgrading to pykafka 2.8.0-dev.3

**Comment by mukkanti1241** [comment]
Thanks. It's working fine now.
