### ISSUE TITLE
Consumer Fetcher Thread exits due to connection issue

### ISSUE THREAD

**Issue by rvsharath** [Parsely/pykafka#895]
I Have a client which is making a call to create a consumer and i see that from the logs, initial connection to the broker is established successfully. 

log output:
    2018-12-05 11:46:43,549:pykafka.connection:connection:connect:164:DEBUG:Connecting to broker1:9092
  2018-12-05 11:46:43,751:pykafka.connection:connection:connect:174:DEBUG:Successfully connected to broker1:9092
                   .....................................
                   .....................................

 2018-12-05 11:46:44,200:pykafka.simpleconsumer:simpleconsumer:_setup_fetch_workers:454:INFO:Starting 1 fetcher threads
                         .......................................
                         .......................................

--> after this point the control comes back to the client which made a call to get_simple_consumer, since no exception was thrown at this point, i went ahead and tried to consume(). 

2018-12-05 12:02:22,832:pykafka.simpleconsumer:simpleconsumer:fetch:810:INFO:Updating cluster in response to error in fetch() for broker id 1 
2018-12-05 12:02:22,834:pykafka.connection:connection:connect:164:DEBUG:Connecting to broker1:9092
                         ..................After multiple attempts..........
                         .................................................................
2018-12-05 12:06:55,810:pykafka.cluster:cluster:_request_random_broker:284:ERROR:Socket disconnected during request for broker broker1:9092. Continuing.
    167 2018-12-05 12:06:55,811:pykafka.simpleconsumer:simpleconsumer:fetcher:453:DEBUG:Fetcher thread exiting

When pykafka spawned the fetcher thread, it was unable to connect to the broker to update the cluster with offset information. After multiple retrials, the fetcher thread exited. In client i have an implementation to repeatedly try if there is SocketDisconnectedError, if so then it continuously retries. 

is it by design that the main thread does not yeild to see if the fetcher thread successfully connected to the broker?

**Comment by rvsharath** [comment]
Reopening with more details

**Comment by emmett9001** [comment]
Thanks for the report, @rvsharath. I don't think this is by design - it would be nice to have an exception raised in this case. Part of what makes that complex is that the connection is attempted on a non-main thread, so an exception can't be raised until the client code makes another call to the library.

**Comment by rvsharath** [comment]
Thanks for your timely reply @emmett9001. Is there a mechanism to get the status of the fetcher thread? i can graceful handle such connection issues depending on the fetcher thread status.

**Comment by emmett9001** [comment]
There is not a public API that lets you directly access the status of the fetcher thread. The pattern for noticing connection errors is to catch `SocketDisconnectedError` from `consumer.consume()` calls, then call `consumer.stop(); consumer.start()`.

**Comment by rvsharath** [comment]
As a work around, we have client who takes care of restarting the consumer after certain number of retrials. I will try your suggestion aswell. thanks
