### ISSUE TITLE
High CPU Utilization with Synchronous Producer

### ISSUE THREAD

**Issue by rjemanuele** [Parsely/pykafka#901]
Greetings!

I'm using pykafka 2.8.0 on Python 3.7.1.  When producing messages into my Kafka cluster I am experiencing very high CPU load on some secondary thread within my Python script.  I'm guessing this secondary thread is one created by the pykafka producer.

![screen shot 2018-12-31 at 3 35 29 pm 1](https://user-images.githubusercontent.com/377119/50569054-cc051100-0d11-11e9-94aa-409d5b8fadc6.png)

I am creating my producer as so:
`producer = kafka.topics['test_topic'].get_producer(delivery_reports=False, linger_ms=0, sync=True)`

A full example is at: https://github.com/rjemanuele/pykafka_debug

Thank you

**Comment by emmett9001** [comment]
Thanks for the report @rjemanuele. Since you're setting `linger_ms` to `0`, every message is sent in a separate network request, which can lead to a lot of unnecessary work in the producer's send thread. I'd try setting `linger_ms` to a value of at least 50.

**Comment by rjemanuele** [comment]
Hi @emmett9001, that test code is just designed to demonstrate the issue.  The process creates a kafka_client and emits one message to the kafka_client and then the process just waits until it gets a SIGTERM.  That is all that is required to reproduce the high CPU load with simple code.

In my actual application I'm emitting data at regular intervals within the python script using the same client and topic while it is run within Kubernetes.

For my system I have some low volume data topics that I want emitted with as low latency as possible.  (I did just try this with a linger of 20ms and the CPU load is reduced.)  Is there a better way to reduce the latency?

**Comment by emmett9001** [comment]
Ah, you're running into the producer busywaiting issue fixed in https://github.com/Parsely/pykafka/commit/b7c7ebca61fbc1a721871ba8158cc5a6d40962b4#diff-51640f24a528215a6771242d37cd98b5. Try setting the [`queue_empty_timeout_ms` kwarg on `Producer`](https://pykafka.readthedocs.io/en/latest/api/producer.html#pykafka.producer.Producer.__init__) to a positive integer. Doing so will slow down the producer's checks for more messages to flush, which are currently happening without any waiting.

**Comment by rjemanuele** [comment]
@emmett9001 Thank you.  Setting `queue_empty_timeout_ms` did the reduce load.  I'm just curious, isn't `b7c7ebc` in v2.8.0?

**Comment by emmett9001** [comment]
Yes it is. See the mention of `queue_empty_timeout_ms` in the 2.8.0 [release notes](https://github.com/Parsely/pykafka/releases/tag/2.8.0).

**Comment by rjemanuele** [comment]
@emmett9001 You're awesome, thank you!
