### ISSUE TITLE
librdkafka dependency and setup issues

### ISSUE THREAD

**Issue by carsonip** [Parsely/pykafka#920]
**PyKafka version**: 2.8.0

In setup.py, with CPython, it detects the existence of librdkafka and compile the extension by default. When it fails, it silently disables the librdkafka support.

When I set up the environment for librdkafka, I installed the system `librdkafka-dev` then I ran setup.py. And I actually bump into a silent error when I ran `pip install -e .`. I had to run `setup.py install` to see the error message:
```
running build_ext
building 'pykafka.rdkafka._rd_kafka' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c pykafka/rdkafka/_rd_kafkamodule.c -o build/temp.linux-x86_64-2.7/pykafka/rdkafka/_rd_kafkamodule.o
pykafka/rdkafka/_rd_kafkamodule.c: In function 'Producer_delivery_report_callback':
pykafka/rdkafka/_rd_kafkamodule.c:568:9: error: unknown type name 'rd_kafka_timestamp_type_t'
        rd_kafka_timestamp_type_t timestamp_type;
        ^
pykafka/rdkafka/_rd_kafkamodule.c:569:29: warning: implicit declaration of function 'rd_kafka_message_timestamp' [-Wimplicit-function-declaration]
        int64_t timestamp = rd_kafka_message_timestamp(rkmessage, &timestamp_ty
                            ^
pykafka/rdkafka/_rd_kafkamodule.c:570:31: error: 'RD_KAFKA_TIMESTAMP_NOT_AVAILABLE' undeclared (first use in this function)
        if (timestamp_type != RD_KAFKA_TIMESTAMP_NOT_AVAILABLE) {
                              ^
pykafka/rdkafka/_rd_kafkamodule.c:570:31: note: each undeclared identifier is reported only once for each function it appears in
pykafka/rdkafka/_rd_kafkamodule.c: In function 'Consumer_consume':
pykafka/rdkafka/_rd_kafkamodule.c:978:9: error: unknown type name 'rd_kafka_timestamp_type_t'
        rd_kafka_timestamp_type_t timestamp_type;
        ^
pykafka/rdkafka/_rd_kafkamodule.c:980:31: error: 'RD_KAFKA_TIMESTAMP_NOT_AVAILABLE' undeclared (first use in this function)
        if (timestamp_type == RD_KAFKA_TIMESTAMP_NOT_AVAILABLE) {
```

1. Is it possible to let users specify rdkafka support and fail the setup if the compilation fails? If the user expects rdkafa support, failing at setup sounds better than failing with ImportError at runtime.
2. Should we document the version of librdkafka needed for the extension to compile successfully? I got librdkafka 0.8.6 (the latest in apt for Ubuntu 16.04) but it doesn't compile. When I manually compile the v0.11.6 from GitHub, it works. There's a similar issue in confluent-kafka-python https://github.com/confluentinc/confluent-kafka-python/issues/230
3. Should we vendor librdkafka? git clone, git checkout to tag, compile and use that shared library file (or use extension)?

I could help with the fix and the doc but there are some decisions to be made. Thanks!

**Comment by carsonip** [comment]
https://github.com/confluentinc/confluent-kafka-python/issues/202 says librdkafka should be 0.9.4+.

**Comment by emmett9001** [comment]
Failing at runtime has been the preferred approach for [a while](https://github.com/Parsely/pykafka/issues/617#issuecomment-331299090), though I think failing at build time is preferable. We don't want to make librdkafka a requirement for all users who install pykafka, since it's perfectly valid to use pykafka without librdkafka. Failing when librdkafka couldn't be installed *and* allowing users to explicitly opt-in or opt-out of the librdkafka installation is the ideal scenario.

It's definitely a good idea to document the earliest supported version / preferred version of librdkafka.

Using a shared library already present on the user's machine sounds ok in theory, but I'm not sure whether that would work given that pykafka uses an [extension to librdkafka](https://github.com/Parsely/pykafka/blob/c816efae85625f4d8064cf9241b616bb6128c834/setup.py#L134) that I believe needs to be compiled into the library at build time.

**Comment by carsonip** [comment]
@emmett9001 
The simplest way to help users who want librdkafka is an environment variable that will fail the install when the c ext compilation fails. It would work like pynacl's `SODIUM_INSTALL` https://github.com/pyca/pynacl/blob/master/setup.py#L91 or sqlalchemy's `DISABLE_SQLALCHEMY_CEXT` https://github.com/sqlalchemy/sqlalchemy/blob/master/setup.py#L203

This will not break backward-compatibility because the c ext is still compiled by default but the fallback will be disabled when the env var is set. People who want rdkafka support would be certain whether they get it as long as they set the env var.

I'm not good at naming so please suggest any names you prefer. e.g. `RDKAFKA_SUPPORT` or a more verbose `PYKAFKA_RDKAFKA_COMPILE`.

With this switch, the c ext compilation can also be explicitly turned off.

**Comment by emmett9001** [comment]
Can you explain the difference between using an environment variable and using an [argument to `setup.py`](https://github.com/Parsely/pykafka/blob/cfccd8e673a22273133860b0f35ffd9122f98388/setup.py#L127), which pykafka already does? It sounds to me like they serve very similar purposes, and the latter has the benefit of not requiring additional configuration of the environment on systems where pykafka is to be installed.

**Comment by carsonip** [comment]
When people install pykafka, they do `pip install pykafka` or maybe `pip install pykafka[whatever]`. But whether the "whatever" extras_require is specified cannot be accessed in [line 189](https://github.com/Parsely/pykafka/blob/master/setup.py#L189) where we call `run_setup()` afaik.

Given this limitation, the most simple way to explicitly require rdkafka support is through env var which we can enforce it when we call `run_setup()`.

I feel kind of sleepy now, please let me know if I missed anything.

**Comment by emmett9001** [comment]
I see what you mean. I think it's reasonable to go ahead with the implementation of an envvar-based rdkafka condition in `setup.py`.
