### ISSUE TITLE
ManagedBalancedConsumer compacted_topic default value

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#923]
From Carl Gieringer on the mailing list:

----------------------------------------------------------------------

I am learning Kafka and PyKafka. I am wondering why ManagedBalancedConsumer uses a [default of True for compacted_topic](https://github.com/Parsely/pykafka/blob/7781e5523c1ed06df03d070d3571cc8bd620250c/pykafka/managedbalancedconsumer.py#L74) while both [SimpleConsumer](https://github.com/Parsely/pykafka/blob/7781e5523c1ed06df03d070d3571cc8bd620250c/pykafka/simpleconsumer.py#L77) and [BalancedConsumer](https://github.com/Parsely/pykafka/blob/7781e5523c1ed06df03d070d3571cc8bd620250c/pykafka/balancedconsumer.py#L104) use False as the default for this parameter.  I would think that strictly from an API design perspective, consistency between these defaults would have been preferable.  Is there a reason that the default differs for ManagedBalancedConsumer?

**Comment by emmett9001** [comment]
This is a bug. The default of `compacted_topic` on `ManagedBalancedConsumer` should be `False`.

**Comment by carlgieringer** [comment]
Thanks for creating this bug, Emmett.

**Comment by emmett9001** [comment]
No problem. Please feel free to pull request this change if you're interested.

**Comment by carsonip** [comment]
Since there's no PR yet, I'll do it.
